// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv_2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv_2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv_2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<18> conv_2::ap_ST_fsm_state1 = "1";
const sc_lv<18> conv_2::ap_ST_fsm_state2 = "10";
const sc_lv<18> conv_2::ap_ST_fsm_state3 = "100";
const sc_lv<18> conv_2::ap_ST_fsm_state4 = "1000";
const sc_lv<18> conv_2::ap_ST_fsm_state5 = "10000";
const sc_lv<18> conv_2::ap_ST_fsm_state6 = "100000";
const sc_lv<18> conv_2::ap_ST_fsm_state7 = "1000000";
const sc_lv<18> conv_2::ap_ST_fsm_state8 = "10000000";
const sc_lv<18> conv_2::ap_ST_fsm_state9 = "100000000";
const sc_lv<18> conv_2::ap_ST_fsm_state10 = "1000000000";
const sc_lv<18> conv_2::ap_ST_fsm_state11 = "10000000000";
const sc_lv<18> conv_2::ap_ST_fsm_state12 = "100000000000";
const sc_lv<18> conv_2::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<18> conv_2::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<18> conv_2::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<18> conv_2::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<18> conv_2::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<18> conv_2::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<32> conv_2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv_2::ap_const_lv32_2 = "10";
const sc_lv<1> conv_2::ap_const_lv1_0 = "0";
const sc_lv<32> conv_2::ap_const_lv32_3 = "11";
const sc_lv<32> conv_2::ap_const_lv32_4 = "100";
const sc_lv<32> conv_2::ap_const_lv32_5 = "101";
const sc_lv<32> conv_2::ap_const_lv32_6 = "110";
const sc_lv<32> conv_2::ap_const_lv32_7 = "111";
const sc_lv<32> conv_2::ap_const_lv32_8 = "1000";
const sc_lv<32> conv_2::ap_const_lv32_9 = "1001";
const sc_lv<32> conv_2::ap_const_lv32_B = "1011";
const sc_lv<32> conv_2::ap_const_lv32_C = "1100";
const sc_lv<32> conv_2::ap_const_lv32_D = "1101";
const sc_lv<32> conv_2::ap_const_lv32_E = "1110";
const sc_lv<32> conv_2::ap_const_lv32_F = "1111";
const sc_lv<32> conv_2::ap_const_lv32_10 = "10000";
const sc_lv<5> conv_2::ap_const_lv5_0 = "00000";
const sc_lv<32> conv_2::ap_const_lv32_1 = "1";
const sc_lv<1> conv_2::ap_const_lv1_1 = "1";
const sc_lv<10> conv_2::ap_const_lv10_0 = "0000000000";
const sc_lv<4> conv_2::ap_const_lv4_0 = "0000";
const sc_lv<16> conv_2::ap_const_lv16_0 = "0000000000000000";
const sc_lv<2> conv_2::ap_const_lv2_0 = "00";
const sc_lv<32> conv_2::ap_const_lv32_11 = "10001";
const sc_lv<32> conv_2::ap_const_lv32_A = "1010";
const sc_lv<10> conv_2::ap_const_lv10_16 = "10110";
const sc_lv<5> conv_2::ap_const_lv5_18 = "11000";
const sc_lv<5> conv_2::ap_const_lv5_1 = "1";
const sc_lv<5> conv_2::ap_const_lv5_16 = "10110";
const sc_lv<4> conv_2::ap_const_lv4_E = "1110";
const sc_lv<4> conv_2::ap_const_lv4_1 = "1";
const sc_lv<3> conv_2::ap_const_lv3_0 = "000";
const sc_lv<2> conv_2::ap_const_lv2_3 = "11";
const sc_lv<2> conv_2::ap_const_lv2_1 = "1";
const sc_lv<14> conv_2::ap_const_lv14_16 = "10110";
const bool conv_2::ap_const_boolean_1 = true;

conv_2::conv_2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    layerconv3_0_weight_U = new conv_2_layerconv3kbM("layerconv3_0_weight_U");
    layerconv3_0_weight_U->clk(ap_clk);
    layerconv3_0_weight_U->reset(ap_rst);
    layerconv3_0_weight_U->address0(layerconv3_0_weight_address0);
    layerconv3_0_weight_U->ce0(layerconv3_0_weight_ce0);
    layerconv3_0_weight_U->q0(layerconv3_0_weight_q0);
    layerconv3_0_bias_U = new conv_2_layerconv3lbW("layerconv3_0_bias_U");
    layerconv3_0_bias_U->clk(ap_clk);
    layerconv3_0_bias_U->reset(ap_rst);
    layerconv3_0_bias_U->address0(layerconv3_0_bias_address0);
    layerconv3_0_bias_U->ce0(layerconv3_0_bias_ce0);
    layerconv3_0_bias_U->q0(layerconv3_0_bias_q0);
    input_after_padding_U = new conv_2_input_aftemb6("input_after_padding_U");
    input_after_padding_U->clk(ap_clk);
    input_after_padding_U->reset(ap_rst);
    input_after_padding_U->address0(input_after_padding_address0);
    input_after_padding_U->ce0(input_after_padding_ce0);
    input_after_padding_U->we0(input_after_padding_we0);
    input_after_padding_U->d0(grp_pad_14_24_0_11_fu_295_output_r_d0);
    input_after_padding_U->q0(input_after_padding_q0);
    grp_pad_14_24_0_11_fu_295 = new pad_14_24_0_11("grp_pad_14_24_0_11_fu_295");
    grp_pad_14_24_0_11_fu_295->ap_clk(ap_clk);
    grp_pad_14_24_0_11_fu_295->ap_rst(ap_rst);
    grp_pad_14_24_0_11_fu_295->ap_start(grp_pad_14_24_0_11_fu_295_ap_start);
    grp_pad_14_24_0_11_fu_295->ap_done(grp_pad_14_24_0_11_fu_295_ap_done);
    grp_pad_14_24_0_11_fu_295->ap_idle(grp_pad_14_24_0_11_fu_295_ap_idle);
    grp_pad_14_24_0_11_fu_295->ap_ready(grp_pad_14_24_0_11_fu_295_ap_ready);
    grp_pad_14_24_0_11_fu_295->input_r_address0(grp_pad_14_24_0_11_fu_295_input_r_address0);
    grp_pad_14_24_0_11_fu_295->input_r_ce0(grp_pad_14_24_0_11_fu_295_input_r_ce0);
    grp_pad_14_24_0_11_fu_295->input_r_q0(input_r_q0);
    grp_pad_14_24_0_11_fu_295->output_r_address0(grp_pad_14_24_0_11_fu_295_output_r_address0);
    grp_pad_14_24_0_11_fu_295->output_r_ce0(grp_pad_14_24_0_11_fu_295_output_r_ce0);
    grp_pad_14_24_0_11_fu_295->output_r_we0(grp_pad_14_24_0_11_fu_295_output_r_we0);
    grp_pad_14_24_0_11_fu_295->output_r_d0(grp_pad_14_24_0_11_fu_295_output_r_d0);
    test_hadd_16ns_16eOg_U30 = new test_hadd_16ns_16eOg<1,2,16,16,16>("test_hadd_16ns_16eOg_U30");
    test_hadd_16ns_16eOg_U30->clk(ap_clk);
    test_hadd_16ns_16eOg_U30->reset(ap_rst);
    test_hadd_16ns_16eOg_U30->din0(grp_fu_303_p0);
    test_hadd_16ns_16eOg_U30->din1(grp_fu_303_p1);
    test_hadd_16ns_16eOg_U30->ce(ap_var_for_const0);
    test_hadd_16ns_16eOg_U30->dout(grp_fu_303_p2);
    test_hmul_16ns_16fYi_U31 = new test_hmul_16ns_16fYi<1,2,16,16,16>("test_hmul_16ns_16fYi_U31");
    test_hmul_16ns_16fYi_U31->clk(ap_clk);
    test_hmul_16ns_16fYi_U31->reset(ap_rst);
    test_hmul_16ns_16fYi_U31->din0(input_after_padding_q0);
    test_hmul_16ns_16fYi_U31->din1(layerconv3_0_weight_q0);
    test_hmul_16ns_16fYi_U31->ce(ap_var_for_const0);
    test_hmul_16ns_16fYi_U31->dout(grp_fu_310_p2);
    test_mul_mul_10nsncg_U32 = new test_mul_mul_10nsncg<1,1,10,6,14>("test_mul_mul_10nsncg_U32");
    test_mul_mul_10nsncg_U32->din0(mul_ln51_fu_710_p0);
    test_mul_mul_10nsncg_U32->din1(mul_ln51_fu_710_p1);
    test_mul_mul_10nsncg_U32->dout(mul_ln51_fu_710_p2);
    test_mul_mul_10nsncg_U33 = new test_mul_mul_10nsncg<1,1,10,6,14>("test_mul_mul_10nsncg_U33");
    test_mul_mul_10nsncg_U33->din0(mul_ln63_fu_716_p0);
    test_mul_mul_10nsncg_U33->din1(mul_ln63_fu_716_p1);
    test_mul_mul_10nsncg_U33->dout(mul_ln63_fu_716_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln31_fu_316_p2);
    sensitive << ( phi_mul_reg_144 );

    SC_METHOD(thread_add_ln47_1_fu_422_p2);
    sensitive << ( sext_ln47_reg_735 );
    sensitive << ( zext_ln47_2_fu_418_p1 );

    SC_METHOD(thread_add_ln47_2_fu_523_p2);
    sensitive << ( sext_ln47_3_reg_774 );
    sensitive << ( zext_ln47_5_fu_519_p1 );

    SC_METHOD(thread_add_ln47_3_fu_601_p2);
    sensitive << ( y_0_reg_168 );
    sensitive << ( zext_ln44_fu_585_p1 );

    SC_METHOD(thread_add_ln47_4_fu_558_p2);
    sensitive << ( sub_ln47_1_reg_769 );
    sensitive << ( zext_ln47_6_fu_554_p1 );

    SC_METHOD(thread_add_ln47_5_fu_611_p2);
    sensitive << ( sub_ln47_3_reg_787 );
    sensitive << ( zext_ln47_7_fu_607_p1 );

    SC_METHOD(thread_add_ln47_6_fu_625_p2);
    sensitive << ( sub_ln47_4_reg_792 );
    sensitive << ( zext_ln47_9_fu_621_p1 );

    SC_METHOD(thread_add_ln47_fu_513_p2);
    sensitive << ( x_0_reg_156 );
    sensitive << ( zext_ln41_fu_497_p1 );

    SC_METHOD(thread_add_ln51_1_fu_487_p2);
    sensitive << ( mul_ln51_reg_748 );
    sensitive << ( zext_ln51_2_fu_483_p1 );

    SC_METHOD(thread_add_ln51_fu_384_p2);
    sensitive << ( phi_mul_reg_144 );
    sensitive << ( zext_ln51_fu_380_p1 );

    SC_METHOD(thread_add_ln55_fu_635_p2);
    sensitive << ( phi_mul8_reg_261 );

    SC_METHOD(thread_add_ln63_1_fu_700_p2);
    sensitive << ( mul_ln63_reg_866 );
    sensitive << ( zext_ln63_3_fu_696_p1 );

    SC_METHOD(thread_add_ln63_fu_674_p2);
    sensitive << ( phi_mul8_reg_261 );
    sensitive << ( zext_ln63_1_fu_670_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln55_fu_641_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln55_fu_641_p2 );

    SC_METHOD(thread_grp_fu_303_p0);
    sensitive << ( output_r_q0 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( convsum_2_reg_227 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_grp_fu_303_p1);
    sensitive << ( tmp_8_reg_825 );
    sensitive << ( layerconv3_0_bias_lo_reg_853 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_grp_pad_14_24_0_11_fu_295_ap_start);
    sensitive << ( grp_pad_14_24_0_11_fu_295_ap_start_reg );

    SC_METHOD(thread_i1_fu_507_p2);
    sensitive << ( i1_0_reg_216 );

    SC_METHOD(thread_i_2_fu_647_p2);
    sensitive << ( i2_0_reg_250 );

    SC_METHOD(thread_i_fu_328_p2);
    sensitive << ( i_0_reg_133 );

    SC_METHOD(thread_icmp_ln31_fu_322_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_0_reg_133 );

    SC_METHOD(thread_icmp_ln34_fu_368_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( x_0_reg_156 );

    SC_METHOD(thread_icmp_ln36_fu_394_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( y_0_reg_168 );

    SC_METHOD(thread_icmp_ln39_fu_406_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j_0_reg_180 );

    SC_METHOD(thread_icmp_ln41_fu_501_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( i1_0_reg_216 );

    SC_METHOD(thread_icmp_ln44_fu_589_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( j1_0_reg_239 );

    SC_METHOD(thread_icmp_ln55_fu_641_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( i2_0_reg_250 );

    SC_METHOD(thread_icmp_ln57_fu_658_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( x3_0_reg_273 );

    SC_METHOD(thread_icmp_ln60_fu_684_p2);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( y4_0_reg_284 );

    SC_METHOD(thread_input_after_padding_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_pad_14_24_0_11_fu_295_output_r_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln47_8_fu_616_p1 );

    SC_METHOD(thread_input_after_padding_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_pad_14_24_0_11_fu_295_output_r_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_after_padding_we0);
    sensitive << ( grp_pad_14_24_0_11_fu_295_output_r_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( grp_pad_14_24_0_11_fu_295_input_r_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( grp_pad_14_24_0_11_fu_295_input_r_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_j1_fu_595_p2);
    sensitive << ( j1_0_reg_239 );

    SC_METHOD(thread_j_fu_412_p2);
    sensitive << ( j_0_reg_180 );

    SC_METHOD(thread_layerconv3_0_bias_address0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( zext_ln63_fu_653_p1 );

    SC_METHOD(thread_layerconv3_0_bias_ce0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_layerconv3_0_weight_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln47_10_fu_630_p1 );

    SC_METHOD(thread_layerconv3_0_weight_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_mul_ln51_fu_710_p0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( mul_ln51_fu_710_p00 );

    SC_METHOD(thread_mul_ln51_fu_710_p00);
    sensitive << ( add_ln51_fu_384_p2 );

    SC_METHOD(thread_mul_ln51_fu_710_p1);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_mul_ln63_fu_716_p0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( mul_ln63_fu_716_p00 );

    SC_METHOD(thread_mul_ln63_fu_716_p00);
    sensitive << ( add_ln63_fu_674_p2 );

    SC_METHOD(thread_mul_ln63_fu_716_p1);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( output_addr_reg_879 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( zext_ln51_3_fu_492_p1 );
    sensitive << ( zext_ln63_4_fu_705_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_fu_303_p2 );
    sensitive << ( convsum_0_reg_191 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln39_fu_406_p2 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_p_shl5_cast_fu_571_p3);
    sensitive << ( trunc_ln47_2_fu_567_p1 );

    SC_METHOD(thread_p_shl6_cast_fu_532_p3);
    sensitive << ( trunc_ln47_fu_528_p1 );

    SC_METHOD(thread_p_shl7_cast_fu_540_p3);
    sensitive << ( add_ln47_2_fu_523_p2 );

    SC_METHOD(thread_sext_ln47_1_fu_427_p1);
    sensitive << ( add_ln47_1_fu_422_p2 );

    SC_METHOD(thread_sext_ln47_2_fu_439_p1);
    sensitive << ( tmp_2_fu_431_p3 );

    SC_METHOD(thread_sext_ln47_3_fu_479_p1);
    sensitive << ( sub_ln47_2_fu_473_p2 );

    SC_METHOD(thread_sext_ln47_fu_364_p1);
    sensitive << ( sub_ln47_fu_358_p2 );

    SC_METHOD(thread_sub_ln47_1_fu_443_p2);
    sensitive << ( sext_ln47_2_fu_439_p1 );
    sensitive << ( sext_ln47_1_fu_427_p1 );

    SC_METHOD(thread_sub_ln47_2_fu_473_p2);
    sensitive << ( zext_ln47_3_fu_457_p1 );
    sensitive << ( zext_ln47_4_fu_469_p1 );

    SC_METHOD(thread_sub_ln47_3_fu_548_p2);
    sensitive << ( p_shl6_cast_fu_532_p3 );
    sensitive << ( p_shl7_cast_fu_540_p3 );

    SC_METHOD(thread_sub_ln47_4_fu_579_p2);
    sensitive << ( p_shl5_cast_fu_571_p3 );
    sensitive << ( trunc_ln47_1_fu_563_p1 );

    SC_METHOD(thread_sub_ln47_fu_358_p2);
    sensitive << ( zext_ln47_fu_342_p1 );
    sensitive << ( zext_ln47_1_fu_354_p1 );

    SC_METHOD(thread_tmp_1_fu_346_p3);
    sensitive << ( i_0_reg_133 );

    SC_METHOD(thread_tmp_2_fu_431_p3);
    sensitive << ( add_ln47_1_fu_422_p2 );

    SC_METHOD(thread_tmp_3_fu_449_p3);
    sensitive << ( j_0_reg_180 );

    SC_METHOD(thread_tmp_4_fu_461_p3);
    sensitive << ( j_0_reg_180 );

    SC_METHOD(thread_tmp_s_fu_334_p3);
    sensitive << ( i_0_reg_133 );

    SC_METHOD(thread_trunc_ln47_1_fu_563_p1);
    sensitive << ( add_ln47_4_fu_558_p2 );

    SC_METHOD(thread_trunc_ln47_2_fu_567_p1);
    sensitive << ( add_ln47_4_fu_558_p2 );

    SC_METHOD(thread_trunc_ln47_fu_528_p1);
    sensitive << ( add_ln47_2_fu_523_p2 );

    SC_METHOD(thread_x_2_fu_664_p2);
    sensitive << ( x3_0_reg_273 );

    SC_METHOD(thread_x_fu_374_p2);
    sensitive << ( x_0_reg_156 );

    SC_METHOD(thread_y_2_fu_400_p2);
    sensitive << ( y_0_reg_168 );

    SC_METHOD(thread_y_fu_690_p2);
    sensitive << ( y4_0_reg_284 );

    SC_METHOD(thread_zext_ln41_fu_497_p1);
    sensitive << ( i1_0_reg_216 );

    SC_METHOD(thread_zext_ln44_fu_585_p1);
    sensitive << ( j1_0_reg_239 );

    SC_METHOD(thread_zext_ln47_10_fu_630_p1);
    sensitive << ( add_ln47_6_fu_625_p2 );

    SC_METHOD(thread_zext_ln47_1_fu_354_p1);
    sensitive << ( tmp_1_fu_346_p3 );

    SC_METHOD(thread_zext_ln47_2_fu_418_p1);
    sensitive << ( j_0_reg_180 );

    SC_METHOD(thread_zext_ln47_3_fu_457_p1);
    sensitive << ( tmp_3_fu_449_p3 );

    SC_METHOD(thread_zext_ln47_4_fu_469_p1);
    sensitive << ( tmp_4_fu_461_p3 );

    SC_METHOD(thread_zext_ln47_5_fu_519_p1);
    sensitive << ( add_ln47_fu_513_p2 );

    SC_METHOD(thread_zext_ln47_6_fu_554_p1);
    sensitive << ( i1_0_reg_216 );

    SC_METHOD(thread_zext_ln47_7_fu_607_p1);
    sensitive << ( add_ln47_3_fu_601_p2 );

    SC_METHOD(thread_zext_ln47_8_fu_616_p1);
    sensitive << ( add_ln47_5_fu_611_p2 );

    SC_METHOD(thread_zext_ln47_9_fu_621_p1);
    sensitive << ( j1_0_reg_239 );

    SC_METHOD(thread_zext_ln47_fu_342_p1);
    sensitive << ( tmp_s_fu_334_p3 );

    SC_METHOD(thread_zext_ln51_2_fu_483_p1);
    sensitive << ( y_0_reg_168 );

    SC_METHOD(thread_zext_ln51_3_fu_492_p1);
    sensitive << ( add_ln51_1_fu_487_p2 );

    SC_METHOD(thread_zext_ln51_fu_380_p1);
    sensitive << ( x_0_reg_156 );

    SC_METHOD(thread_zext_ln63_1_fu_670_p1);
    sensitive << ( x3_0_reg_273 );

    SC_METHOD(thread_zext_ln63_3_fu_696_p1);
    sensitive << ( y4_0_reg_284 );

    SC_METHOD(thread_zext_ln63_4_fu_705_p1);
    sensitive << ( add_ln63_1_fu_700_p2 );

    SC_METHOD(thread_zext_ln63_fu_653_p1);
    sensitive << ( i2_0_reg_250 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln31_fu_322_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln34_fu_368_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln39_fu_406_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln41_fu_501_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln44_fu_589_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln55_fu_641_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( icmp_ln57_fu_658_p2 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( icmp_ln60_fu_684_p2 );
    sensitive << ( grp_pad_14_24_0_11_fu_295_ap_done );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln36_fu_394_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000001";
    grp_pad_14_24_0_11_fu_295_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv_2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, output_r_q0, "(port)output_r_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, layerconv3_0_weight_address0, "layerconv3_0_weight_address0");
    sc_trace(mVcdFile, layerconv3_0_weight_ce0, "layerconv3_0_weight_ce0");
    sc_trace(mVcdFile, layerconv3_0_weight_q0, "layerconv3_0_weight_q0");
    sc_trace(mVcdFile, layerconv3_0_bias_address0, "layerconv3_0_bias_address0");
    sc_trace(mVcdFile, layerconv3_0_bias_ce0, "layerconv3_0_bias_ce0");
    sc_trace(mVcdFile, layerconv3_0_bias_q0, "layerconv3_0_bias_q0");
    sc_trace(mVcdFile, add_ln31_fu_316_p2, "add_ln31_fu_316_p2");
    sc_trace(mVcdFile, add_ln31_reg_722, "add_ln31_reg_722");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_fu_328_p2, "i_fu_328_p2");
    sc_trace(mVcdFile, i_reg_730, "i_reg_730");
    sc_trace(mVcdFile, sext_ln47_fu_364_p1, "sext_ln47_fu_364_p1");
    sc_trace(mVcdFile, sext_ln47_reg_735, "sext_ln47_reg_735");
    sc_trace(mVcdFile, icmp_ln31_fu_322_p2, "icmp_ln31_fu_322_p2");
    sc_trace(mVcdFile, x_fu_374_p2, "x_fu_374_p2");
    sc_trace(mVcdFile, x_reg_743, "x_reg_743");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, mul_ln51_fu_710_p2, "mul_ln51_fu_710_p2");
    sc_trace(mVcdFile, mul_ln51_reg_748, "mul_ln51_reg_748");
    sc_trace(mVcdFile, icmp_ln34_fu_368_p2, "icmp_ln34_fu_368_p2");
    sc_trace(mVcdFile, y_2_fu_400_p2, "y_2_fu_400_p2");
    sc_trace(mVcdFile, y_2_reg_756, "y_2_reg_756");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, j_fu_412_p2, "j_fu_412_p2");
    sc_trace(mVcdFile, j_reg_764, "j_reg_764");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, sub_ln47_1_fu_443_p2, "sub_ln47_1_fu_443_p2");
    sc_trace(mVcdFile, sub_ln47_1_reg_769, "sub_ln47_1_reg_769");
    sc_trace(mVcdFile, icmp_ln39_fu_406_p2, "icmp_ln39_fu_406_p2");
    sc_trace(mVcdFile, sext_ln47_3_fu_479_p1, "sext_ln47_3_fu_479_p1");
    sc_trace(mVcdFile, sext_ln47_3_reg_774, "sext_ln47_3_reg_774");
    sc_trace(mVcdFile, i1_fu_507_p2, "i1_fu_507_p2");
    sc_trace(mVcdFile, i1_reg_782, "i1_reg_782");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, sub_ln47_3_fu_548_p2, "sub_ln47_3_fu_548_p2");
    sc_trace(mVcdFile, sub_ln47_3_reg_787, "sub_ln47_3_reg_787");
    sc_trace(mVcdFile, icmp_ln41_fu_501_p2, "icmp_ln41_fu_501_p2");
    sc_trace(mVcdFile, sub_ln47_4_fu_579_p2, "sub_ln47_4_fu_579_p2");
    sc_trace(mVcdFile, sub_ln47_4_reg_792, "sub_ln47_4_reg_792");
    sc_trace(mVcdFile, j1_fu_595_p2, "j1_fu_595_p2");
    sc_trace(mVcdFile, j1_reg_800, "j1_reg_800");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln44_fu_589_p2, "icmp_ln44_fu_589_p2");
    sc_trace(mVcdFile, input_after_padding_q0, "input_after_padding_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, grp_fu_310_p2, "grp_fu_310_p2");
    sc_trace(mVcdFile, tmp_8_reg_825, "tmp_8_reg_825");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_303_p2, "grp_fu_303_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, add_ln55_fu_635_p2, "add_ln55_fu_635_p2");
    sc_trace(mVcdFile, add_ln55_reg_835, "add_ln55_reg_835");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, i_2_fu_647_p2, "i_2_fu_647_p2");
    sc_trace(mVcdFile, i_2_reg_843, "i_2_reg_843");
    sc_trace(mVcdFile, icmp_ln55_fu_641_p2, "icmp_ln55_fu_641_p2");
    sc_trace(mVcdFile, layerconv3_0_bias_lo_reg_853, "layerconv3_0_bias_lo_reg_853");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, x_2_fu_664_p2, "x_2_fu_664_p2");
    sc_trace(mVcdFile, x_2_reg_861, "x_2_reg_861");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, mul_ln63_fu_716_p2, "mul_ln63_fu_716_p2");
    sc_trace(mVcdFile, mul_ln63_reg_866, "mul_ln63_reg_866");
    sc_trace(mVcdFile, icmp_ln57_fu_658_p2, "icmp_ln57_fu_658_p2");
    sc_trace(mVcdFile, y_fu_690_p2, "y_fu_690_p2");
    sc_trace(mVcdFile, y_reg_874, "y_reg_874");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, output_addr_reg_879, "output_addr_reg_879");
    sc_trace(mVcdFile, icmp_ln60_fu_684_p2, "icmp_ln60_fu_684_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, input_after_padding_address0, "input_after_padding_address0");
    sc_trace(mVcdFile, input_after_padding_ce0, "input_after_padding_ce0");
    sc_trace(mVcdFile, input_after_padding_we0, "input_after_padding_we0");
    sc_trace(mVcdFile, grp_pad_14_24_0_11_fu_295_ap_start, "grp_pad_14_24_0_11_fu_295_ap_start");
    sc_trace(mVcdFile, grp_pad_14_24_0_11_fu_295_ap_done, "grp_pad_14_24_0_11_fu_295_ap_done");
    sc_trace(mVcdFile, grp_pad_14_24_0_11_fu_295_ap_idle, "grp_pad_14_24_0_11_fu_295_ap_idle");
    sc_trace(mVcdFile, grp_pad_14_24_0_11_fu_295_ap_ready, "grp_pad_14_24_0_11_fu_295_ap_ready");
    sc_trace(mVcdFile, grp_pad_14_24_0_11_fu_295_input_r_address0, "grp_pad_14_24_0_11_fu_295_input_r_address0");
    sc_trace(mVcdFile, grp_pad_14_24_0_11_fu_295_input_r_ce0, "grp_pad_14_24_0_11_fu_295_input_r_ce0");
    sc_trace(mVcdFile, grp_pad_14_24_0_11_fu_295_output_r_address0, "grp_pad_14_24_0_11_fu_295_output_r_address0");
    sc_trace(mVcdFile, grp_pad_14_24_0_11_fu_295_output_r_ce0, "grp_pad_14_24_0_11_fu_295_output_r_ce0");
    sc_trace(mVcdFile, grp_pad_14_24_0_11_fu_295_output_r_we0, "grp_pad_14_24_0_11_fu_295_output_r_we0");
    sc_trace(mVcdFile, grp_pad_14_24_0_11_fu_295_output_r_d0, "grp_pad_14_24_0_11_fu_295_output_r_d0");
    sc_trace(mVcdFile, i_0_reg_133, "i_0_reg_133");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, phi_mul_reg_144, "phi_mul_reg_144");
    sc_trace(mVcdFile, x_0_reg_156, "x_0_reg_156");
    sc_trace(mVcdFile, icmp_ln36_fu_394_p2, "icmp_ln36_fu_394_p2");
    sc_trace(mVcdFile, y_0_reg_168, "y_0_reg_168");
    sc_trace(mVcdFile, j_0_reg_180, "j_0_reg_180");
    sc_trace(mVcdFile, convsum_0_reg_191, "convsum_0_reg_191");
    sc_trace(mVcdFile, convsum_1_reg_204, "convsum_1_reg_204");
    sc_trace(mVcdFile, i1_0_reg_216, "i1_0_reg_216");
    sc_trace(mVcdFile, convsum_2_reg_227, "convsum_2_reg_227");
    sc_trace(mVcdFile, j1_0_reg_239, "j1_0_reg_239");
    sc_trace(mVcdFile, i2_0_reg_250, "i2_0_reg_250");
    sc_trace(mVcdFile, phi_mul8_reg_261, "phi_mul8_reg_261");
    sc_trace(mVcdFile, x3_0_reg_273, "x3_0_reg_273");
    sc_trace(mVcdFile, y4_0_reg_284, "y4_0_reg_284");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, grp_pad_14_24_0_11_fu_295_ap_start_reg, "grp_pad_14_24_0_11_fu_295_ap_start_reg");
    sc_trace(mVcdFile, zext_ln51_3_fu_492_p1, "zext_ln51_3_fu_492_p1");
    sc_trace(mVcdFile, zext_ln47_8_fu_616_p1, "zext_ln47_8_fu_616_p1");
    sc_trace(mVcdFile, zext_ln47_10_fu_630_p1, "zext_ln47_10_fu_630_p1");
    sc_trace(mVcdFile, zext_ln63_fu_653_p1, "zext_ln63_fu_653_p1");
    sc_trace(mVcdFile, zext_ln63_4_fu_705_p1, "zext_ln63_4_fu_705_p1");
    sc_trace(mVcdFile, grp_fu_303_p0, "grp_fu_303_p0");
    sc_trace(mVcdFile, grp_fu_303_p1, "grp_fu_303_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp_s_fu_334_p3, "tmp_s_fu_334_p3");
    sc_trace(mVcdFile, tmp_1_fu_346_p3, "tmp_1_fu_346_p3");
    sc_trace(mVcdFile, zext_ln47_fu_342_p1, "zext_ln47_fu_342_p1");
    sc_trace(mVcdFile, zext_ln47_1_fu_354_p1, "zext_ln47_1_fu_354_p1");
    sc_trace(mVcdFile, sub_ln47_fu_358_p2, "sub_ln47_fu_358_p2");
    sc_trace(mVcdFile, zext_ln51_fu_380_p1, "zext_ln51_fu_380_p1");
    sc_trace(mVcdFile, add_ln51_fu_384_p2, "add_ln51_fu_384_p2");
    sc_trace(mVcdFile, zext_ln47_2_fu_418_p1, "zext_ln47_2_fu_418_p1");
    sc_trace(mVcdFile, add_ln47_1_fu_422_p2, "add_ln47_1_fu_422_p2");
    sc_trace(mVcdFile, tmp_2_fu_431_p3, "tmp_2_fu_431_p3");
    sc_trace(mVcdFile, sext_ln47_2_fu_439_p1, "sext_ln47_2_fu_439_p1");
    sc_trace(mVcdFile, sext_ln47_1_fu_427_p1, "sext_ln47_1_fu_427_p1");
    sc_trace(mVcdFile, tmp_3_fu_449_p3, "tmp_3_fu_449_p3");
    sc_trace(mVcdFile, tmp_4_fu_461_p3, "tmp_4_fu_461_p3");
    sc_trace(mVcdFile, zext_ln47_3_fu_457_p1, "zext_ln47_3_fu_457_p1");
    sc_trace(mVcdFile, zext_ln47_4_fu_469_p1, "zext_ln47_4_fu_469_p1");
    sc_trace(mVcdFile, sub_ln47_2_fu_473_p2, "sub_ln47_2_fu_473_p2");
    sc_trace(mVcdFile, zext_ln51_2_fu_483_p1, "zext_ln51_2_fu_483_p1");
    sc_trace(mVcdFile, add_ln51_1_fu_487_p2, "add_ln51_1_fu_487_p2");
    sc_trace(mVcdFile, zext_ln41_fu_497_p1, "zext_ln41_fu_497_p1");
    sc_trace(mVcdFile, add_ln47_fu_513_p2, "add_ln47_fu_513_p2");
    sc_trace(mVcdFile, zext_ln47_5_fu_519_p1, "zext_ln47_5_fu_519_p1");
    sc_trace(mVcdFile, add_ln47_2_fu_523_p2, "add_ln47_2_fu_523_p2");
    sc_trace(mVcdFile, trunc_ln47_fu_528_p1, "trunc_ln47_fu_528_p1");
    sc_trace(mVcdFile, p_shl6_cast_fu_532_p3, "p_shl6_cast_fu_532_p3");
    sc_trace(mVcdFile, p_shl7_cast_fu_540_p3, "p_shl7_cast_fu_540_p3");
    sc_trace(mVcdFile, zext_ln47_6_fu_554_p1, "zext_ln47_6_fu_554_p1");
    sc_trace(mVcdFile, add_ln47_4_fu_558_p2, "add_ln47_4_fu_558_p2");
    sc_trace(mVcdFile, trunc_ln47_2_fu_567_p1, "trunc_ln47_2_fu_567_p1");
    sc_trace(mVcdFile, p_shl5_cast_fu_571_p3, "p_shl5_cast_fu_571_p3");
    sc_trace(mVcdFile, trunc_ln47_1_fu_563_p1, "trunc_ln47_1_fu_563_p1");
    sc_trace(mVcdFile, zext_ln44_fu_585_p1, "zext_ln44_fu_585_p1");
    sc_trace(mVcdFile, add_ln47_3_fu_601_p2, "add_ln47_3_fu_601_p2");
    sc_trace(mVcdFile, zext_ln47_7_fu_607_p1, "zext_ln47_7_fu_607_p1");
    sc_trace(mVcdFile, add_ln47_5_fu_611_p2, "add_ln47_5_fu_611_p2");
    sc_trace(mVcdFile, zext_ln47_9_fu_621_p1, "zext_ln47_9_fu_621_p1");
    sc_trace(mVcdFile, add_ln47_6_fu_625_p2, "add_ln47_6_fu_625_p2");
    sc_trace(mVcdFile, zext_ln63_1_fu_670_p1, "zext_ln63_1_fu_670_p1");
    sc_trace(mVcdFile, add_ln63_fu_674_p2, "add_ln63_fu_674_p2");
    sc_trace(mVcdFile, zext_ln63_3_fu_696_p1, "zext_ln63_3_fu_696_p1");
    sc_trace(mVcdFile, add_ln63_1_fu_700_p2, "add_ln63_1_fu_700_p2");
    sc_trace(mVcdFile, mul_ln51_fu_710_p0, "mul_ln51_fu_710_p0");
    sc_trace(mVcdFile, mul_ln51_fu_710_p1, "mul_ln51_fu_710_p1");
    sc_trace(mVcdFile, mul_ln63_fu_716_p0, "mul_ln63_fu_716_p0");
    sc_trace(mVcdFile, mul_ln63_fu_716_p1, "mul_ln63_fu_716_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul_ln51_fu_710_p00, "mul_ln51_fu_710_p00");
    sc_trace(mVcdFile, mul_ln63_fu_716_p00, "mul_ln63_fu_716_p00");
#endif

    }
}

conv_2::~conv_2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete layerconv3_0_weight_U;
    delete layerconv3_0_bias_U;
    delete input_after_padding_U;
    delete grp_pad_14_24_0_11_fu_295;
    delete test_hadd_16ns_16eOg_U30;
    delete test_hmul_16ns_16fYi_U31;
    delete test_mul_mul_10nsncg_U32;
    delete test_mul_mul_10nsncg_U33;
}

void conv_2::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void conv_2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln36_fu_394_p2.read()))) {
        convsum_0_reg_191 = ap_const_lv16_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln41_fu_501_p2.read(), ap_const_lv1_1))) {
        convsum_0_reg_191 = convsum_1_reg_204.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln44_fu_589_p2.read(), ap_const_lv1_1))) {
        convsum_1_reg_204 = convsum_2_reg_227.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln39_fu_406_p2.read()))) {
        convsum_1_reg_204 = convsum_0_reg_191.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_501_p2.read()))) {
        convsum_2_reg_227 = convsum_1_reg_204.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        convsum_2_reg_227 = grp_fu_303_p2.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_pad_14_24_0_11_fu_295_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_pad_14_24_0_11_fu_295_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pad_14_24_0_11_fu_295_ap_ready.read())) {
            grp_pad_14_24_0_11_fu_295_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln44_fu_589_p2.read(), ap_const_lv1_1))) {
        i1_0_reg_216 = i1_reg_782.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln39_fu_406_p2.read()))) {
        i1_0_reg_216 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_322_p2.read(), ap_const_lv1_1))) {
        i2_0_reg_250 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(icmp_ln57_fu_658_p2.read(), ap_const_lv1_1))) {
        i2_0_reg_250 = i_2_reg_843.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln34_fu_368_p2.read(), ap_const_lv1_1))) {
        i_0_reg_133 = i_reg_730.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(grp_pad_14_24_0_11_fu_295_ap_done.read(), ap_const_logic_1))) {
        i_0_reg_133 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_501_p2.read()))) {
        j1_0_reg_239 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        j1_0_reg_239 = j1_reg_800.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln36_fu_394_p2.read()))) {
        j_0_reg_180 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln41_fu_501_p2.read(), ap_const_lv1_1))) {
        j_0_reg_180 = j_reg_764.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_322_p2.read(), ap_const_lv1_1))) {
        phi_mul8_reg_261 = ap_const_lv10_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(icmp_ln57_fu_658_p2.read(), ap_const_lv1_1))) {
        phi_mul8_reg_261 = add_ln55_reg_835.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln34_fu_368_p2.read(), ap_const_lv1_1))) {
        phi_mul_reg_144 = add_ln31_reg_722.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(grp_pad_14_24_0_11_fu_295_ap_done.read(), ap_const_logic_1))) {
        phi_mul_reg_144 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
         esl_seteq<1,1,1>(icmp_ln60_fu_684_p2.read(), ap_const_lv1_1))) {
        x3_0_reg_273 = x_2_reg_861.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        x3_0_reg_273 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln36_fu_394_p2.read()))) {
        x_0_reg_156 = x_reg_743.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln31_fu_322_p2.read(), ap_const_lv1_0))) {
        x_0_reg_156 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_658_p2.read()))) {
        y4_0_reg_284 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        y4_0_reg_284 = y_reg_874.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_368_p2.read()))) {
        y_0_reg_168 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln39_fu_406_p2.read(), ap_const_lv1_1))) {
        y_0_reg_168 = y_2_reg_756.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_ln31_reg_722 = add_ln31_fu_316_p2.read();
        i_reg_730 = i_fu_328_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        add_ln55_reg_835 = add_ln55_fu_635_p2.read();
        i_2_reg_843 = i_2_fu_647_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i1_reg_782 = i1_fu_507_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        j1_reg_800 = j1_fu_595_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_reg_764 = j_fu_412_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        layerconv3_0_bias_lo_reg_853 = layerconv3_0_bias_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_368_p2.read()))) {
        mul_ln51_reg_748 = mul_ln51_fu_710_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_658_p2.read()))) {
        mul_ln63_reg_866 = mul_ln63_fu_716_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_fu_684_p2.read()))) {
        output_addr_reg_879 =  (sc_lv<14>) (zext_ln63_4_fu_705_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln39_fu_406_p2.read()))) {
        sext_ln47_3_reg_774 = sext_ln47_3_fu_479_p1.read();
        sub_ln47_1_reg_769 = sub_ln47_1_fu_443_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln31_fu_322_p2.read(), ap_const_lv1_0))) {
        sext_ln47_reg_735 = sext_ln47_fu_364_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_501_p2.read()))) {
        sub_ln47_3_reg_787 = sub_ln47_3_fu_548_p2.read();
        sub_ln47_4_reg_792 = sub_ln47_4_fu_579_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_8_reg_825 = grp_fu_310_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        x_2_reg_861 = x_2_fu_664_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_reg_743 = x_fu_374_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_2_reg_756 = y_2_fu_400_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        y_reg_874 = y_fu_690_p2.read();
    }
}

void conv_2::thread_add_ln31_fu_316_p2() {
    add_ln31_fu_316_p2 = (!phi_mul_reg_144.read().is_01() || !ap_const_lv10_16.is_01())? sc_lv<10>(): (sc_biguint<10>(phi_mul_reg_144.read()) + sc_biguint<10>(ap_const_lv10_16));
}

void conv_2::thread_add_ln47_1_fu_422_p2() {
    add_ln47_1_fu_422_p2 = (!sext_ln47_reg_735.read().is_01() || !zext_ln47_2_fu_418_p1.read().is_01())? sc_lv<11>(): (sc_bigint<11>(sext_ln47_reg_735.read()) + sc_biguint<11>(zext_ln47_2_fu_418_p1.read()));
}

void conv_2::thread_add_ln47_2_fu_523_p2() {
    add_ln47_2_fu_523_p2 = (!zext_ln47_5_fu_519_p1.read().is_01() || !sext_ln47_3_reg_774.read().is_01())? sc_lv<11>(): (sc_biguint<11>(zext_ln47_5_fu_519_p1.read()) + sc_bigint<11>(sext_ln47_3_reg_774.read()));
}

void conv_2::thread_add_ln47_3_fu_601_p2() {
    add_ln47_3_fu_601_p2 = (!zext_ln44_fu_585_p1.read().is_01() || !y_0_reg_168.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln44_fu_585_p1.read()) + sc_biguint<5>(y_0_reg_168.read()));
}

void conv_2::thread_add_ln47_4_fu_558_p2() {
    add_ln47_4_fu_558_p2 = (!zext_ln47_6_fu_554_p1.read().is_01() || !sub_ln47_1_reg_769.read().is_01())? sc_lv<64>(): (sc_biguint<64>(zext_ln47_6_fu_554_p1.read()) + sc_biguint<64>(sub_ln47_1_reg_769.read()));
}

void conv_2::thread_add_ln47_5_fu_611_p2() {
    add_ln47_5_fu_611_p2 = (!sub_ln47_3_reg_787.read().is_01() || !zext_ln47_7_fu_607_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(sub_ln47_3_reg_787.read()) + sc_biguint<14>(zext_ln47_7_fu_607_p1.read()));
}

void conv_2::thread_add_ln47_6_fu_625_p2() {
    add_ln47_6_fu_625_p2 = (!sub_ln47_4_reg_792.read().is_01() || !zext_ln47_9_fu_621_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(sub_ln47_4_reg_792.read()) + sc_biguint<13>(zext_ln47_9_fu_621_p1.read()));
}

void conv_2::thread_add_ln47_fu_513_p2() {
    add_ln47_fu_513_p2 = (!x_0_reg_156.read().is_01() || !zext_ln41_fu_497_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(x_0_reg_156.read()) + sc_biguint<5>(zext_ln41_fu_497_p1.read()));
}

void conv_2::thread_add_ln51_1_fu_487_p2() {
    add_ln51_1_fu_487_p2 = (!mul_ln51_reg_748.read().is_01() || !zext_ln51_2_fu_483_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln51_reg_748.read()) + sc_biguint<14>(zext_ln51_2_fu_483_p1.read()));
}

void conv_2::thread_add_ln51_fu_384_p2() {
    add_ln51_fu_384_p2 = (!phi_mul_reg_144.read().is_01() || !zext_ln51_fu_380_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(phi_mul_reg_144.read()) + sc_biguint<10>(zext_ln51_fu_380_p1.read()));
}

void conv_2::thread_add_ln55_fu_635_p2() {
    add_ln55_fu_635_p2 = (!phi_mul8_reg_261.read().is_01() || !ap_const_lv10_16.is_01())? sc_lv<10>(): (sc_biguint<10>(phi_mul8_reg_261.read()) + sc_biguint<10>(ap_const_lv10_16));
}

void conv_2::thread_add_ln63_1_fu_700_p2() {
    add_ln63_1_fu_700_p2 = (!mul_ln63_reg_866.read().is_01() || !zext_ln63_3_fu_696_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln63_reg_866.read()) + sc_biguint<14>(zext_ln63_3_fu_696_p1.read()));
}

void conv_2::thread_add_ln63_fu_674_p2() {
    add_ln63_fu_674_p2 = (!phi_mul8_reg_261.read().is_01() || !zext_ln63_1_fu_670_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(phi_mul8_reg_261.read()) + sc_biguint<10>(zext_ln63_1_fu_670_p1.read()));
}

void conv_2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv_2::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv_2::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void conv_2::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void conv_2::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void conv_2::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void conv_2::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void conv_2::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void conv_2::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void conv_2::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void conv_2::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv_2::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv_2::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv_2::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv_2::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv_2::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv_2::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv_2::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv_2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(icmp_ln55_fu_641_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv_2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv_2::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_641_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv_2::thread_grp_fu_303_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_303_p0 = output_r_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_303_p0 = convsum_2_reg_227.read();
    } else {
        grp_fu_303_p0 = "XXXXXXXXXXXXXXXX";
    }
}

void conv_2::thread_grp_fu_303_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_303_p1 = layerconv3_0_bias_lo_reg_853.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_303_p1 = tmp_8_reg_825.read();
    } else {
        grp_fu_303_p1 = "XXXXXXXXXXXXXXXX";
    }
}

void conv_2::thread_grp_pad_14_24_0_11_fu_295_ap_start() {
    grp_pad_14_24_0_11_fu_295_ap_start = grp_pad_14_24_0_11_fu_295_ap_start_reg.read();
}

void conv_2::thread_i1_fu_507_p2() {
    i1_fu_507_p2 = (!i1_0_reg_216.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_0_reg_216.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_2::thread_i_2_fu_647_p2() {
    i_2_fu_647_p2 = (!i2_0_reg_250.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i2_0_reg_250.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv_2::thread_i_fu_328_p2() {
    i_fu_328_p2 = (!i_0_reg_133.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_reg_133.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv_2::thread_icmp_ln31_fu_322_p2() {
    icmp_ln31_fu_322_p2 = (!i_0_reg_133.read().is_01() || !ap_const_lv5_18.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_133.read() == ap_const_lv5_18);
}

void conv_2::thread_icmp_ln34_fu_368_p2() {
    icmp_ln34_fu_368_p2 = (!x_0_reg_156.read().is_01() || !ap_const_lv5_16.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_156.read() == ap_const_lv5_16);
}

void conv_2::thread_icmp_ln36_fu_394_p2() {
    icmp_ln36_fu_394_p2 = (!y_0_reg_168.read().is_01() || !ap_const_lv5_16.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_168.read() == ap_const_lv5_16);
}

void conv_2::thread_icmp_ln39_fu_406_p2() {
    icmp_ln39_fu_406_p2 = (!j_0_reg_180.read().is_01() || !ap_const_lv4_E.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_180.read() == ap_const_lv4_E);
}

void conv_2::thread_icmp_ln41_fu_501_p2() {
    icmp_ln41_fu_501_p2 = (!i1_0_reg_216.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_216.read() == ap_const_lv2_3);
}

void conv_2::thread_icmp_ln44_fu_589_p2() {
    icmp_ln44_fu_589_p2 = (!j1_0_reg_239.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j1_0_reg_239.read() == ap_const_lv2_3);
}

void conv_2::thread_icmp_ln55_fu_641_p2() {
    icmp_ln55_fu_641_p2 = (!i2_0_reg_250.read().is_01() || !ap_const_lv5_18.is_01())? sc_lv<1>(): sc_lv<1>(i2_0_reg_250.read() == ap_const_lv5_18);
}

void conv_2::thread_icmp_ln57_fu_658_p2() {
    icmp_ln57_fu_658_p2 = (!x3_0_reg_273.read().is_01() || !ap_const_lv5_16.is_01())? sc_lv<1>(): sc_lv<1>(x3_0_reg_273.read() == ap_const_lv5_16);
}

void conv_2::thread_icmp_ln60_fu_684_p2() {
    icmp_ln60_fu_684_p2 = (!y4_0_reg_284.read().is_01() || !ap_const_lv5_16.is_01())? sc_lv<1>(): sc_lv<1>(y4_0_reg_284.read() == ap_const_lv5_16);
}

void conv_2::thread_input_after_padding_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_after_padding_address0 =  (sc_lv<13>) (zext_ln47_8_fu_616_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_after_padding_address0 = grp_pad_14_24_0_11_fu_295_output_r_address0.read();
    } else {
        input_after_padding_address0 =  (sc_lv<13>) ("XXXXXXXXXXXXX");
    }
}

void conv_2::thread_input_after_padding_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_after_padding_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_after_padding_ce0 = grp_pad_14_24_0_11_fu_295_output_r_ce0.read();
    } else {
        input_after_padding_ce0 = ap_const_logic_0;
    }
}

void conv_2::thread_input_after_padding_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_after_padding_we0 = grp_pad_14_24_0_11_fu_295_output_r_we0.read();
    } else {
        input_after_padding_we0 = ap_const_logic_0;
    }
}

void conv_2::thread_input_r_address0() {
    input_r_address0 = grp_pad_14_24_0_11_fu_295_input_r_address0.read();
}

void conv_2::thread_input_r_ce0() {
    input_r_ce0 = grp_pad_14_24_0_11_fu_295_input_r_ce0.read();
}

void conv_2::thread_j1_fu_595_p2() {
    j1_fu_595_p2 = (!j1_0_reg_239.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j1_0_reg_239.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_2::thread_j_fu_412_p2() {
    j_fu_412_p2 = (!j_0_reg_180.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j_0_reg_180.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_2::thread_layerconv3_0_bias_address0() {
    layerconv3_0_bias_address0 =  (sc_lv<5>) (zext_ln63_fu_653_p1.read());
}

void conv_2::thread_layerconv3_0_bias_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        layerconv3_0_bias_ce0 = ap_const_logic_1;
    } else {
        layerconv3_0_bias_ce0 = ap_const_logic_0;
    }
}

void conv_2::thread_layerconv3_0_weight_address0() {
    layerconv3_0_weight_address0 =  (sc_lv<12>) (zext_ln47_10_fu_630_p1.read());
}

void conv_2::thread_layerconv3_0_weight_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        layerconv3_0_weight_ce0 = ap_const_logic_1;
    } else {
        layerconv3_0_weight_ce0 = ap_const_logic_0;
    }
}

void conv_2::thread_mul_ln51_fu_710_p0() {
    mul_ln51_fu_710_p0 =  (sc_lv<10>) (mul_ln51_fu_710_p00.read());
}

void conv_2::thread_mul_ln51_fu_710_p00() {
    mul_ln51_fu_710_p00 = esl_zext<14,10>(add_ln51_fu_384_p2.read());
}

void conv_2::thread_mul_ln51_fu_710_p1() {
    mul_ln51_fu_710_p1 =  (sc_lv<6>) (ap_const_lv14_16);
}

void conv_2::thread_mul_ln63_fu_716_p0() {
    mul_ln63_fu_716_p0 =  (sc_lv<10>) (mul_ln63_fu_716_p00.read());
}

void conv_2::thread_mul_ln63_fu_716_p00() {
    mul_ln63_fu_716_p00 = esl_zext<14,10>(add_ln63_fu_674_p2.read());
}

void conv_2::thread_mul_ln63_fu_716_p1() {
    mul_ln63_fu_716_p1 =  (sc_lv<6>) (ap_const_lv14_16);
}

void conv_2::thread_output_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_r_address0 = output_addr_reg_879.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        output_r_address0 =  (sc_lv<14>) (zext_ln63_4_fu_705_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_address0 =  (sc_lv<14>) (zext_ln51_3_fu_492_p1.read());
    } else {
        output_r_address0 =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void conv_2::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv_2::thread_output_r_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_r_d0 = grp_fu_303_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_d0 = convsum_0_reg_191.read();
    } else {
        output_r_d0 = "XXXXXXXXXXXXXXXX";
    }
}

void conv_2::thread_output_r_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(icmp_ln39_fu_406_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv_2::thread_p_shl5_cast_fu_571_p3() {
    p_shl5_cast_fu_571_p3 = esl_concat<11,2>(trunc_ln47_2_fu_567_p1.read(), ap_const_lv2_0);
}

void conv_2::thread_p_shl6_cast_fu_532_p3() {
    p_shl6_cast_fu_532_p3 = esl_concat<9,5>(trunc_ln47_fu_528_p1.read(), ap_const_lv5_0);
}

void conv_2::thread_p_shl7_cast_fu_540_p3() {
    p_shl7_cast_fu_540_p3 = esl_concat<11,3>(add_ln47_2_fu_523_p2.read(), ap_const_lv3_0);
}

void conv_2::thread_sext_ln47_1_fu_427_p1() {
    sext_ln47_1_fu_427_p1 = esl_sext<64,11>(add_ln47_1_fu_422_p2.read());
}

void conv_2::thread_sext_ln47_2_fu_439_p1() {
    sext_ln47_2_fu_439_p1 = esl_sext<64,13>(tmp_2_fu_431_p3.read());
}

void conv_2::thread_sext_ln47_3_fu_479_p1() {
    sext_ln47_3_fu_479_p1 = esl_sext<11,10>(sub_ln47_2_fu_473_p2.read());
}

void conv_2::thread_sext_ln47_fu_364_p1() {
    sext_ln47_fu_364_p1 = esl_sext<11,10>(sub_ln47_fu_358_p2.read());
}

void conv_2::thread_sub_ln47_1_fu_443_p2() {
    sub_ln47_1_fu_443_p2 = (!sext_ln47_2_fu_439_p1.read().is_01() || !sext_ln47_1_fu_427_p1.read().is_01())? sc_lv<64>(): (sc_bigint<64>(sext_ln47_2_fu_439_p1.read()) - sc_bigint<64>(sext_ln47_1_fu_427_p1.read()));
}

void conv_2::thread_sub_ln47_2_fu_473_p2() {
    sub_ln47_2_fu_473_p2 = (!zext_ln47_3_fu_457_p1.read().is_01() || !zext_ln47_4_fu_469_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln47_3_fu_457_p1.read()) - sc_biguint<10>(zext_ln47_4_fu_469_p1.read()));
}

void conv_2::thread_sub_ln47_3_fu_548_p2() {
    sub_ln47_3_fu_548_p2 = (!p_shl6_cast_fu_532_p3.read().is_01() || !p_shl7_cast_fu_540_p3.read().is_01())? sc_lv<14>(): (sc_biguint<14>(p_shl6_cast_fu_532_p3.read()) - sc_biguint<14>(p_shl7_cast_fu_540_p3.read()));
}

void conv_2::thread_sub_ln47_4_fu_579_p2() {
    sub_ln47_4_fu_579_p2 = (!p_shl5_cast_fu_571_p3.read().is_01() || !trunc_ln47_1_fu_563_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl5_cast_fu_571_p3.read()) - sc_biguint<13>(trunc_ln47_1_fu_563_p1.read()));
}

void conv_2::thread_sub_ln47_fu_358_p2() {
    sub_ln47_fu_358_p2 = (!zext_ln47_fu_342_p1.read().is_01() || !zext_ln47_1_fu_354_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln47_fu_342_p1.read()) - sc_biguint<10>(zext_ln47_1_fu_354_p1.read()));
}

void conv_2::thread_tmp_1_fu_346_p3() {
    tmp_1_fu_346_p3 = esl_concat<5,1>(i_0_reg_133.read(), ap_const_lv1_0);
}

void conv_2::thread_tmp_2_fu_431_p3() {
    tmp_2_fu_431_p3 = esl_concat<11,2>(add_ln47_1_fu_422_p2.read(), ap_const_lv2_0);
}

void conv_2::thread_tmp_3_fu_449_p3() {
    tmp_3_fu_449_p3 = esl_concat<4,5>(j_0_reg_180.read(), ap_const_lv5_0);
}

void conv_2::thread_tmp_4_fu_461_p3() {
    tmp_4_fu_461_p3 = esl_concat<4,3>(j_0_reg_180.read(), ap_const_lv3_0);
}

void conv_2::thread_tmp_s_fu_334_p3() {
    tmp_s_fu_334_p3 = esl_concat<5,4>(i_0_reg_133.read(), ap_const_lv4_0);
}

void conv_2::thread_trunc_ln47_1_fu_563_p1() {
    trunc_ln47_1_fu_563_p1 = add_ln47_4_fu_558_p2.read().range(13-1, 0);
}

void conv_2::thread_trunc_ln47_2_fu_567_p1() {
    trunc_ln47_2_fu_567_p1 = add_ln47_4_fu_558_p2.read().range(11-1, 0);
}

void conv_2::thread_trunc_ln47_fu_528_p1() {
    trunc_ln47_fu_528_p1 = add_ln47_2_fu_523_p2.read().range(9-1, 0);
}

void conv_2::thread_x_2_fu_664_p2() {
    x_2_fu_664_p2 = (!x3_0_reg_273.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(x3_0_reg_273.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv_2::thread_x_fu_374_p2() {
    x_fu_374_p2 = (!x_0_reg_156.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(x_0_reg_156.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv_2::thread_y_2_fu_400_p2() {
    y_2_fu_400_p2 = (!y_0_reg_168.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(y_0_reg_168.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv_2::thread_y_fu_690_p2() {
    y_fu_690_p2 = (!y4_0_reg_284.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(y4_0_reg_284.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv_2::thread_zext_ln41_fu_497_p1() {
    zext_ln41_fu_497_p1 = esl_zext<5,2>(i1_0_reg_216.read());
}

void conv_2::thread_zext_ln44_fu_585_p1() {
    zext_ln44_fu_585_p1 = esl_zext<5,2>(j1_0_reg_239.read());
}

void conv_2::thread_zext_ln47_10_fu_630_p1() {
    zext_ln47_10_fu_630_p1 = esl_zext<64,13>(add_ln47_6_fu_625_p2.read());
}

void conv_2::thread_zext_ln47_1_fu_354_p1() {
    zext_ln47_1_fu_354_p1 = esl_zext<10,6>(tmp_1_fu_346_p3.read());
}

void conv_2::thread_zext_ln47_2_fu_418_p1() {
    zext_ln47_2_fu_418_p1 = esl_zext<11,4>(j_0_reg_180.read());
}

void conv_2::thread_zext_ln47_3_fu_457_p1() {
    zext_ln47_3_fu_457_p1 = esl_zext<10,9>(tmp_3_fu_449_p3.read());
}

void conv_2::thread_zext_ln47_4_fu_469_p1() {
    zext_ln47_4_fu_469_p1 = esl_zext<10,7>(tmp_4_fu_461_p3.read());
}

void conv_2::thread_zext_ln47_5_fu_519_p1() {
    zext_ln47_5_fu_519_p1 = esl_zext<11,5>(add_ln47_fu_513_p2.read());
}

void conv_2::thread_zext_ln47_6_fu_554_p1() {
    zext_ln47_6_fu_554_p1 = esl_zext<64,2>(i1_0_reg_216.read());
}

void conv_2::thread_zext_ln47_7_fu_607_p1() {
    zext_ln47_7_fu_607_p1 = esl_zext<14,5>(add_ln47_3_fu_601_p2.read());
}

void conv_2::thread_zext_ln47_8_fu_616_p1() {
    zext_ln47_8_fu_616_p1 = esl_zext<64,14>(add_ln47_5_fu_611_p2.read());
}

void conv_2::thread_zext_ln47_9_fu_621_p1() {
    zext_ln47_9_fu_621_p1 = esl_zext<13,2>(j1_0_reg_239.read());
}

void conv_2::thread_zext_ln47_fu_342_p1() {
    zext_ln47_fu_342_p1 = esl_zext<10,9>(tmp_s_fu_334_p3.read());
}

void conv_2::thread_zext_ln51_2_fu_483_p1() {
    zext_ln51_2_fu_483_p1 = esl_zext<14,5>(y_0_reg_168.read());
}

void conv_2::thread_zext_ln51_3_fu_492_p1() {
    zext_ln51_3_fu_492_p1 = esl_zext<64,14>(add_ln51_1_fu_487_p2.read());
}

void conv_2::thread_zext_ln51_fu_380_p1() {
    zext_ln51_fu_380_p1 = esl_zext<10,5>(x_0_reg_156.read());
}

void conv_2::thread_zext_ln63_1_fu_670_p1() {
    zext_ln63_1_fu_670_p1 = esl_zext<10,5>(x3_0_reg_273.read());
}

void conv_2::thread_zext_ln63_3_fu_696_p1() {
    zext_ln63_3_fu_696_p1 = esl_zext<14,5>(y4_0_reg_284.read());
}

void conv_2::thread_zext_ln63_4_fu_705_p1() {
    zext_ln63_4_fu_705_p1 = esl_zext<64,14>(add_ln63_1_fu_700_p2.read());
}

void conv_2::thread_zext_ln63_fu_653_p1() {
    zext_ln63_fu_653_p1 = esl_zext<64,5>(i2_0_reg_250.read());
}

void conv_2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_pad_14_24_0_11_fu_295_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln31_fu_322_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln34_fu_368_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln36_fu_394_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln39_fu_406_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln41_fu_501_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln44_fu_589_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(icmp_ln55_fu_641_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(icmp_ln57_fu_658_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(icmp_ln60_fu_684_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

