// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<18> conv_1::ap_ST_fsm_state1 = "1";
const sc_lv<18> conv_1::ap_ST_fsm_state2 = "10";
const sc_lv<18> conv_1::ap_ST_fsm_state3 = "100";
const sc_lv<18> conv_1::ap_ST_fsm_state4 = "1000";
const sc_lv<18> conv_1::ap_ST_fsm_state5 = "10000";
const sc_lv<18> conv_1::ap_ST_fsm_state6 = "100000";
const sc_lv<18> conv_1::ap_ST_fsm_state7 = "1000000";
const sc_lv<18> conv_1::ap_ST_fsm_state8 = "10000000";
const sc_lv<18> conv_1::ap_ST_fsm_state9 = "100000000";
const sc_lv<18> conv_1::ap_ST_fsm_state10 = "1000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state11 = "10000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state12 = "100000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<32> conv_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv_1::ap_const_lv32_2 = "10";
const sc_lv<1> conv_1::ap_const_lv1_0 = "0";
const sc_lv<32> conv_1::ap_const_lv32_3 = "11";
const sc_lv<32> conv_1::ap_const_lv32_4 = "100";
const sc_lv<32> conv_1::ap_const_lv32_5 = "101";
const sc_lv<32> conv_1::ap_const_lv32_6 = "110";
const sc_lv<32> conv_1::ap_const_lv32_7 = "111";
const sc_lv<32> conv_1::ap_const_lv32_8 = "1000";
const sc_lv<32> conv_1::ap_const_lv32_9 = "1001";
const sc_lv<32> conv_1::ap_const_lv32_B = "1011";
const sc_lv<32> conv_1::ap_const_lv32_C = "1100";
const sc_lv<32> conv_1::ap_const_lv32_D = "1101";
const sc_lv<32> conv_1::ap_const_lv32_E = "1110";
const sc_lv<32> conv_1::ap_const_lv32_F = "1111";
const sc_lv<32> conv_1::ap_const_lv32_10 = "10000";
const sc_lv<4> conv_1::ap_const_lv4_0 = "0000";
const sc_lv<32> conv_1::ap_const_lv32_1 = "1";
const sc_lv<1> conv_1::ap_const_lv1_1 = "1";
const sc_lv<9> conv_1::ap_const_lv9_0 = "000000000";
const sc_lv<6> conv_1::ap_const_lv6_0 = "000000";
const sc_lv<2> conv_1::ap_const_lv2_0 = "00";
const sc_lv<16> conv_1::ap_const_lv16_0 = "0000000000000000";
const sc_lv<8> conv_1::ap_const_lv8_0 = "00000000";
const sc_lv<32> conv_1::ap_const_lv32_11 = "10001";
const sc_lv<32> conv_1::ap_const_lv32_A = "1010";
const sc_lv<9> conv_1::ap_const_lv9_31 = "110001";
const sc_lv<4> conv_1::ap_const_lv4_8 = "1000";
const sc_lv<4> conv_1::ap_const_lv4_1 = "1";
const sc_lv<6> conv_1::ap_const_lv6_31 = "110001";
const sc_lv<6> conv_1::ap_const_lv6_1 = "1";
const sc_lv<15> conv_1::ap_const_lv15_31 = "110001";
const sc_lv<8> conv_1::ap_const_lv8_33 = "110011";
const sc_lv<2> conv_1::ap_const_lv2_3 = "11";
const sc_lv<2> conv_1::ap_const_lv2_1 = "1";
const sc_lv<14> conv_1::ap_const_lv14_33 = "110011";
const bool conv_1::ap_const_boolean_1 = true;

conv_1::conv_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    layerconv1_0_weight_U = new conv_1_layerconv1bkb("layerconv1_0_weight_U");
    layerconv1_0_weight_U->clk(ap_clk);
    layerconv1_0_weight_U->reset(ap_rst);
    layerconv1_0_weight_U->address0(layerconv1_0_weight_address0);
    layerconv1_0_weight_U->ce0(layerconv1_0_weight_ce0);
    layerconv1_0_weight_U->q0(layerconv1_0_weight_q0);
    layerconv1_0_bias_U = new conv_1_layerconv1cud("layerconv1_0_bias_U");
    layerconv1_0_bias_U->clk(ap_clk);
    layerconv1_0_bias_U->reset(ap_rst);
    layerconv1_0_bias_U->address0(layerconv1_0_bias_address0);
    layerconv1_0_bias_U->ce0(layerconv1_0_bias_ce0);
    layerconv1_0_bias_U->q0(layerconv1_0_bias_q0);
    input_after_padding_U = new conv_1_input_aftedEe("input_after_padding_U");
    input_after_padding_U->clk(ap_clk);
    input_after_padding_U->reset(ap_rst);
    input_after_padding_U->address0(input_after_padding_address0);
    input_after_padding_U->ce0(input_after_padding_ce0);
    input_after_padding_U->we0(input_after_padding_we0);
    input_after_padding_U->d0(grp_pad_3_51_0_9_fu_297_output_r_d0);
    input_after_padding_U->q0(input_after_padding_q0);
    grp_pad_3_51_0_9_fu_297 = new pad_3_51_0_9("grp_pad_3_51_0_9_fu_297");
    grp_pad_3_51_0_9_fu_297->ap_clk(ap_clk);
    grp_pad_3_51_0_9_fu_297->ap_rst(ap_rst);
    grp_pad_3_51_0_9_fu_297->ap_start(grp_pad_3_51_0_9_fu_297_ap_start);
    grp_pad_3_51_0_9_fu_297->ap_done(grp_pad_3_51_0_9_fu_297_ap_done);
    grp_pad_3_51_0_9_fu_297->ap_idle(grp_pad_3_51_0_9_fu_297_ap_idle);
    grp_pad_3_51_0_9_fu_297->ap_ready(grp_pad_3_51_0_9_fu_297_ap_ready);
    grp_pad_3_51_0_9_fu_297->input_r_address0(grp_pad_3_51_0_9_fu_297_input_r_address0);
    grp_pad_3_51_0_9_fu_297->input_r_ce0(grp_pad_3_51_0_9_fu_297_input_r_ce0);
    grp_pad_3_51_0_9_fu_297->input_r_q0(input_r_q0);
    grp_pad_3_51_0_9_fu_297->output_r_address0(grp_pad_3_51_0_9_fu_297_output_r_address0);
    grp_pad_3_51_0_9_fu_297->output_r_ce0(grp_pad_3_51_0_9_fu_297_output_r_ce0);
    grp_pad_3_51_0_9_fu_297->output_r_we0(grp_pad_3_51_0_9_fu_297_output_r_we0);
    grp_pad_3_51_0_9_fu_297->output_r_d0(grp_pad_3_51_0_9_fu_297_output_r_d0);
    test_hadd_16ns_16eOg_U3 = new test_hadd_16ns_16eOg<1,2,16,16,16>("test_hadd_16ns_16eOg_U3");
    test_hadd_16ns_16eOg_U3->clk(ap_clk);
    test_hadd_16ns_16eOg_U3->reset(ap_rst);
    test_hadd_16ns_16eOg_U3->din0(grp_fu_305_p0);
    test_hadd_16ns_16eOg_U3->din1(grp_fu_305_p1);
    test_hadd_16ns_16eOg_U3->ce(ap_var_for_const0);
    test_hadd_16ns_16eOg_U3->dout(grp_fu_305_p2);
    test_hmul_16ns_16fYi_U4 = new test_hmul_16ns_16fYi<1,2,16,16,16>("test_hmul_16ns_16fYi_U4");
    test_hmul_16ns_16fYi_U4->clk(ap_clk);
    test_hmul_16ns_16fYi_U4->reset(ap_rst);
    test_hmul_16ns_16fYi_U4->din0(input_after_padding_q0);
    test_hmul_16ns_16fYi_U4->din1(layerconv1_0_weight_q0);
    test_hmul_16ns_16fYi_U4->ce(ap_var_for_const0);
    test_hmul_16ns_16fYi_U4->dout(grp_fu_312_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln31_fu_318_p2);
    sensitive << ( phi_mul3_reg_134 );

    SC_METHOD(thread_add_ln39_fu_406_p2);
    sensitive << ( phi_mul_reg_194 );

    SC_METHOD(thread_add_ln47_10_fu_568_p2);
    sensitive << ( mul_ln47_reg_738 );
    sensitive << ( zext_ln47_15_fu_564_p1 );

    SC_METHOD(thread_add_ln47_11_fu_582_p2);
    sensitive << ( sub_ln47_6_reg_743 );
    sensitive << ( zext_ln47_17_fu_578_p1 );

    SC_METHOD(thread_add_ln47_2_fu_558_p2);
    sensitive << ( y_0_reg_158 );
    sensitive << ( zext_ln44_fu_542_p1 );

    SC_METHOD(thread_add_ln47_7_fu_428_p2);
    sensitive << ( sext_ln47_reg_686 );
    sensitive << ( zext_ln47_12_fu_424_p1 );

    SC_METHOD(thread_add_ln47_8_fu_495_p2);
    sensitive << ( phi_mul_reg_194 );
    sensitive << ( zext_ln47_13_fu_491_p1 );

    SC_METHOD(thread_add_ln47_9_fu_515_p2);
    sensitive << ( sub_ln47_5_reg_725 );
    sensitive << ( zext_ln47_8_fu_511_p1 );

    SC_METHOD(thread_add_ln47_fu_485_p2);
    sensitive << ( x_0_reg_146 );
    sensitive << ( zext_ln41_fu_469_p1 );

    SC_METHOD(thread_add_ln51_2_fu_459_p2);
    sensitive << ( mul_ln51_reg_699 );
    sensitive << ( zext_ln51_5_fu_455_p1 );

    SC_METHOD(thread_add_ln51_fu_378_p2);
    sensitive << ( phi_mul3_reg_134 );
    sensitive << ( zext_ln51_fu_374_p1 );

    SC_METHOD(thread_add_ln55_fu_592_p2);
    sensitive << ( phi_mul5_reg_263 );

    SC_METHOD(thread_add_ln63_2_fu_663_p2);
    sensitive << ( mul_ln63_reg_817 );
    sensitive << ( zext_ln63_7_fu_659_p1 );

    SC_METHOD(thread_add_ln63_fu_631_p2);
    sensitive << ( phi_mul5_reg_263 );
    sensitive << ( zext_ln63_5_fu_627_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln55_fu_598_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln55_fu_598_p2 );

    SC_METHOD(thread_grp_fu_305_p0);
    sensitive << ( output_r_q0 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( convsum_2_reg_229 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_grp_fu_305_p1);
    sensitive << ( tmp_6_reg_776 );
    sensitive << ( layerconv1_0_bias_lo_reg_804 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_grp_pad_3_51_0_9_fu_297_ap_start);
    sensitive << ( grp_pad_3_51_0_9_fu_297_ap_start_reg );

    SC_METHOD(thread_i1_fu_479_p2);
    sensitive << ( i1_0_reg_218 );

    SC_METHOD(thread_i_3_fu_604_p2);
    sensitive << ( i2_0_reg_252 );

    SC_METHOD(thread_i_fu_330_p2);
    sensitive << ( i_0_reg_123 );

    SC_METHOD(thread_icmp_ln31_fu_324_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_0_reg_123 );

    SC_METHOD(thread_icmp_ln34_fu_362_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( x_0_reg_146 );

    SC_METHOD(thread_icmp_ln36_fu_394_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( y_0_reg_158 );

    SC_METHOD(thread_icmp_ln39_fu_412_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j_0_reg_170 );

    SC_METHOD(thread_icmp_ln41_fu_473_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( i1_0_reg_218 );

    SC_METHOD(thread_icmp_ln44_fu_546_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( j1_0_reg_241 );

    SC_METHOD(thread_icmp_ln55_fu_598_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( i2_0_reg_252 );

    SC_METHOD(thread_icmp_ln57_fu_615_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( x3_0_reg_275 );

    SC_METHOD(thread_icmp_ln60_fu_647_p2);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( y4_0_reg_286 );

    SC_METHOD(thread_input_after_padding_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_pad_3_51_0_9_fu_297_output_r_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln47_16_fu_573_p1 );

    SC_METHOD(thread_input_after_padding_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_pad_3_51_0_9_fu_297_output_r_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_after_padding_we0);
    sensitive << ( grp_pad_3_51_0_9_fu_297_output_r_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( grp_pad_3_51_0_9_fu_297_input_r_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( grp_pad_3_51_0_9_fu_297_input_r_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_j1_fu_552_p2);
    sensitive << ( j1_0_reg_241 );

    SC_METHOD(thread_j_fu_418_p2);
    sensitive << ( j_0_reg_170 );

    SC_METHOD(thread_layerconv1_0_bias_address0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( zext_ln63_fu_610_p1 );

    SC_METHOD(thread_layerconv1_0_bias_ce0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_layerconv1_0_weight_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln47_18_fu_587_p1 );

    SC_METHOD(thread_layerconv1_0_weight_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_mul_ln47_fu_505_p1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( mul_ln47_fu_505_p10 );

    SC_METHOD(thread_mul_ln47_fu_505_p10);
    sensitive << ( add_ln47_8_fu_495_p2 );

    SC_METHOD(thread_mul_ln47_fu_505_p2);
    sensitive << ( mul_ln47_fu_505_p1 );

    SC_METHOD(thread_mul_ln51_fu_388_p0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( mul_ln51_fu_388_p00 );

    SC_METHOD(thread_mul_ln51_fu_388_p00);
    sensitive << ( add_ln51_fu_378_p2 );

    SC_METHOD(thread_mul_ln51_fu_388_p2);
    sensitive << ( mul_ln51_fu_388_p0 );

    SC_METHOD(thread_mul_ln63_fu_641_p0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( mul_ln63_fu_641_p00 );

    SC_METHOD(thread_mul_ln63_fu_641_p00);
    sensitive << ( add_ln63_fu_631_p2 );

    SC_METHOD(thread_mul_ln63_fu_641_p2);
    sensitive << ( mul_ln63_fu_641_p0 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( output_addr_reg_830 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( zext_ln51_6_fu_464_p1 );
    sensitive << ( zext_ln63_8_fu_668_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_fu_305_p2 );
    sensitive << ( convsum_0_reg_181 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln39_fu_412_p2 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_p_shl2_cast_fu_528_p3);
    sensitive << ( trunc_ln47_3_fu_524_p1 );

    SC_METHOD(thread_sext_ln47_4_fu_433_p1);
    sensitive << ( add_ln47_7_fu_428_p2 );

    SC_METHOD(thread_sext_ln47_5_fu_445_p1);
    sensitive << ( tmp_3_fu_437_p3 );

    SC_METHOD(thread_sext_ln47_fu_358_p1);
    sensitive << ( sub_ln47_fu_352_p2 );

    SC_METHOD(thread_sub_ln47_5_fu_449_p2);
    sensitive << ( sext_ln47_5_fu_445_p1 );
    sensitive << ( sext_ln47_4_fu_433_p1 );

    SC_METHOD(thread_sub_ln47_6_fu_536_p2);
    sensitive << ( p_shl2_cast_fu_528_p3 );
    sensitive << ( trunc_ln47_fu_520_p1 );

    SC_METHOD(thread_sub_ln47_fu_352_p2);
    sensitive << ( zext_ln47_11_fu_348_p1 );
    sensitive << ( zext_ln47_fu_336_p1 );

    SC_METHOD(thread_tmp_3_fu_437_p3);
    sensitive << ( add_ln47_7_fu_428_p2 );

    SC_METHOD(thread_tmp_s_fu_340_p3);
    sensitive << ( i_0_reg_123 );

    SC_METHOD(thread_trunc_ln47_3_fu_524_p1);
    sensitive << ( add_ln47_9_fu_515_p2 );

    SC_METHOD(thread_trunc_ln47_fu_520_p1);
    sensitive << ( add_ln47_9_fu_515_p2 );

    SC_METHOD(thread_x_3_fu_621_p2);
    sensitive << ( x3_0_reg_275 );

    SC_METHOD(thread_x_fu_368_p2);
    sensitive << ( x_0_reg_146 );

    SC_METHOD(thread_y_3_fu_400_p2);
    sensitive << ( y_0_reg_158 );

    SC_METHOD(thread_y_fu_653_p2);
    sensitive << ( y4_0_reg_286 );

    SC_METHOD(thread_zext_ln41_fu_469_p1);
    sensitive << ( i1_0_reg_218 );

    SC_METHOD(thread_zext_ln44_fu_542_p1);
    sensitive << ( j1_0_reg_241 );

    SC_METHOD(thread_zext_ln47_11_fu_348_p1);
    sensitive << ( tmp_s_fu_340_p3 );

    SC_METHOD(thread_zext_ln47_12_fu_424_p1);
    sensitive << ( j_0_reg_170 );

    SC_METHOD(thread_zext_ln47_13_fu_491_p1);
    sensitive << ( add_ln47_fu_485_p2 );

    SC_METHOD(thread_zext_ln47_15_fu_564_p1);
    sensitive << ( add_ln47_2_fu_558_p2 );

    SC_METHOD(thread_zext_ln47_16_fu_573_p1);
    sensitive << ( add_ln47_10_fu_568_p2 );

    SC_METHOD(thread_zext_ln47_17_fu_578_p1);
    sensitive << ( j1_0_reg_241 );

    SC_METHOD(thread_zext_ln47_18_fu_587_p1);
    sensitive << ( add_ln47_11_fu_582_p2 );

    SC_METHOD(thread_zext_ln47_8_fu_511_p1);
    sensitive << ( i1_0_reg_218 );

    SC_METHOD(thread_zext_ln47_fu_336_p1);
    sensitive << ( i_0_reg_123 );

    SC_METHOD(thread_zext_ln51_5_fu_455_p1);
    sensitive << ( y_0_reg_158 );

    SC_METHOD(thread_zext_ln51_6_fu_464_p1);
    sensitive << ( add_ln51_2_fu_459_p2 );

    SC_METHOD(thread_zext_ln51_fu_374_p1);
    sensitive << ( x_0_reg_146 );

    SC_METHOD(thread_zext_ln63_5_fu_627_p1);
    sensitive << ( x3_0_reg_275 );

    SC_METHOD(thread_zext_ln63_7_fu_659_p1);
    sensitive << ( y4_0_reg_286 );

    SC_METHOD(thread_zext_ln63_8_fu_668_p1);
    sensitive << ( add_ln63_2_fu_663_p2 );

    SC_METHOD(thread_zext_ln63_fu_610_p1);
    sensitive << ( i2_0_reg_252 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln31_fu_324_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln34_fu_362_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln39_fu_412_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln41_fu_473_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln44_fu_546_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln55_fu_598_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( icmp_ln57_fu_615_p2 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( icmp_ln60_fu_647_p2 );
    sensitive << ( grp_pad_3_51_0_9_fu_297_ap_done );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln36_fu_394_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000001";
    grp_pad_3_51_0_9_fu_297_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, output_r_q0, "(port)output_r_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, layerconv1_0_weight_address0, "layerconv1_0_weight_address0");
    sc_trace(mVcdFile, layerconv1_0_weight_ce0, "layerconv1_0_weight_ce0");
    sc_trace(mVcdFile, layerconv1_0_weight_q0, "layerconv1_0_weight_q0");
    sc_trace(mVcdFile, layerconv1_0_bias_address0, "layerconv1_0_bias_address0");
    sc_trace(mVcdFile, layerconv1_0_bias_ce0, "layerconv1_0_bias_ce0");
    sc_trace(mVcdFile, layerconv1_0_bias_q0, "layerconv1_0_bias_q0");
    sc_trace(mVcdFile, add_ln31_fu_318_p2, "add_ln31_fu_318_p2");
    sc_trace(mVcdFile, add_ln31_reg_673, "add_ln31_reg_673");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_fu_330_p2, "i_fu_330_p2");
    sc_trace(mVcdFile, i_reg_681, "i_reg_681");
    sc_trace(mVcdFile, sext_ln47_fu_358_p1, "sext_ln47_fu_358_p1");
    sc_trace(mVcdFile, sext_ln47_reg_686, "sext_ln47_reg_686");
    sc_trace(mVcdFile, icmp_ln31_fu_324_p2, "icmp_ln31_fu_324_p2");
    sc_trace(mVcdFile, x_fu_368_p2, "x_fu_368_p2");
    sc_trace(mVcdFile, x_reg_694, "x_reg_694");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, mul_ln51_fu_388_p2, "mul_ln51_fu_388_p2");
    sc_trace(mVcdFile, mul_ln51_reg_699, "mul_ln51_reg_699");
    sc_trace(mVcdFile, icmp_ln34_fu_362_p2, "icmp_ln34_fu_362_p2");
    sc_trace(mVcdFile, y_3_fu_400_p2, "y_3_fu_400_p2");
    sc_trace(mVcdFile, y_3_reg_707, "y_3_reg_707");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, add_ln39_fu_406_p2, "add_ln39_fu_406_p2");
    sc_trace(mVcdFile, add_ln39_reg_712, "add_ln39_reg_712");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, j_fu_418_p2, "j_fu_418_p2");
    sc_trace(mVcdFile, j_reg_720, "j_reg_720");
    sc_trace(mVcdFile, sub_ln47_5_fu_449_p2, "sub_ln47_5_fu_449_p2");
    sc_trace(mVcdFile, sub_ln47_5_reg_725, "sub_ln47_5_reg_725");
    sc_trace(mVcdFile, icmp_ln39_fu_412_p2, "icmp_ln39_fu_412_p2");
    sc_trace(mVcdFile, i1_fu_479_p2, "i1_fu_479_p2");
    sc_trace(mVcdFile, i1_reg_733, "i1_reg_733");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, mul_ln47_fu_505_p2, "mul_ln47_fu_505_p2");
    sc_trace(mVcdFile, mul_ln47_reg_738, "mul_ln47_reg_738");
    sc_trace(mVcdFile, icmp_ln41_fu_473_p2, "icmp_ln41_fu_473_p2");
    sc_trace(mVcdFile, sub_ln47_6_fu_536_p2, "sub_ln47_6_fu_536_p2");
    sc_trace(mVcdFile, sub_ln47_6_reg_743, "sub_ln47_6_reg_743");
    sc_trace(mVcdFile, j1_fu_552_p2, "j1_fu_552_p2");
    sc_trace(mVcdFile, j1_reg_751, "j1_reg_751");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln44_fu_546_p2, "icmp_ln44_fu_546_p2");
    sc_trace(mVcdFile, input_after_padding_q0, "input_after_padding_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, grp_fu_312_p2, "grp_fu_312_p2");
    sc_trace(mVcdFile, tmp_6_reg_776, "tmp_6_reg_776");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_305_p2, "grp_fu_305_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, add_ln55_fu_592_p2, "add_ln55_fu_592_p2");
    sc_trace(mVcdFile, add_ln55_reg_786, "add_ln55_reg_786");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, i_3_fu_604_p2, "i_3_fu_604_p2");
    sc_trace(mVcdFile, i_3_reg_794, "i_3_reg_794");
    sc_trace(mVcdFile, icmp_ln55_fu_598_p2, "icmp_ln55_fu_598_p2");
    sc_trace(mVcdFile, layerconv1_0_bias_lo_reg_804, "layerconv1_0_bias_lo_reg_804");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, x_3_fu_621_p2, "x_3_fu_621_p2");
    sc_trace(mVcdFile, x_3_reg_812, "x_3_reg_812");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, mul_ln63_fu_641_p2, "mul_ln63_fu_641_p2");
    sc_trace(mVcdFile, mul_ln63_reg_817, "mul_ln63_reg_817");
    sc_trace(mVcdFile, icmp_ln57_fu_615_p2, "icmp_ln57_fu_615_p2");
    sc_trace(mVcdFile, y_fu_653_p2, "y_fu_653_p2");
    sc_trace(mVcdFile, y_reg_825, "y_reg_825");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, output_addr_reg_830, "output_addr_reg_830");
    sc_trace(mVcdFile, icmp_ln60_fu_647_p2, "icmp_ln60_fu_647_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, input_after_padding_address0, "input_after_padding_address0");
    sc_trace(mVcdFile, input_after_padding_ce0, "input_after_padding_ce0");
    sc_trace(mVcdFile, input_after_padding_we0, "input_after_padding_we0");
    sc_trace(mVcdFile, grp_pad_3_51_0_9_fu_297_ap_start, "grp_pad_3_51_0_9_fu_297_ap_start");
    sc_trace(mVcdFile, grp_pad_3_51_0_9_fu_297_ap_done, "grp_pad_3_51_0_9_fu_297_ap_done");
    sc_trace(mVcdFile, grp_pad_3_51_0_9_fu_297_ap_idle, "grp_pad_3_51_0_9_fu_297_ap_idle");
    sc_trace(mVcdFile, grp_pad_3_51_0_9_fu_297_ap_ready, "grp_pad_3_51_0_9_fu_297_ap_ready");
    sc_trace(mVcdFile, grp_pad_3_51_0_9_fu_297_input_r_address0, "grp_pad_3_51_0_9_fu_297_input_r_address0");
    sc_trace(mVcdFile, grp_pad_3_51_0_9_fu_297_input_r_ce0, "grp_pad_3_51_0_9_fu_297_input_r_ce0");
    sc_trace(mVcdFile, grp_pad_3_51_0_9_fu_297_output_r_address0, "grp_pad_3_51_0_9_fu_297_output_r_address0");
    sc_trace(mVcdFile, grp_pad_3_51_0_9_fu_297_output_r_ce0, "grp_pad_3_51_0_9_fu_297_output_r_ce0");
    sc_trace(mVcdFile, grp_pad_3_51_0_9_fu_297_output_r_we0, "grp_pad_3_51_0_9_fu_297_output_r_we0");
    sc_trace(mVcdFile, grp_pad_3_51_0_9_fu_297_output_r_d0, "grp_pad_3_51_0_9_fu_297_output_r_d0");
    sc_trace(mVcdFile, i_0_reg_123, "i_0_reg_123");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, phi_mul3_reg_134, "phi_mul3_reg_134");
    sc_trace(mVcdFile, x_0_reg_146, "x_0_reg_146");
    sc_trace(mVcdFile, icmp_ln36_fu_394_p2, "icmp_ln36_fu_394_p2");
    sc_trace(mVcdFile, y_0_reg_158, "y_0_reg_158");
    sc_trace(mVcdFile, j_0_reg_170, "j_0_reg_170");
    sc_trace(mVcdFile, convsum_0_reg_181, "convsum_0_reg_181");
    sc_trace(mVcdFile, phi_mul_reg_194, "phi_mul_reg_194");
    sc_trace(mVcdFile, convsum_1_reg_206, "convsum_1_reg_206");
    sc_trace(mVcdFile, i1_0_reg_218, "i1_0_reg_218");
    sc_trace(mVcdFile, convsum_2_reg_229, "convsum_2_reg_229");
    sc_trace(mVcdFile, j1_0_reg_241, "j1_0_reg_241");
    sc_trace(mVcdFile, i2_0_reg_252, "i2_0_reg_252");
    sc_trace(mVcdFile, phi_mul5_reg_263, "phi_mul5_reg_263");
    sc_trace(mVcdFile, x3_0_reg_275, "x3_0_reg_275");
    sc_trace(mVcdFile, y4_0_reg_286, "y4_0_reg_286");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, grp_pad_3_51_0_9_fu_297_ap_start_reg, "grp_pad_3_51_0_9_fu_297_ap_start_reg");
    sc_trace(mVcdFile, zext_ln51_6_fu_464_p1, "zext_ln51_6_fu_464_p1");
    sc_trace(mVcdFile, zext_ln47_16_fu_573_p1, "zext_ln47_16_fu_573_p1");
    sc_trace(mVcdFile, zext_ln47_18_fu_587_p1, "zext_ln47_18_fu_587_p1");
    sc_trace(mVcdFile, zext_ln63_fu_610_p1, "zext_ln63_fu_610_p1");
    sc_trace(mVcdFile, zext_ln63_8_fu_668_p1, "zext_ln63_8_fu_668_p1");
    sc_trace(mVcdFile, grp_fu_305_p0, "grp_fu_305_p0");
    sc_trace(mVcdFile, grp_fu_305_p1, "grp_fu_305_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp_s_fu_340_p3, "tmp_s_fu_340_p3");
    sc_trace(mVcdFile, zext_ln47_11_fu_348_p1, "zext_ln47_11_fu_348_p1");
    sc_trace(mVcdFile, zext_ln47_fu_336_p1, "zext_ln47_fu_336_p1");
    sc_trace(mVcdFile, sub_ln47_fu_352_p2, "sub_ln47_fu_352_p2");
    sc_trace(mVcdFile, zext_ln51_fu_374_p1, "zext_ln51_fu_374_p1");
    sc_trace(mVcdFile, add_ln51_fu_378_p2, "add_ln51_fu_378_p2");
    sc_trace(mVcdFile, mul_ln51_fu_388_p0, "mul_ln51_fu_388_p0");
    sc_trace(mVcdFile, zext_ln47_12_fu_424_p1, "zext_ln47_12_fu_424_p1");
    sc_trace(mVcdFile, add_ln47_7_fu_428_p2, "add_ln47_7_fu_428_p2");
    sc_trace(mVcdFile, tmp_3_fu_437_p3, "tmp_3_fu_437_p3");
    sc_trace(mVcdFile, sext_ln47_5_fu_445_p1, "sext_ln47_5_fu_445_p1");
    sc_trace(mVcdFile, sext_ln47_4_fu_433_p1, "sext_ln47_4_fu_433_p1");
    sc_trace(mVcdFile, zext_ln51_5_fu_455_p1, "zext_ln51_5_fu_455_p1");
    sc_trace(mVcdFile, add_ln51_2_fu_459_p2, "add_ln51_2_fu_459_p2");
    sc_trace(mVcdFile, zext_ln41_fu_469_p1, "zext_ln41_fu_469_p1");
    sc_trace(mVcdFile, add_ln47_fu_485_p2, "add_ln47_fu_485_p2");
    sc_trace(mVcdFile, zext_ln47_13_fu_491_p1, "zext_ln47_13_fu_491_p1");
    sc_trace(mVcdFile, add_ln47_8_fu_495_p2, "add_ln47_8_fu_495_p2");
    sc_trace(mVcdFile, mul_ln47_fu_505_p1, "mul_ln47_fu_505_p1");
    sc_trace(mVcdFile, zext_ln47_8_fu_511_p1, "zext_ln47_8_fu_511_p1");
    sc_trace(mVcdFile, add_ln47_9_fu_515_p2, "add_ln47_9_fu_515_p2");
    sc_trace(mVcdFile, trunc_ln47_3_fu_524_p1, "trunc_ln47_3_fu_524_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_528_p3, "p_shl2_cast_fu_528_p3");
    sc_trace(mVcdFile, trunc_ln47_fu_520_p1, "trunc_ln47_fu_520_p1");
    sc_trace(mVcdFile, zext_ln44_fu_542_p1, "zext_ln44_fu_542_p1");
    sc_trace(mVcdFile, add_ln47_2_fu_558_p2, "add_ln47_2_fu_558_p2");
    sc_trace(mVcdFile, zext_ln47_15_fu_564_p1, "zext_ln47_15_fu_564_p1");
    sc_trace(mVcdFile, add_ln47_10_fu_568_p2, "add_ln47_10_fu_568_p2");
    sc_trace(mVcdFile, zext_ln47_17_fu_578_p1, "zext_ln47_17_fu_578_p1");
    sc_trace(mVcdFile, add_ln47_11_fu_582_p2, "add_ln47_11_fu_582_p2");
    sc_trace(mVcdFile, zext_ln63_5_fu_627_p1, "zext_ln63_5_fu_627_p1");
    sc_trace(mVcdFile, add_ln63_fu_631_p2, "add_ln63_fu_631_p2");
    sc_trace(mVcdFile, mul_ln63_fu_641_p0, "mul_ln63_fu_641_p0");
    sc_trace(mVcdFile, zext_ln63_7_fu_659_p1, "zext_ln63_7_fu_659_p1");
    sc_trace(mVcdFile, add_ln63_2_fu_663_p2, "add_ln63_2_fu_663_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul_ln47_fu_505_p10, "mul_ln47_fu_505_p10");
    sc_trace(mVcdFile, mul_ln51_fu_388_p00, "mul_ln51_fu_388_p00");
    sc_trace(mVcdFile, mul_ln63_fu_641_p00, "mul_ln63_fu_641_p00");
#endif

    }
}

conv_1::~conv_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete layerconv1_0_weight_U;
    delete layerconv1_0_bias_U;
    delete input_after_padding_U;
    delete grp_pad_3_51_0_9_fu_297;
    delete test_hadd_16ns_16eOg_U3;
    delete test_hmul_16ns_16fYi_U4;
}

void conv_1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void conv_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln36_fu_394_p2.read()))) {
        convsum_0_reg_181 = ap_const_lv16_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln41_fu_473_p2.read(), ap_const_lv1_1))) {
        convsum_0_reg_181 = convsum_1_reg_206.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln44_fu_546_p2.read(), ap_const_lv1_1))) {
        convsum_1_reg_206 = convsum_2_reg_229.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln39_fu_412_p2.read()))) {
        convsum_1_reg_206 = convsum_0_reg_181.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_473_p2.read()))) {
        convsum_2_reg_229 = convsum_1_reg_206.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        convsum_2_reg_229 = grp_fu_305_p2.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_pad_3_51_0_9_fu_297_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_pad_3_51_0_9_fu_297_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pad_3_51_0_9_fu_297_ap_ready.read())) {
            grp_pad_3_51_0_9_fu_297_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln44_fu_546_p2.read(), ap_const_lv1_1))) {
        i1_0_reg_218 = i1_reg_733.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln39_fu_412_p2.read()))) {
        i1_0_reg_218 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_324_p2.read(), ap_const_lv1_1))) {
        i2_0_reg_252 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(icmp_ln57_fu_615_p2.read(), ap_const_lv1_1))) {
        i2_0_reg_252 = i_3_reg_794.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln34_fu_362_p2.read(), ap_const_lv1_1))) {
        i_0_reg_123 = i_reg_681.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(grp_pad_3_51_0_9_fu_297_ap_done.read(), ap_const_logic_1))) {
        i_0_reg_123 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_473_p2.read()))) {
        j1_0_reg_241 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        j1_0_reg_241 = j1_reg_751.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln36_fu_394_p2.read()))) {
        j_0_reg_170 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln41_fu_473_p2.read(), ap_const_lv1_1))) {
        j_0_reg_170 = j_reg_720.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln34_fu_362_p2.read(), ap_const_lv1_1))) {
        phi_mul3_reg_134 = add_ln31_reg_673.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(grp_pad_3_51_0_9_fu_297_ap_done.read(), ap_const_logic_1))) {
        phi_mul3_reg_134 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_324_p2.read(), ap_const_lv1_1))) {
        phi_mul5_reg_263 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(icmp_ln57_fu_615_p2.read(), ap_const_lv1_1))) {
        phi_mul5_reg_263 = add_ln55_reg_786.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln36_fu_394_p2.read()))) {
        phi_mul_reg_194 = ap_const_lv8_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln41_fu_473_p2.read(), ap_const_lv1_1))) {
        phi_mul_reg_194 = add_ln39_reg_712.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
         esl_seteq<1,1,1>(icmp_ln60_fu_647_p2.read(), ap_const_lv1_1))) {
        x3_0_reg_275 = x_3_reg_812.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        x3_0_reg_275 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln36_fu_394_p2.read()))) {
        x_0_reg_146 = x_reg_694.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln31_fu_324_p2.read(), ap_const_lv1_0))) {
        x_0_reg_146 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_615_p2.read()))) {
        y4_0_reg_286 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        y4_0_reg_286 = y_reg_825.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_362_p2.read()))) {
        y_0_reg_158 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln39_fu_412_p2.read(), ap_const_lv1_1))) {
        y_0_reg_158 = y_3_reg_707.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_ln31_reg_673 = add_ln31_fu_318_p2.read();
        i_reg_681 = i_fu_330_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        add_ln39_reg_712 = add_ln39_fu_406_p2.read();
        j_reg_720 = j_fu_418_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        add_ln55_reg_786 = add_ln55_fu_592_p2.read();
        i_3_reg_794 = i_3_fu_604_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i1_reg_733 = i1_fu_479_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        j1_reg_751 = j1_fu_552_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        layerconv1_0_bias_lo_reg_804 = layerconv1_0_bias_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_473_p2.read()))) {
        mul_ln47_reg_738 = mul_ln47_fu_505_p2.read();
        sub_ln47_6_reg_743 = sub_ln47_6_fu_536_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_362_p2.read()))) {
        mul_ln51_reg_699 = mul_ln51_fu_388_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_615_p2.read()))) {
        mul_ln63_reg_817 = mul_ln63_fu_641_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_fu_647_p2.read()))) {
        output_addr_reg_830 =  (sc_lv<15>) (zext_ln63_8_fu_668_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln31_fu_324_p2.read(), ap_const_lv1_0))) {
        sext_ln47_reg_686 = sext_ln47_fu_358_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln39_fu_412_p2.read()))) {
        sub_ln47_5_reg_725 = sub_ln47_5_fu_449_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_6_reg_776 = grp_fu_312_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        x_3_reg_812 = x_3_fu_621_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_reg_694 = x_fu_368_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_3_reg_707 = y_3_fu_400_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        y_reg_825 = y_fu_653_p2.read();
    }
}

void conv_1::thread_add_ln31_fu_318_p2() {
    add_ln31_fu_318_p2 = (!phi_mul3_reg_134.read().is_01() || !ap_const_lv9_31.is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul3_reg_134.read()) + sc_biguint<9>(ap_const_lv9_31));
}

void conv_1::thread_add_ln39_fu_406_p2() {
    add_ln39_fu_406_p2 = (!phi_mul_reg_194.read().is_01() || !ap_const_lv8_33.is_01())? sc_lv<8>(): (sc_biguint<8>(phi_mul_reg_194.read()) + sc_biguint<8>(ap_const_lv8_33));
}

void conv_1::thread_add_ln47_10_fu_568_p2() {
    add_ln47_10_fu_568_p2 = (!mul_ln47_reg_738.read().is_01() || !zext_ln47_15_fu_564_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln47_reg_738.read()) + sc_biguint<14>(zext_ln47_15_fu_564_p1.read()));
}

void conv_1::thread_add_ln47_11_fu_582_p2() {
    add_ln47_11_fu_582_p2 = (!sub_ln47_6_reg_743.read().is_01() || !zext_ln47_17_fu_578_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(sub_ln47_6_reg_743.read()) + sc_biguint<9>(zext_ln47_17_fu_578_p1.read()));
}

void conv_1::thread_add_ln47_2_fu_558_p2() {
    add_ln47_2_fu_558_p2 = (!zext_ln44_fu_542_p1.read().is_01() || !y_0_reg_158.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln44_fu_542_p1.read()) + sc_biguint<6>(y_0_reg_158.read()));
}

void conv_1::thread_add_ln47_7_fu_428_p2() {
    add_ln47_7_fu_428_p2 = (!sext_ln47_reg_686.read().is_01() || !zext_ln47_12_fu_424_p1.read().is_01())? sc_lv<8>(): (sc_bigint<8>(sext_ln47_reg_686.read()) + sc_biguint<8>(zext_ln47_12_fu_424_p1.read()));
}

void conv_1::thread_add_ln47_8_fu_495_p2() {
    add_ln47_8_fu_495_p2 = (!zext_ln47_13_fu_491_p1.read().is_01() || !phi_mul_reg_194.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln47_13_fu_491_p1.read()) + sc_biguint<8>(phi_mul_reg_194.read()));
}

void conv_1::thread_add_ln47_9_fu_515_p2() {
    add_ln47_9_fu_515_p2 = (!zext_ln47_8_fu_511_p1.read().is_01() || !sub_ln47_5_reg_725.read().is_01())? sc_lv<64>(): (sc_biguint<64>(zext_ln47_8_fu_511_p1.read()) + sc_biguint<64>(sub_ln47_5_reg_725.read()));
}

void conv_1::thread_add_ln47_fu_485_p2() {
    add_ln47_fu_485_p2 = (!x_0_reg_146.read().is_01() || !zext_ln41_fu_469_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(x_0_reg_146.read()) + sc_biguint<6>(zext_ln41_fu_469_p1.read()));
}

void conv_1::thread_add_ln51_2_fu_459_p2() {
    add_ln51_2_fu_459_p2 = (!mul_ln51_reg_699.read().is_01() || !zext_ln51_5_fu_455_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(mul_ln51_reg_699.read()) + sc_biguint<15>(zext_ln51_5_fu_455_p1.read()));
}

void conv_1::thread_add_ln51_fu_378_p2() {
    add_ln51_fu_378_p2 = (!phi_mul3_reg_134.read().is_01() || !zext_ln51_fu_374_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul3_reg_134.read()) + sc_biguint<9>(zext_ln51_fu_374_p1.read()));
}

void conv_1::thread_add_ln55_fu_592_p2() {
    add_ln55_fu_592_p2 = (!phi_mul5_reg_263.read().is_01() || !ap_const_lv9_31.is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul5_reg_263.read()) + sc_biguint<9>(ap_const_lv9_31));
}

void conv_1::thread_add_ln63_2_fu_663_p2() {
    add_ln63_2_fu_663_p2 = (!mul_ln63_reg_817.read().is_01() || !zext_ln63_7_fu_659_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(mul_ln63_reg_817.read()) + sc_biguint<15>(zext_ln63_7_fu_659_p1.read()));
}

void conv_1::thread_add_ln63_fu_631_p2() {
    add_ln63_fu_631_p2 = (!phi_mul5_reg_263.read().is_01() || !zext_ln63_5_fu_627_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul5_reg_263.read()) + sc_biguint<9>(zext_ln63_5_fu_627_p1.read()));
}

void conv_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv_1::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv_1::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void conv_1::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void conv_1::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void conv_1::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void conv_1::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void conv_1::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void conv_1::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void conv_1::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void conv_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv_1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv_1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv_1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv_1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv_1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv_1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv_1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(icmp_ln55_fu_598_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv_1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_598_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv_1::thread_grp_fu_305_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_305_p0 = output_r_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_305_p0 = convsum_2_reg_229.read();
    } else {
        grp_fu_305_p0 = "XXXXXXXXXXXXXXXX";
    }
}

void conv_1::thread_grp_fu_305_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_305_p1 = layerconv1_0_bias_lo_reg_804.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_305_p1 = tmp_6_reg_776.read();
    } else {
        grp_fu_305_p1 = "XXXXXXXXXXXXXXXX";
    }
}

void conv_1::thread_grp_pad_3_51_0_9_fu_297_ap_start() {
    grp_pad_3_51_0_9_fu_297_ap_start = grp_pad_3_51_0_9_fu_297_ap_start_reg.read();
}

void conv_1::thread_i1_fu_479_p2() {
    i1_fu_479_p2 = (!i1_0_reg_218.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_0_reg_218.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_1::thread_i_3_fu_604_p2() {
    i_3_fu_604_p2 = (!i2_0_reg_252.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i2_0_reg_252.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_1::thread_i_fu_330_p2() {
    i_fu_330_p2 = (!i_0_reg_123.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_123.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_1::thread_icmp_ln31_fu_324_p2() {
    icmp_ln31_fu_324_p2 = (!i_0_reg_123.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_123.read() == ap_const_lv4_8);
}

void conv_1::thread_icmp_ln34_fu_362_p2() {
    icmp_ln34_fu_362_p2 = (!x_0_reg_146.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_146.read() == ap_const_lv6_31);
}

void conv_1::thread_icmp_ln36_fu_394_p2() {
    icmp_ln36_fu_394_p2 = (!y_0_reg_158.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_158.read() == ap_const_lv6_31);
}

void conv_1::thread_icmp_ln39_fu_412_p2() {
    icmp_ln39_fu_412_p2 = (!j_0_reg_170.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_170.read() == ap_const_lv2_3);
}

void conv_1::thread_icmp_ln41_fu_473_p2() {
    icmp_ln41_fu_473_p2 = (!i1_0_reg_218.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_218.read() == ap_const_lv2_3);
}

void conv_1::thread_icmp_ln44_fu_546_p2() {
    icmp_ln44_fu_546_p2 = (!j1_0_reg_241.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j1_0_reg_241.read() == ap_const_lv2_3);
}

void conv_1::thread_icmp_ln55_fu_598_p2() {
    icmp_ln55_fu_598_p2 = (!i2_0_reg_252.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i2_0_reg_252.read() == ap_const_lv4_8);
}

void conv_1::thread_icmp_ln57_fu_615_p2() {
    icmp_ln57_fu_615_p2 = (!x3_0_reg_275.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(x3_0_reg_275.read() == ap_const_lv6_31);
}

void conv_1::thread_icmp_ln60_fu_647_p2() {
    icmp_ln60_fu_647_p2 = (!y4_0_reg_286.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(y4_0_reg_286.read() == ap_const_lv6_31);
}

void conv_1::thread_input_after_padding_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_after_padding_address0 =  (sc_lv<13>) (zext_ln47_16_fu_573_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_after_padding_address0 = grp_pad_3_51_0_9_fu_297_output_r_address0.read();
    } else {
        input_after_padding_address0 =  (sc_lv<13>) ("XXXXXXXXXXXXX");
    }
}

void conv_1::thread_input_after_padding_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_after_padding_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_after_padding_ce0 = grp_pad_3_51_0_9_fu_297_output_r_ce0.read();
    } else {
        input_after_padding_ce0 = ap_const_logic_0;
    }
}

void conv_1::thread_input_after_padding_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_after_padding_we0 = grp_pad_3_51_0_9_fu_297_output_r_we0.read();
    } else {
        input_after_padding_we0 = ap_const_logic_0;
    }
}

void conv_1::thread_input_r_address0() {
    input_r_address0 = grp_pad_3_51_0_9_fu_297_input_r_address0.read();
}

void conv_1::thread_input_r_ce0() {
    input_r_ce0 = grp_pad_3_51_0_9_fu_297_input_r_ce0.read();
}

void conv_1::thread_j1_fu_552_p2() {
    j1_fu_552_p2 = (!j1_0_reg_241.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j1_0_reg_241.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_1::thread_j_fu_418_p2() {
    j_fu_418_p2 = (!j_0_reg_170.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j_0_reg_170.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_1::thread_layerconv1_0_bias_address0() {
    layerconv1_0_bias_address0 =  (sc_lv<3>) (zext_ln63_fu_610_p1.read());
}

void conv_1::thread_layerconv1_0_bias_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        layerconv1_0_bias_ce0 = ap_const_logic_1;
    } else {
        layerconv1_0_bias_ce0 = ap_const_logic_0;
    }
}

void conv_1::thread_layerconv1_0_weight_address0() {
    layerconv1_0_weight_address0 =  (sc_lv<8>) (zext_ln47_18_fu_587_p1.read());
}

void conv_1::thread_layerconv1_0_weight_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        layerconv1_0_weight_ce0 = ap_const_logic_1;
    } else {
        layerconv1_0_weight_ce0 = ap_const_logic_0;
    }
}

void conv_1::thread_mul_ln47_fu_505_p1() {
    mul_ln47_fu_505_p1 =  (sc_lv<8>) (mul_ln47_fu_505_p10.read());
}

void conv_1::thread_mul_ln47_fu_505_p10() {
    mul_ln47_fu_505_p10 = esl_zext<14,8>(add_ln47_8_fu_495_p2.read());
}

void conv_1::thread_mul_ln47_fu_505_p2() {
    mul_ln47_fu_505_p2 = (!ap_const_lv14_33.is_01() || !mul_ln47_fu_505_p1.read().is_01())? sc_lv<14>(): sc_biguint<14>(ap_const_lv14_33) * sc_biguint<8>(mul_ln47_fu_505_p1.read());
}

void conv_1::thread_mul_ln51_fu_388_p0() {
    mul_ln51_fu_388_p0 =  (sc_lv<9>) (mul_ln51_fu_388_p00.read());
}

void conv_1::thread_mul_ln51_fu_388_p00() {
    mul_ln51_fu_388_p00 = esl_zext<15,9>(add_ln51_fu_378_p2.read());
}

void conv_1::thread_mul_ln51_fu_388_p2() {
    mul_ln51_fu_388_p2 = (!mul_ln51_fu_388_p0.read().is_01() || !ap_const_lv15_31.is_01())? sc_lv<15>(): sc_biguint<9>(mul_ln51_fu_388_p0.read()) * sc_biguint<15>(ap_const_lv15_31);
}

void conv_1::thread_mul_ln63_fu_641_p0() {
    mul_ln63_fu_641_p0 =  (sc_lv<9>) (mul_ln63_fu_641_p00.read());
}

void conv_1::thread_mul_ln63_fu_641_p00() {
    mul_ln63_fu_641_p00 = esl_zext<15,9>(add_ln63_fu_631_p2.read());
}

void conv_1::thread_mul_ln63_fu_641_p2() {
    mul_ln63_fu_641_p2 = (!mul_ln63_fu_641_p0.read().is_01() || !ap_const_lv15_31.is_01())? sc_lv<15>(): sc_biguint<9>(mul_ln63_fu_641_p0.read()) * sc_biguint<15>(ap_const_lv15_31);
}

void conv_1::thread_output_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_r_address0 = output_addr_reg_830.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        output_r_address0 =  (sc_lv<15>) (zext_ln63_8_fu_668_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_address0 =  (sc_lv<15>) (zext_ln51_6_fu_464_p1.read());
    } else {
        output_r_address0 =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
    }
}

void conv_1::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv_1::thread_output_r_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_r_d0 = grp_fu_305_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_d0 = convsum_0_reg_181.read();
    } else {
        output_r_d0 = "XXXXXXXXXXXXXXXX";
    }
}

void conv_1::thread_output_r_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(icmp_ln39_fu_412_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv_1::thread_p_shl2_cast_fu_528_p3() {
    p_shl2_cast_fu_528_p3 = esl_concat<7,2>(trunc_ln47_3_fu_524_p1.read(), ap_const_lv2_0);
}

void conv_1::thread_sext_ln47_4_fu_433_p1() {
    sext_ln47_4_fu_433_p1 = esl_sext<64,8>(add_ln47_7_fu_428_p2.read());
}

void conv_1::thread_sext_ln47_5_fu_445_p1() {
    sext_ln47_5_fu_445_p1 = esl_sext<64,10>(tmp_3_fu_437_p3.read());
}

void conv_1::thread_sext_ln47_fu_358_p1() {
    sext_ln47_fu_358_p1 = esl_sext<8,7>(sub_ln47_fu_352_p2.read());
}

void conv_1::thread_sub_ln47_5_fu_449_p2() {
    sub_ln47_5_fu_449_p2 = (!sext_ln47_5_fu_445_p1.read().is_01() || !sext_ln47_4_fu_433_p1.read().is_01())? sc_lv<64>(): (sc_bigint<64>(sext_ln47_5_fu_445_p1.read()) - sc_bigint<64>(sext_ln47_4_fu_433_p1.read()));
}

void conv_1::thread_sub_ln47_6_fu_536_p2() {
    sub_ln47_6_fu_536_p2 = (!p_shl2_cast_fu_528_p3.read().is_01() || !trunc_ln47_fu_520_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl2_cast_fu_528_p3.read()) - sc_biguint<9>(trunc_ln47_fu_520_p1.read()));
}

void conv_1::thread_sub_ln47_fu_352_p2() {
    sub_ln47_fu_352_p2 = (!zext_ln47_11_fu_348_p1.read().is_01() || !zext_ln47_fu_336_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln47_11_fu_348_p1.read()) - sc_biguint<7>(zext_ln47_fu_336_p1.read()));
}

void conv_1::thread_tmp_3_fu_437_p3() {
    tmp_3_fu_437_p3 = esl_concat<8,2>(add_ln47_7_fu_428_p2.read(), ap_const_lv2_0);
}

void conv_1::thread_tmp_s_fu_340_p3() {
    tmp_s_fu_340_p3 = esl_concat<4,2>(i_0_reg_123.read(), ap_const_lv2_0);
}

void conv_1::thread_trunc_ln47_3_fu_524_p1() {
    trunc_ln47_3_fu_524_p1 = add_ln47_9_fu_515_p2.read().range(7-1, 0);
}

void conv_1::thread_trunc_ln47_fu_520_p1() {
    trunc_ln47_fu_520_p1 = add_ln47_9_fu_515_p2.read().range(9-1, 0);
}

void conv_1::thread_x_3_fu_621_p2() {
    x_3_fu_621_p2 = (!x3_0_reg_275.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(x3_0_reg_275.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv_1::thread_x_fu_368_p2() {
    x_fu_368_p2 = (!x_0_reg_146.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(x_0_reg_146.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv_1::thread_y_3_fu_400_p2() {
    y_3_fu_400_p2 = (!y_0_reg_158.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(y_0_reg_158.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv_1::thread_y_fu_653_p2() {
    y_fu_653_p2 = (!y4_0_reg_286.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(y4_0_reg_286.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv_1::thread_zext_ln41_fu_469_p1() {
    zext_ln41_fu_469_p1 = esl_zext<6,2>(i1_0_reg_218.read());
}

void conv_1::thread_zext_ln44_fu_542_p1() {
    zext_ln44_fu_542_p1 = esl_zext<6,2>(j1_0_reg_241.read());
}

void conv_1::thread_zext_ln47_11_fu_348_p1() {
    zext_ln47_11_fu_348_p1 = esl_zext<7,6>(tmp_s_fu_340_p3.read());
}

void conv_1::thread_zext_ln47_12_fu_424_p1() {
    zext_ln47_12_fu_424_p1 = esl_zext<8,2>(j_0_reg_170.read());
}

void conv_1::thread_zext_ln47_13_fu_491_p1() {
    zext_ln47_13_fu_491_p1 = esl_zext<8,6>(add_ln47_fu_485_p2.read());
}

void conv_1::thread_zext_ln47_15_fu_564_p1() {
    zext_ln47_15_fu_564_p1 = esl_zext<14,6>(add_ln47_2_fu_558_p2.read());
}

void conv_1::thread_zext_ln47_16_fu_573_p1() {
    zext_ln47_16_fu_573_p1 = esl_zext<64,14>(add_ln47_10_fu_568_p2.read());
}

void conv_1::thread_zext_ln47_17_fu_578_p1() {
    zext_ln47_17_fu_578_p1 = esl_zext<9,2>(j1_0_reg_241.read());
}

void conv_1::thread_zext_ln47_18_fu_587_p1() {
    zext_ln47_18_fu_587_p1 = esl_zext<64,9>(add_ln47_11_fu_582_p2.read());
}

void conv_1::thread_zext_ln47_8_fu_511_p1() {
    zext_ln47_8_fu_511_p1 = esl_zext<64,2>(i1_0_reg_218.read());
}

void conv_1::thread_zext_ln47_fu_336_p1() {
    zext_ln47_fu_336_p1 = esl_zext<7,4>(i_0_reg_123.read());
}

void conv_1::thread_zext_ln51_5_fu_455_p1() {
    zext_ln51_5_fu_455_p1 = esl_zext<15,6>(y_0_reg_158.read());
}

void conv_1::thread_zext_ln51_6_fu_464_p1() {
    zext_ln51_6_fu_464_p1 = esl_zext<64,15>(add_ln51_2_fu_459_p2.read());
}

void conv_1::thread_zext_ln51_fu_374_p1() {
    zext_ln51_fu_374_p1 = esl_zext<9,6>(x_0_reg_146.read());
}

void conv_1::thread_zext_ln63_5_fu_627_p1() {
    zext_ln63_5_fu_627_p1 = esl_zext<9,6>(x3_0_reg_275.read());
}

void conv_1::thread_zext_ln63_7_fu_659_p1() {
    zext_ln63_7_fu_659_p1 = esl_zext<15,6>(y4_0_reg_286.read());
}

void conv_1::thread_zext_ln63_8_fu_668_p1() {
    zext_ln63_8_fu_668_p1 = esl_zext<64,15>(add_ln63_2_fu_663_p2.read());
}

void conv_1::thread_zext_ln63_fu_610_p1() {
    zext_ln63_fu_610_p1 = esl_zext<64,4>(i2_0_reg_252.read());
}

void conv_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_pad_3_51_0_9_fu_297_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln31_fu_324_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln34_fu_362_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln36_fu_394_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln39_fu_412_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln41_fu_473_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln44_fu_546_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(icmp_ln55_fu_598_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(icmp_ln57_fu_615_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(icmp_ln60_fu_647_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

