// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<18> conv_1::ap_ST_fsm_state1 = "1";
const sc_lv<18> conv_1::ap_ST_fsm_state2 = "10";
const sc_lv<18> conv_1::ap_ST_fsm_state3 = "100";
const sc_lv<18> conv_1::ap_ST_fsm_state4 = "1000";
const sc_lv<18> conv_1::ap_ST_fsm_state5 = "10000";
const sc_lv<18> conv_1::ap_ST_fsm_state6 = "100000";
const sc_lv<18> conv_1::ap_ST_fsm_state7 = "1000000";
const sc_lv<18> conv_1::ap_ST_fsm_state8 = "10000000";
const sc_lv<18> conv_1::ap_ST_fsm_state9 = "100000000";
const sc_lv<18> conv_1::ap_ST_fsm_state10 = "1000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state11 = "10000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state12 = "100000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<18> conv_1::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<32> conv_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv_1::ap_const_lv32_2 = "10";
const sc_lv<1> conv_1::ap_const_lv1_0 = "0";
const sc_lv<32> conv_1::ap_const_lv32_3 = "11";
const sc_lv<32> conv_1::ap_const_lv32_4 = "100";
const sc_lv<32> conv_1::ap_const_lv32_5 = "101";
const sc_lv<32> conv_1::ap_const_lv32_6 = "110";
const sc_lv<32> conv_1::ap_const_lv32_7 = "111";
const sc_lv<32> conv_1::ap_const_lv32_8 = "1000";
const sc_lv<32> conv_1::ap_const_lv32_9 = "1001";
const sc_lv<32> conv_1::ap_const_lv32_B = "1011";
const sc_lv<32> conv_1::ap_const_lv32_C = "1100";
const sc_lv<32> conv_1::ap_const_lv32_D = "1101";
const sc_lv<32> conv_1::ap_const_lv32_E = "1110";
const sc_lv<32> conv_1::ap_const_lv32_F = "1111";
const sc_lv<32> conv_1::ap_const_lv32_10 = "10000";
const sc_lv<4> conv_1::ap_const_lv4_0 = "0000";
const sc_lv<32> conv_1::ap_const_lv32_1 = "1";
const sc_lv<1> conv_1::ap_const_lv1_1 = "1";
const sc_lv<6> conv_1::ap_const_lv6_0 = "000000";
const sc_lv<2> conv_1::ap_const_lv2_0 = "00";
const sc_lv<16> conv_1::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> conv_1::ap_const_lv32_11 = "10001";
const sc_lv<32> conv_1::ap_const_lv32_A = "1010";
const sc_lv<4> conv_1::ap_const_lv4_8 = "1000";
const sc_lv<4> conv_1::ap_const_lv4_1 = "1";
const sc_lv<5> conv_1::ap_const_lv5_0 = "00000";
const sc_lv<6> conv_1::ap_const_lv6_20 = "100000";
const sc_lv<6> conv_1::ap_const_lv6_1 = "1";
const sc_lv<2> conv_1::ap_const_lv2_3 = "11";
const sc_lv<2> conv_1::ap_const_lv2_1 = "1";
const bool conv_1::ap_const_boolean_1 = true;

conv_1::conv_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    layerconv1_0_weight_U = new conv_1_layerconv1bkb("layerconv1_0_weight_U");
    layerconv1_0_weight_U->clk(ap_clk);
    layerconv1_0_weight_U->reset(ap_rst);
    layerconv1_0_weight_U->address0(layerconv1_0_weight_address0);
    layerconv1_0_weight_U->ce0(layerconv1_0_weight_ce0);
    layerconv1_0_weight_U->q0(layerconv1_0_weight_q0);
    layerconv1_0_bias_U = new conv_1_layerconv1cud("layerconv1_0_bias_U");
    layerconv1_0_bias_U->clk(ap_clk);
    layerconv1_0_bias_U->reset(ap_rst);
    layerconv1_0_bias_U->address0(layerconv1_0_bias_address0);
    layerconv1_0_bias_U->ce0(layerconv1_0_bias_ce0);
    layerconv1_0_bias_U->q0(layerconv1_0_bias_q0);
    input_after_padding_U = new conv_1_input_aftedEe("input_after_padding_U");
    input_after_padding_U->clk(ap_clk);
    input_after_padding_U->reset(ap_rst);
    input_after_padding_U->address0(input_after_padding_address0);
    input_after_padding_U->ce0(input_after_padding_ce0);
    input_after_padding_U->we0(input_after_padding_we0);
    input_after_padding_U->d0(grp_pad_3_34_0_8_fu_266_output_r_d0);
    input_after_padding_U->q0(input_after_padding_q0);
    grp_pad_3_34_0_8_fu_266 = new pad_3_34_0_8("grp_pad_3_34_0_8_fu_266");
    grp_pad_3_34_0_8_fu_266->ap_clk(ap_clk);
    grp_pad_3_34_0_8_fu_266->ap_rst(ap_rst);
    grp_pad_3_34_0_8_fu_266->ap_start(grp_pad_3_34_0_8_fu_266_ap_start);
    grp_pad_3_34_0_8_fu_266->ap_done(grp_pad_3_34_0_8_fu_266_ap_done);
    grp_pad_3_34_0_8_fu_266->ap_idle(grp_pad_3_34_0_8_fu_266_ap_idle);
    grp_pad_3_34_0_8_fu_266->ap_ready(grp_pad_3_34_0_8_fu_266_ap_ready);
    grp_pad_3_34_0_8_fu_266->input_r_address0(grp_pad_3_34_0_8_fu_266_input_r_address0);
    grp_pad_3_34_0_8_fu_266->input_r_ce0(grp_pad_3_34_0_8_fu_266_input_r_ce0);
    grp_pad_3_34_0_8_fu_266->input_r_q0(input_r_q0);
    grp_pad_3_34_0_8_fu_266->output_r_address0(grp_pad_3_34_0_8_fu_266_output_r_address0);
    grp_pad_3_34_0_8_fu_266->output_r_ce0(grp_pad_3_34_0_8_fu_266_output_r_ce0);
    grp_pad_3_34_0_8_fu_266->output_r_we0(grp_pad_3_34_0_8_fu_266_output_r_we0);
    grp_pad_3_34_0_8_fu_266->output_r_d0(grp_pad_3_34_0_8_fu_266_output_r_d0);
    test_hadd_16ns_16eOg_U3 = new test_hadd_16ns_16eOg<1,2,16,16,16>("test_hadd_16ns_16eOg_U3");
    test_hadd_16ns_16eOg_U3->clk(ap_clk);
    test_hadd_16ns_16eOg_U3->reset(ap_rst);
    test_hadd_16ns_16eOg_U3->din0(grp_fu_274_p0);
    test_hadd_16ns_16eOg_U3->din1(grp_fu_274_p1);
    test_hadd_16ns_16eOg_U3->ce(ap_var_for_const0);
    test_hadd_16ns_16eOg_U3->dout(grp_fu_274_p2);
    test_hmul_16ns_16fYi_U4 = new test_hmul_16ns_16fYi<1,2,16,16,16>("test_hmul_16ns_16fYi_U4");
    test_hmul_16ns_16fYi_U4->clk(ap_clk);
    test_hmul_16ns_16fYi_U4->reset(ap_rst);
    test_hmul_16ns_16fYi_U4->din0(input_after_padding_q0);
    test_hmul_16ns_16fYi_U4->din1(layerconv1_0_weight_q0);
    test_hmul_16ns_16fYi_U4->ce(ap_var_for_const0);
    test_hmul_16ns_16fYi_U4->dout(grp_fu_281_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln47_1_fu_394_p2);
    sensitive << ( sext_ln47_reg_695 );
    sensitive << ( zext_ln47_2_fu_390_p1 );

    SC_METHOD(thread_add_ln47_2_fu_569_p2);
    sensitive << ( y_0_reg_150 );
    sensitive << ( zext_ln44_fu_553_p1 );

    SC_METHOD(thread_add_ln47_3_fu_445_p2);
    sensitive << ( zext_ln47_4_fu_441_p1 );
    sensitive << ( zext_ln47_3_fu_429_p1 );

    SC_METHOD(thread_add_ln47_4_fu_491_p2);
    sensitive << ( add_ln47_3_reg_739 );
    sensitive << ( zext_ln47_5_fu_487_p1 );

    SC_METHOD(thread_add_ln47_5_fu_516_p2);
    sensitive << ( zext_ln47_7_fu_512_p1 );
    sensitive << ( p_shl5_cast_fu_496_p3 );

    SC_METHOD(thread_add_ln47_6_fu_526_p2);
    sensitive << ( sub_ln47_1_reg_734 );
    sensitive << ( zext_ln47_6_fu_522_p1 );

    SC_METHOD(thread_add_ln47_7_fu_579_p2);
    sensitive << ( add_ln47_5_reg_752 );
    sensitive << ( zext_ln47_8_fu_575_p1 );

    SC_METHOD(thread_add_ln47_8_fu_593_p2);
    sensitive << ( sub_ln47_2_reg_757 );
    sensitive << ( zext_ln47_10_fu_589_p1 );

    SC_METHOD(thread_add_ln47_fu_481_p2);
    sensitive << ( x_0_reg_138 );
    sensitive << ( zext_ln41_fu_465_p1 );

    SC_METHOD(thread_add_ln51_1_fu_455_p2);
    sensitive << ( tmp_36_cast_reg_713 );
    sensitive << ( zext_ln51_1_fu_451_p1 );

    SC_METHOD(thread_add_ln51_fu_353_p2);
    sensitive << ( zext_ln34_reg_700 );
    sensitive << ( zext_ln51_fu_349_p1 );

    SC_METHOD(thread_add_ln63_1_fu_677_p2);
    sensitive << ( tmp_38_cast_reg_831 );
    sensitive << ( zext_ln63_3_fu_673_p1 );

    SC_METHOD(thread_add_ln63_fu_648_p2);
    sensitive << ( zext_ln63_1_reg_813 );
    sensitive << ( zext_ln63_2_fu_644_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln55_fu_603_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln55_fu_603_p2 );

    SC_METHOD(thread_grp_fu_274_p0);
    sensitive << ( output_r_q0 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( convsum_2_reg_209 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_grp_fu_274_p1);
    sensitive << ( tmp_5_reg_790 );
    sensitive << ( layerconv1_0_bias_lo_reg_818 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_grp_pad_3_34_0_8_fu_266_ap_start);
    sensitive << ( grp_pad_3_34_0_8_fu_266_ap_start_reg );

    SC_METHOD(thread_i1_fu_475_p2);
    sensitive << ( i1_0_reg_198 );

    SC_METHOD(thread_i_2_fu_609_p2);
    sensitive << ( i2_0_reg_232 );

    SC_METHOD(thread_i_fu_293_p2);
    sensitive << ( i_0_reg_127 );

    SC_METHOD(thread_icmp_ln31_fu_287_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_0_reg_127 );

    SC_METHOD(thread_icmp_ln34_fu_337_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( x_0_reg_138 );

    SC_METHOD(thread_icmp_ln36_fu_366_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( y_0_reg_150 );

    SC_METHOD(thread_icmp_ln39_fu_378_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j_0_reg_162 );

    SC_METHOD(thread_icmp_ln41_fu_469_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( i1_0_reg_198 );

    SC_METHOD(thread_icmp_ln44_fu_557_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( j1_0_reg_221 );

    SC_METHOD(thread_icmp_ln55_fu_603_p2);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( i2_0_reg_232 );

    SC_METHOD(thread_icmp_ln57_fu_632_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( x3_0_reg_244 );

    SC_METHOD(thread_icmp_ln60_fu_661_p2);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( y4_0_reg_255 );

    SC_METHOD(thread_input_after_padding_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_pad_3_34_0_8_fu_266_output_r_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln47_9_fu_584_p1 );

    SC_METHOD(thread_input_after_padding_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_pad_3_34_0_8_fu_266_output_r_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_after_padding_we0);
    sensitive << ( grp_pad_3_34_0_8_fu_266_output_r_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( grp_pad_3_34_0_8_fu_266_input_r_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( grp_pad_3_34_0_8_fu_266_input_r_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_j1_fu_563_p2);
    sensitive << ( j1_0_reg_221 );

    SC_METHOD(thread_j_fu_384_p2);
    sensitive << ( j_0_reg_162 );

    SC_METHOD(thread_layerconv1_0_bias_address0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( zext_ln63_fu_615_p1 );

    SC_METHOD(thread_layerconv1_0_bias_ce0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_layerconv1_0_weight_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln47_11_fu_598_p1 );

    SC_METHOD(thread_layerconv1_0_weight_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( output_addr_reg_844 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( zext_ln51_2_fu_460_p1 );
    sensitive << ( zext_ln63_4_fu_682_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( grp_fu_274_p2 );
    sensitive << ( convsum_0_reg_173 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln39_fu_378_p2 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_p_shl4_cast_fu_539_p3);
    sensitive << ( trunc_ln47_1_fu_535_p1 );

    SC_METHOD(thread_p_shl5_cast_fu_496_p3);
    sensitive << ( add_ln47_4_fu_491_p2 );

    SC_METHOD(thread_sext_ln47_1_fu_399_p1);
    sensitive << ( add_ln47_1_fu_394_p2 );

    SC_METHOD(thread_sext_ln47_2_fu_411_p1);
    sensitive << ( tmp_7_fu_403_p3 );

    SC_METHOD(thread_sext_ln47_fu_321_p1);
    sensitive << ( sub_ln47_fu_315_p2 );

    SC_METHOD(thread_sub_ln47_1_fu_415_p2);
    sensitive << ( sext_ln47_2_fu_411_p1 );
    sensitive << ( sext_ln47_1_fu_399_p1 );

    SC_METHOD(thread_sub_ln47_2_fu_547_p2);
    sensitive << ( p_shl4_cast_fu_539_p3 );
    sensitive << ( trunc_ln47_fu_531_p1 );

    SC_METHOD(thread_sub_ln47_fu_315_p2);
    sensitive << ( zext_ln47_1_fu_311_p1 );
    sensitive << ( zext_ln47_fu_299_p1 );

    SC_METHOD(thread_tmp_10_fu_504_p3);
    sensitive << ( add_ln47_4_fu_491_p2 );

    SC_METHOD(thread_tmp_36_cast_fu_358_p3);
    sensitive << ( add_ln51_fu_353_p2 );

    SC_METHOD(thread_tmp_38_cast_fu_653_p3);
    sensitive << ( add_ln63_fu_648_p2 );

    SC_METHOD(thread_tmp_4_fu_325_p3);
    sensitive << ( i_0_reg_127 );

    SC_METHOD(thread_tmp_6_fu_620_p3);
    sensitive << ( i2_0_reg_232 );

    SC_METHOD(thread_tmp_7_fu_403_p3);
    sensitive << ( add_ln47_1_fu_394_p2 );

    SC_METHOD(thread_tmp_8_fu_421_p3);
    sensitive << ( j_0_reg_162 );

    SC_METHOD(thread_tmp_9_fu_433_p3);
    sensitive << ( j_0_reg_162 );

    SC_METHOD(thread_tmp_s_fu_303_p3);
    sensitive << ( i_0_reg_127 );

    SC_METHOD(thread_trunc_ln47_1_fu_535_p1);
    sensitive << ( add_ln47_6_fu_526_p2 );

    SC_METHOD(thread_trunc_ln47_fu_531_p1);
    sensitive << ( add_ln47_6_fu_526_p2 );

    SC_METHOD(thread_x_3_fu_638_p2);
    sensitive << ( x3_0_reg_244 );

    SC_METHOD(thread_x_fu_343_p2);
    sensitive << ( x_0_reg_138 );

    SC_METHOD(thread_y_3_fu_372_p2);
    sensitive << ( y_0_reg_150 );

    SC_METHOD(thread_y_fu_667_p2);
    sensitive << ( y4_0_reg_255 );

    SC_METHOD(thread_zext_ln34_fu_333_p1);
    sensitive << ( tmp_4_fu_325_p3 );

    SC_METHOD(thread_zext_ln41_fu_465_p1);
    sensitive << ( i1_0_reg_198 );

    SC_METHOD(thread_zext_ln44_fu_553_p1);
    sensitive << ( j1_0_reg_221 );

    SC_METHOD(thread_zext_ln47_10_fu_589_p1);
    sensitive << ( j1_0_reg_221 );

    SC_METHOD(thread_zext_ln47_11_fu_598_p1);
    sensitive << ( add_ln47_8_fu_593_p2 );

    SC_METHOD(thread_zext_ln47_1_fu_311_p1);
    sensitive << ( tmp_s_fu_303_p3 );

    SC_METHOD(thread_zext_ln47_2_fu_390_p1);
    sensitive << ( j_0_reg_162 );

    SC_METHOD(thread_zext_ln47_3_fu_429_p1);
    sensitive << ( tmp_8_fu_421_p3 );

    SC_METHOD(thread_zext_ln47_4_fu_441_p1);
    sensitive << ( tmp_9_fu_433_p3 );

    SC_METHOD(thread_zext_ln47_5_fu_487_p1);
    sensitive << ( add_ln47_fu_481_p2 );

    SC_METHOD(thread_zext_ln47_6_fu_522_p1);
    sensitive << ( i1_0_reg_198 );

    SC_METHOD(thread_zext_ln47_7_fu_512_p1);
    sensitive << ( tmp_10_fu_504_p3 );

    SC_METHOD(thread_zext_ln47_8_fu_575_p1);
    sensitive << ( add_ln47_2_fu_569_p2 );

    SC_METHOD(thread_zext_ln47_9_fu_584_p1);
    sensitive << ( add_ln47_7_fu_579_p2 );

    SC_METHOD(thread_zext_ln47_fu_299_p1);
    sensitive << ( i_0_reg_127 );

    SC_METHOD(thread_zext_ln51_1_fu_451_p1);
    sensitive << ( y_0_reg_150 );

    SC_METHOD(thread_zext_ln51_2_fu_460_p1);
    sensitive << ( add_ln51_1_fu_455_p2 );

    SC_METHOD(thread_zext_ln51_fu_349_p1);
    sensitive << ( x_0_reg_138 );

    SC_METHOD(thread_zext_ln63_1_fu_628_p1);
    sensitive << ( tmp_6_fu_620_p3 );

    SC_METHOD(thread_zext_ln63_2_fu_644_p1);
    sensitive << ( x3_0_reg_244 );

    SC_METHOD(thread_zext_ln63_3_fu_673_p1);
    sensitive << ( y4_0_reg_255 );

    SC_METHOD(thread_zext_ln63_4_fu_682_p1);
    sensitive << ( add_ln63_1_fu_677_p2 );

    SC_METHOD(thread_zext_ln63_fu_615_p1);
    sensitive << ( i2_0_reg_232 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln31_fu_287_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln34_fu_337_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln39_fu_378_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln41_fu_469_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln44_fu_557_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln55_fu_603_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( icmp_ln57_fu_632_p2 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( icmp_ln60_fu_661_p2 );
    sensitive << ( grp_pad_3_34_0_8_fu_266_ap_done );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln36_fu_366_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000001";
    grp_pad_3_34_0_8_fu_266_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, output_r_q0, "(port)output_r_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, layerconv1_0_weight_address0, "layerconv1_0_weight_address0");
    sc_trace(mVcdFile, layerconv1_0_weight_ce0, "layerconv1_0_weight_ce0");
    sc_trace(mVcdFile, layerconv1_0_weight_q0, "layerconv1_0_weight_q0");
    sc_trace(mVcdFile, layerconv1_0_bias_address0, "layerconv1_0_bias_address0");
    sc_trace(mVcdFile, layerconv1_0_bias_ce0, "layerconv1_0_bias_ce0");
    sc_trace(mVcdFile, layerconv1_0_bias_q0, "layerconv1_0_bias_q0");
    sc_trace(mVcdFile, i_fu_293_p2, "i_fu_293_p2");
    sc_trace(mVcdFile, i_reg_690, "i_reg_690");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, sext_ln47_fu_321_p1, "sext_ln47_fu_321_p1");
    sc_trace(mVcdFile, sext_ln47_reg_695, "sext_ln47_reg_695");
    sc_trace(mVcdFile, icmp_ln31_fu_287_p2, "icmp_ln31_fu_287_p2");
    sc_trace(mVcdFile, zext_ln34_fu_333_p1, "zext_ln34_fu_333_p1");
    sc_trace(mVcdFile, zext_ln34_reg_700, "zext_ln34_reg_700");
    sc_trace(mVcdFile, x_fu_343_p2, "x_fu_343_p2");
    sc_trace(mVcdFile, x_reg_708, "x_reg_708");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_36_cast_fu_358_p3, "tmp_36_cast_fu_358_p3");
    sc_trace(mVcdFile, tmp_36_cast_reg_713, "tmp_36_cast_reg_713");
    sc_trace(mVcdFile, icmp_ln34_fu_337_p2, "icmp_ln34_fu_337_p2");
    sc_trace(mVcdFile, y_3_fu_372_p2, "y_3_fu_372_p2");
    sc_trace(mVcdFile, y_3_reg_721, "y_3_reg_721");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, j_fu_384_p2, "j_fu_384_p2");
    sc_trace(mVcdFile, j_reg_729, "j_reg_729");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, sub_ln47_1_fu_415_p2, "sub_ln47_1_fu_415_p2");
    sc_trace(mVcdFile, sub_ln47_1_reg_734, "sub_ln47_1_reg_734");
    sc_trace(mVcdFile, icmp_ln39_fu_378_p2, "icmp_ln39_fu_378_p2");
    sc_trace(mVcdFile, add_ln47_3_fu_445_p2, "add_ln47_3_fu_445_p2");
    sc_trace(mVcdFile, add_ln47_3_reg_739, "add_ln47_3_reg_739");
    sc_trace(mVcdFile, i1_fu_475_p2, "i1_fu_475_p2");
    sc_trace(mVcdFile, i1_reg_747, "i1_reg_747");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, add_ln47_5_fu_516_p2, "add_ln47_5_fu_516_p2");
    sc_trace(mVcdFile, add_ln47_5_reg_752, "add_ln47_5_reg_752");
    sc_trace(mVcdFile, icmp_ln41_fu_469_p2, "icmp_ln41_fu_469_p2");
    sc_trace(mVcdFile, sub_ln47_2_fu_547_p2, "sub_ln47_2_fu_547_p2");
    sc_trace(mVcdFile, sub_ln47_2_reg_757, "sub_ln47_2_reg_757");
    sc_trace(mVcdFile, j1_fu_563_p2, "j1_fu_563_p2");
    sc_trace(mVcdFile, j1_reg_765, "j1_reg_765");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln44_fu_557_p2, "icmp_ln44_fu_557_p2");
    sc_trace(mVcdFile, input_after_padding_q0, "input_after_padding_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, grp_fu_281_p2, "grp_fu_281_p2");
    sc_trace(mVcdFile, tmp_5_reg_790, "tmp_5_reg_790");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_274_p2, "grp_fu_274_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, i_2_fu_609_p2, "i_2_fu_609_p2");
    sc_trace(mVcdFile, i_2_reg_803, "i_2_reg_803");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, icmp_ln55_fu_603_p2, "icmp_ln55_fu_603_p2");
    sc_trace(mVcdFile, zext_ln63_1_fu_628_p1, "zext_ln63_1_fu_628_p1");
    sc_trace(mVcdFile, zext_ln63_1_reg_813, "zext_ln63_1_reg_813");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, layerconv1_0_bias_lo_reg_818, "layerconv1_0_bias_lo_reg_818");
    sc_trace(mVcdFile, x_3_fu_638_p2, "x_3_fu_638_p2");
    sc_trace(mVcdFile, x_3_reg_826, "x_3_reg_826");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp_38_cast_fu_653_p3, "tmp_38_cast_fu_653_p3");
    sc_trace(mVcdFile, tmp_38_cast_reg_831, "tmp_38_cast_reg_831");
    sc_trace(mVcdFile, icmp_ln57_fu_632_p2, "icmp_ln57_fu_632_p2");
    sc_trace(mVcdFile, y_fu_667_p2, "y_fu_667_p2");
    sc_trace(mVcdFile, y_reg_839, "y_reg_839");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, output_addr_reg_844, "output_addr_reg_844");
    sc_trace(mVcdFile, icmp_ln60_fu_661_p2, "icmp_ln60_fu_661_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, input_after_padding_address0, "input_after_padding_address0");
    sc_trace(mVcdFile, input_after_padding_ce0, "input_after_padding_ce0");
    sc_trace(mVcdFile, input_after_padding_we0, "input_after_padding_we0");
    sc_trace(mVcdFile, grp_pad_3_34_0_8_fu_266_ap_start, "grp_pad_3_34_0_8_fu_266_ap_start");
    sc_trace(mVcdFile, grp_pad_3_34_0_8_fu_266_ap_done, "grp_pad_3_34_0_8_fu_266_ap_done");
    sc_trace(mVcdFile, grp_pad_3_34_0_8_fu_266_ap_idle, "grp_pad_3_34_0_8_fu_266_ap_idle");
    sc_trace(mVcdFile, grp_pad_3_34_0_8_fu_266_ap_ready, "grp_pad_3_34_0_8_fu_266_ap_ready");
    sc_trace(mVcdFile, grp_pad_3_34_0_8_fu_266_input_r_address0, "grp_pad_3_34_0_8_fu_266_input_r_address0");
    sc_trace(mVcdFile, grp_pad_3_34_0_8_fu_266_input_r_ce0, "grp_pad_3_34_0_8_fu_266_input_r_ce0");
    sc_trace(mVcdFile, grp_pad_3_34_0_8_fu_266_output_r_address0, "grp_pad_3_34_0_8_fu_266_output_r_address0");
    sc_trace(mVcdFile, grp_pad_3_34_0_8_fu_266_output_r_ce0, "grp_pad_3_34_0_8_fu_266_output_r_ce0");
    sc_trace(mVcdFile, grp_pad_3_34_0_8_fu_266_output_r_we0, "grp_pad_3_34_0_8_fu_266_output_r_we0");
    sc_trace(mVcdFile, grp_pad_3_34_0_8_fu_266_output_r_d0, "grp_pad_3_34_0_8_fu_266_output_r_d0");
    sc_trace(mVcdFile, i_0_reg_127, "i_0_reg_127");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, x_0_reg_138, "x_0_reg_138");
    sc_trace(mVcdFile, icmp_ln36_fu_366_p2, "icmp_ln36_fu_366_p2");
    sc_trace(mVcdFile, y_0_reg_150, "y_0_reg_150");
    sc_trace(mVcdFile, j_0_reg_162, "j_0_reg_162");
    sc_trace(mVcdFile, convsum_0_reg_173, "convsum_0_reg_173");
    sc_trace(mVcdFile, convsum_1_reg_186, "convsum_1_reg_186");
    sc_trace(mVcdFile, i1_0_reg_198, "i1_0_reg_198");
    sc_trace(mVcdFile, convsum_2_reg_209, "convsum_2_reg_209");
    sc_trace(mVcdFile, j1_0_reg_221, "j1_0_reg_221");
    sc_trace(mVcdFile, i2_0_reg_232, "i2_0_reg_232");
    sc_trace(mVcdFile, x3_0_reg_244, "x3_0_reg_244");
    sc_trace(mVcdFile, y4_0_reg_255, "y4_0_reg_255");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, grp_pad_3_34_0_8_fu_266_ap_start_reg, "grp_pad_3_34_0_8_fu_266_ap_start_reg");
    sc_trace(mVcdFile, zext_ln51_2_fu_460_p1, "zext_ln51_2_fu_460_p1");
    sc_trace(mVcdFile, zext_ln47_9_fu_584_p1, "zext_ln47_9_fu_584_p1");
    sc_trace(mVcdFile, zext_ln47_11_fu_598_p1, "zext_ln47_11_fu_598_p1");
    sc_trace(mVcdFile, zext_ln63_fu_615_p1, "zext_ln63_fu_615_p1");
    sc_trace(mVcdFile, zext_ln63_4_fu_682_p1, "zext_ln63_4_fu_682_p1");
    sc_trace(mVcdFile, grp_fu_274_p0, "grp_fu_274_p0");
    sc_trace(mVcdFile, grp_fu_274_p1, "grp_fu_274_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp_s_fu_303_p3, "tmp_s_fu_303_p3");
    sc_trace(mVcdFile, zext_ln47_1_fu_311_p1, "zext_ln47_1_fu_311_p1");
    sc_trace(mVcdFile, zext_ln47_fu_299_p1, "zext_ln47_fu_299_p1");
    sc_trace(mVcdFile, sub_ln47_fu_315_p2, "sub_ln47_fu_315_p2");
    sc_trace(mVcdFile, tmp_4_fu_325_p3, "tmp_4_fu_325_p3");
    sc_trace(mVcdFile, zext_ln51_fu_349_p1, "zext_ln51_fu_349_p1");
    sc_trace(mVcdFile, add_ln51_fu_353_p2, "add_ln51_fu_353_p2");
    sc_trace(mVcdFile, zext_ln47_2_fu_390_p1, "zext_ln47_2_fu_390_p1");
    sc_trace(mVcdFile, add_ln47_1_fu_394_p2, "add_ln47_1_fu_394_p2");
    sc_trace(mVcdFile, tmp_7_fu_403_p3, "tmp_7_fu_403_p3");
    sc_trace(mVcdFile, sext_ln47_2_fu_411_p1, "sext_ln47_2_fu_411_p1");
    sc_trace(mVcdFile, sext_ln47_1_fu_399_p1, "sext_ln47_1_fu_399_p1");
    sc_trace(mVcdFile, tmp_8_fu_421_p3, "tmp_8_fu_421_p3");
    sc_trace(mVcdFile, tmp_9_fu_433_p3, "tmp_9_fu_433_p3");
    sc_trace(mVcdFile, zext_ln47_4_fu_441_p1, "zext_ln47_4_fu_441_p1");
    sc_trace(mVcdFile, zext_ln47_3_fu_429_p1, "zext_ln47_3_fu_429_p1");
    sc_trace(mVcdFile, zext_ln51_1_fu_451_p1, "zext_ln51_1_fu_451_p1");
    sc_trace(mVcdFile, add_ln51_1_fu_455_p2, "add_ln51_1_fu_455_p2");
    sc_trace(mVcdFile, zext_ln41_fu_465_p1, "zext_ln41_fu_465_p1");
    sc_trace(mVcdFile, add_ln47_fu_481_p2, "add_ln47_fu_481_p2");
    sc_trace(mVcdFile, zext_ln47_5_fu_487_p1, "zext_ln47_5_fu_487_p1");
    sc_trace(mVcdFile, add_ln47_4_fu_491_p2, "add_ln47_4_fu_491_p2");
    sc_trace(mVcdFile, tmp_10_fu_504_p3, "tmp_10_fu_504_p3");
    sc_trace(mVcdFile, zext_ln47_7_fu_512_p1, "zext_ln47_7_fu_512_p1");
    sc_trace(mVcdFile, p_shl5_cast_fu_496_p3, "p_shl5_cast_fu_496_p3");
    sc_trace(mVcdFile, zext_ln47_6_fu_522_p1, "zext_ln47_6_fu_522_p1");
    sc_trace(mVcdFile, add_ln47_6_fu_526_p2, "add_ln47_6_fu_526_p2");
    sc_trace(mVcdFile, trunc_ln47_1_fu_535_p1, "trunc_ln47_1_fu_535_p1");
    sc_trace(mVcdFile, p_shl4_cast_fu_539_p3, "p_shl4_cast_fu_539_p3");
    sc_trace(mVcdFile, trunc_ln47_fu_531_p1, "trunc_ln47_fu_531_p1");
    sc_trace(mVcdFile, zext_ln44_fu_553_p1, "zext_ln44_fu_553_p1");
    sc_trace(mVcdFile, add_ln47_2_fu_569_p2, "add_ln47_2_fu_569_p2");
    sc_trace(mVcdFile, zext_ln47_8_fu_575_p1, "zext_ln47_8_fu_575_p1");
    sc_trace(mVcdFile, add_ln47_7_fu_579_p2, "add_ln47_7_fu_579_p2");
    sc_trace(mVcdFile, zext_ln47_10_fu_589_p1, "zext_ln47_10_fu_589_p1");
    sc_trace(mVcdFile, add_ln47_8_fu_593_p2, "add_ln47_8_fu_593_p2");
    sc_trace(mVcdFile, tmp_6_fu_620_p3, "tmp_6_fu_620_p3");
    sc_trace(mVcdFile, zext_ln63_2_fu_644_p1, "zext_ln63_2_fu_644_p1");
    sc_trace(mVcdFile, add_ln63_fu_648_p2, "add_ln63_fu_648_p2");
    sc_trace(mVcdFile, zext_ln63_3_fu_673_p1, "zext_ln63_3_fu_673_p1");
    sc_trace(mVcdFile, add_ln63_1_fu_677_p2, "add_ln63_1_fu_677_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

conv_1::~conv_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete layerconv1_0_weight_U;
    delete layerconv1_0_bias_U;
    delete input_after_padding_U;
    delete grp_pad_3_34_0_8_fu_266;
    delete test_hadd_16ns_16eOg_U3;
    delete test_hmul_16ns_16fYi_U4;
}

void conv_1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void conv_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln36_fu_366_p2.read()))) {
        convsum_0_reg_173 = ap_const_lv16_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln41_fu_469_p2.read(), ap_const_lv1_1))) {
        convsum_0_reg_173 = convsum_1_reg_186.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln44_fu_557_p2.read(), ap_const_lv1_1))) {
        convsum_1_reg_186 = convsum_2_reg_209.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln39_fu_378_p2.read()))) {
        convsum_1_reg_186 = convsum_0_reg_173.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_469_p2.read()))) {
        convsum_2_reg_209 = convsum_1_reg_186.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        convsum_2_reg_209 = grp_fu_274_p2.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_pad_3_34_0_8_fu_266_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_pad_3_34_0_8_fu_266_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pad_3_34_0_8_fu_266_ap_ready.read())) {
            grp_pad_3_34_0_8_fu_266_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln44_fu_557_p2.read(), ap_const_lv1_1))) {
        i1_0_reg_198 = i1_reg_747.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln39_fu_378_p2.read()))) {
        i1_0_reg_198 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_287_p2.read(), ap_const_lv1_1))) {
        i2_0_reg_232 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(icmp_ln57_fu_632_p2.read(), ap_const_lv1_1))) {
        i2_0_reg_232 = i_2_reg_803.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln34_fu_337_p2.read(), ap_const_lv1_1))) {
        i_0_reg_127 = i_reg_690.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(grp_pad_3_34_0_8_fu_266_ap_done.read(), ap_const_logic_1))) {
        i_0_reg_127 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_469_p2.read()))) {
        j1_0_reg_221 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        j1_0_reg_221 = j1_reg_765.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln36_fu_366_p2.read()))) {
        j_0_reg_162 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(icmp_ln41_fu_469_p2.read(), ap_const_lv1_1))) {
        j_0_reg_162 = j_reg_729.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
         esl_seteq<1,1,1>(icmp_ln60_fu_661_p2.read(), ap_const_lv1_1))) {
        x3_0_reg_244 = x_3_reg_826.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        x3_0_reg_244 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln36_fu_366_p2.read()))) {
        x_0_reg_138 = x_reg_708.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln31_fu_287_p2.read(), ap_const_lv1_0))) {
        x_0_reg_138 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_632_p2.read()))) {
        y4_0_reg_255 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        y4_0_reg_255 = y_reg_839.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_337_p2.read()))) {
        y_0_reg_150 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln39_fu_378_p2.read(), ap_const_lv1_1))) {
        y_0_reg_150 = y_3_reg_721.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln39_fu_378_p2.read()))) {
        add_ln47_3_reg_739 = add_ln47_3_fu_445_p2.read();
        sub_ln47_1_reg_734 = sub_ln47_1_fu_415_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_469_p2.read()))) {
        add_ln47_5_reg_752 = add_ln47_5_fu_516_p2.read();
        sub_ln47_2_reg_757 = sub_ln47_2_fu_547_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i1_reg_747 = i1_fu_475_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        i_2_reg_803 = i_2_fu_609_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_reg_690 = i_fu_293_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        j1_reg_765 = j1_fu_563_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_reg_729 = j_fu_384_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        layerconv1_0_bias_lo_reg_818 = layerconv1_0_bias_q0.read();
        zext_ln63_1_reg_813 = zext_ln63_1_fu_628_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_fu_661_p2.read()))) {
        output_addr_reg_844 =  (sc_lv<13>) (zext_ln63_4_fu_682_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln31_fu_287_p2.read(), ap_const_lv1_0))) {
        sext_ln47_reg_695 = sext_ln47_fu_321_p1.read();
        zext_ln34_reg_700 = zext_ln34_fu_333_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln34_fu_337_p2.read()))) {
        tmp_36_cast_reg_713 = tmp_36_cast_fu_358_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_632_p2.read()))) {
        tmp_38_cast_reg_831 = tmp_38_cast_fu_653_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_5_reg_790 = grp_fu_281_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        x_3_reg_826 = x_3_fu_638_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_reg_708 = x_fu_343_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_3_reg_721 = y_3_fu_372_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        y_reg_839 = y_fu_667_p2.read();
    }
}

void conv_1::thread_add_ln47_1_fu_394_p2() {
    add_ln47_1_fu_394_p2 = (!sext_ln47_reg_695.read().is_01() || !zext_ln47_2_fu_390_p1.read().is_01())? sc_lv<8>(): (sc_bigint<8>(sext_ln47_reg_695.read()) + sc_biguint<8>(zext_ln47_2_fu_390_p1.read()));
}

void conv_1::thread_add_ln47_2_fu_569_p2() {
    add_ln47_2_fu_569_p2 = (!zext_ln44_fu_553_p1.read().is_01() || !y_0_reg_150.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln44_fu_553_p1.read()) + sc_biguint<6>(y_0_reg_150.read()));
}

void conv_1::thread_add_ln47_3_fu_445_p2() {
    add_ln47_3_fu_445_p2 = (!zext_ln47_4_fu_441_p1.read().is_01() || !zext_ln47_3_fu_429_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln47_4_fu_441_p1.read()) + sc_biguint<8>(zext_ln47_3_fu_429_p1.read()));
}

void conv_1::thread_add_ln47_4_fu_491_p2() {
    add_ln47_4_fu_491_p2 = (!add_ln47_3_reg_739.read().is_01() || !zext_ln47_5_fu_487_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(add_ln47_3_reg_739.read()) + sc_biguint<8>(zext_ln47_5_fu_487_p1.read()));
}

void conv_1::thread_add_ln47_5_fu_516_p2() {
    add_ln47_5_fu_516_p2 = (!zext_ln47_7_fu_512_p1.read().is_01() || !p_shl5_cast_fu_496_p3.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln47_7_fu_512_p1.read()) + sc_biguint<13>(p_shl5_cast_fu_496_p3.read()));
}

void conv_1::thread_add_ln47_6_fu_526_p2() {
    add_ln47_6_fu_526_p2 = (!sub_ln47_1_reg_734.read().is_01() || !zext_ln47_6_fu_522_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(sub_ln47_1_reg_734.read()) + sc_biguint<64>(zext_ln47_6_fu_522_p1.read()));
}

void conv_1::thread_add_ln47_7_fu_579_p2() {
    add_ln47_7_fu_579_p2 = (!add_ln47_5_reg_752.read().is_01() || !zext_ln47_8_fu_575_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(add_ln47_5_reg_752.read()) + sc_biguint<13>(zext_ln47_8_fu_575_p1.read()));
}

void conv_1::thread_add_ln47_8_fu_593_p2() {
    add_ln47_8_fu_593_p2 = (!sub_ln47_2_reg_757.read().is_01() || !zext_ln47_10_fu_589_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(sub_ln47_2_reg_757.read()) + sc_biguint<9>(zext_ln47_10_fu_589_p1.read()));
}

void conv_1::thread_add_ln47_fu_481_p2() {
    add_ln47_fu_481_p2 = (!zext_ln41_fu_465_p1.read().is_01() || !x_0_reg_138.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln41_fu_465_p1.read()) + sc_biguint<6>(x_0_reg_138.read()));
}

void conv_1::thread_add_ln51_1_fu_455_p2() {
    add_ln51_1_fu_455_p2 = (!tmp_36_cast_reg_713.read().is_01() || !zext_ln51_1_fu_451_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_36_cast_reg_713.read()) + sc_biguint<15>(zext_ln51_1_fu_451_p1.read()));
}

void conv_1::thread_add_ln51_fu_353_p2() {
    add_ln51_fu_353_p2 = (!zext_ln51_fu_349_p1.read().is_01() || !zext_ln34_reg_700.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln51_fu_349_p1.read()) + sc_biguint<10>(zext_ln34_reg_700.read()));
}

void conv_1::thread_add_ln63_1_fu_677_p2() {
    add_ln63_1_fu_677_p2 = (!tmp_38_cast_reg_831.read().is_01() || !zext_ln63_3_fu_673_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_38_cast_reg_831.read()) + sc_biguint<15>(zext_ln63_3_fu_673_p1.read()));
}

void conv_1::thread_add_ln63_fu_648_p2() {
    add_ln63_fu_648_p2 = (!zext_ln63_2_fu_644_p1.read().is_01() || !zext_ln63_1_reg_813.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln63_2_fu_644_p1.read()) + sc_biguint<10>(zext_ln63_1_reg_813.read()));
}

void conv_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv_1::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv_1::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void conv_1::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void conv_1::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void conv_1::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void conv_1::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void conv_1::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void conv_1::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void conv_1::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void conv_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv_1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv_1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv_1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv_1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv_1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv_1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv_1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(icmp_ln55_fu_603_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv_1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(icmp_ln55_fu_603_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv_1::thread_grp_fu_274_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_274_p0 = output_r_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_274_p0 = convsum_2_reg_209.read();
    } else {
        grp_fu_274_p0 = "XXXXXXXXXXXXXXXX";
    }
}

void conv_1::thread_grp_fu_274_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        grp_fu_274_p1 = layerconv1_0_bias_lo_reg_818.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_274_p1 = tmp_5_reg_790.read();
    } else {
        grp_fu_274_p1 = "XXXXXXXXXXXXXXXX";
    }
}

void conv_1::thread_grp_pad_3_34_0_8_fu_266_ap_start() {
    grp_pad_3_34_0_8_fu_266_ap_start = grp_pad_3_34_0_8_fu_266_ap_start_reg.read();
}

void conv_1::thread_i1_fu_475_p2() {
    i1_fu_475_p2 = (!i1_0_reg_198.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_0_reg_198.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_1::thread_i_2_fu_609_p2() {
    i_2_fu_609_p2 = (!i2_0_reg_232.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i2_0_reg_232.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_1::thread_i_fu_293_p2() {
    i_fu_293_p2 = (!i_0_reg_127.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_127.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_1::thread_icmp_ln31_fu_287_p2() {
    icmp_ln31_fu_287_p2 = (!i_0_reg_127.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_127.read() == ap_const_lv4_8);
}

void conv_1::thread_icmp_ln34_fu_337_p2() {
    icmp_ln34_fu_337_p2 = (!x_0_reg_138.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_138.read() == ap_const_lv6_20);
}

void conv_1::thread_icmp_ln36_fu_366_p2() {
    icmp_ln36_fu_366_p2 = (!y_0_reg_150.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_150.read() == ap_const_lv6_20);
}

void conv_1::thread_icmp_ln39_fu_378_p2() {
    icmp_ln39_fu_378_p2 = (!j_0_reg_162.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_162.read() == ap_const_lv2_3);
}

void conv_1::thread_icmp_ln41_fu_469_p2() {
    icmp_ln41_fu_469_p2 = (!i1_0_reg_198.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_198.read() == ap_const_lv2_3);
}

void conv_1::thread_icmp_ln44_fu_557_p2() {
    icmp_ln44_fu_557_p2 = (!j1_0_reg_221.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j1_0_reg_221.read() == ap_const_lv2_3);
}

void conv_1::thread_icmp_ln55_fu_603_p2() {
    icmp_ln55_fu_603_p2 = (!i2_0_reg_232.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i2_0_reg_232.read() == ap_const_lv4_8);
}

void conv_1::thread_icmp_ln57_fu_632_p2() {
    icmp_ln57_fu_632_p2 = (!x3_0_reg_244.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(x3_0_reg_244.read() == ap_const_lv6_20);
}

void conv_1::thread_icmp_ln60_fu_661_p2() {
    icmp_ln60_fu_661_p2 = (!y4_0_reg_255.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(y4_0_reg_255.read() == ap_const_lv6_20);
}

void conv_1::thread_input_after_padding_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_after_padding_address0 =  (sc_lv<12>) (zext_ln47_9_fu_584_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_after_padding_address0 = grp_pad_3_34_0_8_fu_266_output_r_address0.read();
    } else {
        input_after_padding_address0 =  (sc_lv<12>) ("XXXXXXXXXXXX");
    }
}

void conv_1::thread_input_after_padding_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_after_padding_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_after_padding_ce0 = grp_pad_3_34_0_8_fu_266_output_r_ce0.read();
    } else {
        input_after_padding_ce0 = ap_const_logic_0;
    }
}

void conv_1::thread_input_after_padding_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_after_padding_we0 = grp_pad_3_34_0_8_fu_266_output_r_we0.read();
    } else {
        input_after_padding_we0 = ap_const_logic_0;
    }
}

void conv_1::thread_input_r_address0() {
    input_r_address0 = grp_pad_3_34_0_8_fu_266_input_r_address0.read();
}

void conv_1::thread_input_r_ce0() {
    input_r_ce0 = grp_pad_3_34_0_8_fu_266_input_r_ce0.read();
}

void conv_1::thread_j1_fu_563_p2() {
    j1_fu_563_p2 = (!j1_0_reg_221.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j1_0_reg_221.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_1::thread_j_fu_384_p2() {
    j_fu_384_p2 = (!j_0_reg_162.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j_0_reg_162.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_1::thread_layerconv1_0_bias_address0() {
    layerconv1_0_bias_address0 =  (sc_lv<3>) (zext_ln63_fu_615_p1.read());
}

void conv_1::thread_layerconv1_0_bias_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        layerconv1_0_bias_ce0 = ap_const_logic_1;
    } else {
        layerconv1_0_bias_ce0 = ap_const_logic_0;
    }
}

void conv_1::thread_layerconv1_0_weight_address0() {
    layerconv1_0_weight_address0 =  (sc_lv<8>) (zext_ln47_11_fu_598_p1.read());
}

void conv_1::thread_layerconv1_0_weight_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        layerconv1_0_weight_ce0 = ap_const_logic_1;
    } else {
        layerconv1_0_weight_ce0 = ap_const_logic_0;
    }
}

void conv_1::thread_output_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_r_address0 = output_addr_reg_844.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        output_r_address0 =  (sc_lv<13>) (zext_ln63_4_fu_682_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_address0 =  (sc_lv<13>) (zext_ln51_2_fu_460_p1.read());
    } else {
        output_r_address0 =  (sc_lv<13>) ("XXXXXXXXXXXXX");
    }
}

void conv_1::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv_1::thread_output_r_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_r_d0 = grp_fu_274_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_d0 = convsum_0_reg_173.read();
    } else {
        output_r_d0 = "XXXXXXXXXXXXXXXX";
    }
}

void conv_1::thread_output_r_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(icmp_ln39_fu_378_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv_1::thread_p_shl4_cast_fu_539_p3() {
    p_shl4_cast_fu_539_p3 = esl_concat<7,2>(trunc_ln47_1_fu_535_p1.read(), ap_const_lv2_0);
}

void conv_1::thread_p_shl5_cast_fu_496_p3() {
    p_shl5_cast_fu_496_p3 = esl_concat<8,5>(add_ln47_4_fu_491_p2.read(), ap_const_lv5_0);
}

void conv_1::thread_sext_ln47_1_fu_399_p1() {
    sext_ln47_1_fu_399_p1 = esl_sext<64,8>(add_ln47_1_fu_394_p2.read());
}

void conv_1::thread_sext_ln47_2_fu_411_p1() {
    sext_ln47_2_fu_411_p1 = esl_sext<64,10>(tmp_7_fu_403_p3.read());
}

void conv_1::thread_sext_ln47_fu_321_p1() {
    sext_ln47_fu_321_p1 = esl_sext<8,7>(sub_ln47_fu_315_p2.read());
}

void conv_1::thread_sub_ln47_1_fu_415_p2() {
    sub_ln47_1_fu_415_p2 = (!sext_ln47_2_fu_411_p1.read().is_01() || !sext_ln47_1_fu_399_p1.read().is_01())? sc_lv<64>(): (sc_bigint<64>(sext_ln47_2_fu_411_p1.read()) - sc_bigint<64>(sext_ln47_1_fu_399_p1.read()));
}

void conv_1::thread_sub_ln47_2_fu_547_p2() {
    sub_ln47_2_fu_547_p2 = (!p_shl4_cast_fu_539_p3.read().is_01() || !trunc_ln47_fu_531_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl4_cast_fu_539_p3.read()) - sc_biguint<9>(trunc_ln47_fu_531_p1.read()));
}

void conv_1::thread_sub_ln47_fu_315_p2() {
    sub_ln47_fu_315_p2 = (!zext_ln47_1_fu_311_p1.read().is_01() || !zext_ln47_fu_299_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln47_1_fu_311_p1.read()) - sc_biguint<7>(zext_ln47_fu_299_p1.read()));
}

void conv_1::thread_tmp_10_fu_504_p3() {
    tmp_10_fu_504_p3 = esl_concat<8,1>(add_ln47_4_fu_491_p2.read(), ap_const_lv1_0);
}

void conv_1::thread_tmp_36_cast_fu_358_p3() {
    tmp_36_cast_fu_358_p3 = esl_concat<10,5>(add_ln51_fu_353_p2.read(), ap_const_lv5_0);
}

void conv_1::thread_tmp_38_cast_fu_653_p3() {
    tmp_38_cast_fu_653_p3 = esl_concat<10,5>(add_ln63_fu_648_p2.read(), ap_const_lv5_0);
}

void conv_1::thread_tmp_4_fu_325_p3() {
    tmp_4_fu_325_p3 = esl_concat<4,5>(i_0_reg_127.read(), ap_const_lv5_0);
}

void conv_1::thread_tmp_6_fu_620_p3() {
    tmp_6_fu_620_p3 = esl_concat<4,5>(i2_0_reg_232.read(), ap_const_lv5_0);
}

void conv_1::thread_tmp_7_fu_403_p3() {
    tmp_7_fu_403_p3 = esl_concat<8,2>(add_ln47_1_fu_394_p2.read(), ap_const_lv2_0);
}

void conv_1::thread_tmp_8_fu_421_p3() {
    tmp_8_fu_421_p3 = esl_concat<2,5>(j_0_reg_162.read(), ap_const_lv5_0);
}

void conv_1::thread_tmp_9_fu_433_p3() {
    tmp_9_fu_433_p3 = esl_concat<2,1>(j_0_reg_162.read(), ap_const_lv1_0);
}

void conv_1::thread_tmp_s_fu_303_p3() {
    tmp_s_fu_303_p3 = esl_concat<4,2>(i_0_reg_127.read(), ap_const_lv2_0);
}

void conv_1::thread_trunc_ln47_1_fu_535_p1() {
    trunc_ln47_1_fu_535_p1 = add_ln47_6_fu_526_p2.read().range(7-1, 0);
}

void conv_1::thread_trunc_ln47_fu_531_p1() {
    trunc_ln47_fu_531_p1 = add_ln47_6_fu_526_p2.read().range(9-1, 0);
}

void conv_1::thread_x_3_fu_638_p2() {
    x_3_fu_638_p2 = (!x3_0_reg_244.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(x3_0_reg_244.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv_1::thread_x_fu_343_p2() {
    x_fu_343_p2 = (!x_0_reg_138.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(x_0_reg_138.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv_1::thread_y_3_fu_372_p2() {
    y_3_fu_372_p2 = (!y_0_reg_150.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(y_0_reg_150.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv_1::thread_y_fu_667_p2() {
    y_fu_667_p2 = (!y4_0_reg_255.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(y4_0_reg_255.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv_1::thread_zext_ln34_fu_333_p1() {
    zext_ln34_fu_333_p1 = esl_zext<10,9>(tmp_4_fu_325_p3.read());
}

void conv_1::thread_zext_ln41_fu_465_p1() {
    zext_ln41_fu_465_p1 = esl_zext<6,2>(i1_0_reg_198.read());
}

void conv_1::thread_zext_ln44_fu_553_p1() {
    zext_ln44_fu_553_p1 = esl_zext<6,2>(j1_0_reg_221.read());
}

void conv_1::thread_zext_ln47_10_fu_589_p1() {
    zext_ln47_10_fu_589_p1 = esl_zext<9,2>(j1_0_reg_221.read());
}

void conv_1::thread_zext_ln47_11_fu_598_p1() {
    zext_ln47_11_fu_598_p1 = esl_zext<64,9>(add_ln47_8_fu_593_p2.read());
}

void conv_1::thread_zext_ln47_1_fu_311_p1() {
    zext_ln47_1_fu_311_p1 = esl_zext<7,6>(tmp_s_fu_303_p3.read());
}

void conv_1::thread_zext_ln47_2_fu_390_p1() {
    zext_ln47_2_fu_390_p1 = esl_zext<8,2>(j_0_reg_162.read());
}

void conv_1::thread_zext_ln47_3_fu_429_p1() {
    zext_ln47_3_fu_429_p1 = esl_zext<8,7>(tmp_8_fu_421_p3.read());
}

void conv_1::thread_zext_ln47_4_fu_441_p1() {
    zext_ln47_4_fu_441_p1 = esl_zext<8,3>(tmp_9_fu_433_p3.read());
}

void conv_1::thread_zext_ln47_5_fu_487_p1() {
    zext_ln47_5_fu_487_p1 = esl_zext<8,6>(add_ln47_fu_481_p2.read());
}

void conv_1::thread_zext_ln47_6_fu_522_p1() {
    zext_ln47_6_fu_522_p1 = esl_zext<64,2>(i1_0_reg_198.read());
}

void conv_1::thread_zext_ln47_7_fu_512_p1() {
    zext_ln47_7_fu_512_p1 = esl_zext<13,9>(tmp_10_fu_504_p3.read());
}

void conv_1::thread_zext_ln47_8_fu_575_p1() {
    zext_ln47_8_fu_575_p1 = esl_zext<13,6>(add_ln47_2_fu_569_p2.read());
}

void conv_1::thread_zext_ln47_9_fu_584_p1() {
    zext_ln47_9_fu_584_p1 = esl_zext<64,13>(add_ln47_7_fu_579_p2.read());
}

void conv_1::thread_zext_ln47_fu_299_p1() {
    zext_ln47_fu_299_p1 = esl_zext<7,4>(i_0_reg_127.read());
}

void conv_1::thread_zext_ln51_1_fu_451_p1() {
    zext_ln51_1_fu_451_p1 = esl_zext<15,6>(y_0_reg_150.read());
}

void conv_1::thread_zext_ln51_2_fu_460_p1() {
    zext_ln51_2_fu_460_p1 = esl_zext<64,15>(add_ln51_1_fu_455_p2.read());
}

void conv_1::thread_zext_ln51_fu_349_p1() {
    zext_ln51_fu_349_p1 = esl_zext<10,6>(x_0_reg_138.read());
}

void conv_1::thread_zext_ln63_1_fu_628_p1() {
    zext_ln63_1_fu_628_p1 = esl_zext<10,9>(tmp_6_fu_620_p3.read());
}

void conv_1::thread_zext_ln63_2_fu_644_p1() {
    zext_ln63_2_fu_644_p1 = esl_zext<10,6>(x3_0_reg_244.read());
}

void conv_1::thread_zext_ln63_3_fu_673_p1() {
    zext_ln63_3_fu_673_p1 = esl_zext<15,6>(y4_0_reg_255.read());
}

void conv_1::thread_zext_ln63_4_fu_682_p1() {
    zext_ln63_4_fu_682_p1 = esl_zext<64,15>(add_ln63_1_fu_677_p2.read());
}

void conv_1::thread_zext_ln63_fu_615_p1() {
    zext_ln63_fu_615_p1 = esl_zext<64,4>(i2_0_reg_232.read());
}

void conv_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_pad_3_34_0_8_fu_266_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln31_fu_287_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln34_fu_337_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln36_fu_366_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln39_fu_378_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln41_fu_469_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln44_fu_557_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(icmp_ln55_fu_603_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(icmp_ln57_fu_632_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(icmp_ln60_fu_661_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

