// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "max_pool_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic max_pool_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic max_pool_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> max_pool_1::ap_ST_fsm_state1 = "1";
const sc_lv<8> max_pool_1::ap_ST_fsm_state2 = "10";
const sc_lv<8> max_pool_1::ap_ST_fsm_state3 = "100";
const sc_lv<8> max_pool_1::ap_ST_fsm_state4 = "1000";
const sc_lv<8> max_pool_1::ap_ST_fsm_state5 = "10000";
const sc_lv<8> max_pool_1::ap_ST_fsm_state6 = "100000";
const sc_lv<8> max_pool_1::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> max_pool_1::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> max_pool_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> max_pool_1::ap_const_lv32_1 = "1";
const sc_lv<1> max_pool_1::ap_const_lv1_0 = "0";
const sc_lv<32> max_pool_1::ap_const_lv32_2 = "10";
const sc_lv<32> max_pool_1::ap_const_lv32_3 = "11";
const sc_lv<32> max_pool_1::ap_const_lv32_4 = "100";
const sc_lv<1> max_pool_1::ap_const_lv1_1 = "1";
const sc_lv<32> max_pool_1::ap_const_lv32_5 = "101";
const sc_lv<32> max_pool_1::ap_const_lv32_6 = "110";
const sc_lv<32> max_pool_1::ap_const_lv32_7 = "111";
const sc_lv<5> max_pool_1::ap_const_lv5_0 = "00000";
const sc_lv<3> max_pool_1::ap_const_lv3_0 = "000";
const sc_lv<16> max_pool_1::ap_const_lv16_FC00 = "1111110000000000";
const sc_lv<5> max_pool_1::ap_const_lv5_10 = "10000";
const sc_lv<5> max_pool_1::ap_const_lv5_1 = "1";
const sc_lv<4> max_pool_1::ap_const_lv4_0 = "0000";
const sc_lv<3> max_pool_1::ap_const_lv3_7 = "111";
const sc_lv<3> max_pool_1::ap_const_lv3_1 = "1";
const sc_lv<4> max_pool_1::ap_const_lv4_2 = "10";
const sc_lv<5> max_pool_1::ap_const_lv5_2 = "10";
const bool max_pool_1::ap_const_boolean_1 = true;

max_pool_1::max_pool_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    test_hcmp_16ns_16g8j_U31 = new test_hcmp_16ns_16g8j<1,1,16,16,1>("test_hcmp_16ns_16g8j_U31");
    test_hcmp_16ns_16g8j_U31->din0(max_record_reg_509);
    test_hcmp_16ns_16g8j_U31->din1(max_record_1_reg_131);
    test_hcmp_16ns_16g8j_U31->opcode(ap_var_for_const0);
    test_hcmp_16ns_16g8j_U31->dout(tmp_fu_152_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln80_fu_253_p2);
    sensitive << ( x_fu_241_p3 );

    SC_METHOD(thread_add_ln81_fu_318_p2);
    sensitive << ( y_fu_306_p3 );

    SC_METHOD(thread_add_ln83_1_fu_395_p2);
    sensitive << ( sub_ln83_1_reg_486 );
    sensitive << ( trunc_ln83_2_fu_391_p1 );

    SC_METHOD(thread_add_ln83_fu_337_p2);
    sensitive << ( sext_ln83_reg_432 );
    sensitive << ( sext_ln83_1_fu_333_p1 );

    SC_METHOD(thread_add_ln87_1_fu_376_p2);
    sensitive << ( sub_ln87_1_reg_460 );
    sensitive << ( zext_ln87_2_fu_372_p1 );

    SC_METHOD(thread_add_ln87_fu_267_p2);
    sensitive << ( sext_ln87_reg_437 );
    sensitive << ( zext_ln87_1_fu_263_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln73_fu_157_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln73_fu_157_p2 );

    SC_METHOD(thread_i_fu_235_p2);
    sensitive << ( i_0_reg_85 );

    SC_METHOD(thread_icmp_ln73_fu_157_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( m_0_reg_74 );

    SC_METHOD(thread_icmp_ln75_fu_229_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_0_reg_85 );

    SC_METHOD(thread_icmp_ln77_fu_294_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( j_0_reg_96 );

    SC_METHOD(thread_icmp_ln80_fu_328_p2);
    sensitive << ( zext_ln80_1_reg_455 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( x_0_reg_121 );

    SC_METHOD(thread_icmp_ln81_fu_386_p2);
    sensitive << ( zext_ln81_1_reg_478 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( y_0_reg_143 );

    SC_METHOD(thread_in_r_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln83_3_fu_400_p1 );

    SC_METHOD(thread_in_r_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_j_fu_300_p2);
    sensitive << ( j_0_reg_96 );

    SC_METHOD(thread_m_fu_163_p2);
    sensitive << ( m_0_reg_74 );

    SC_METHOD(thread_max_record_2_fu_417_p3);
    sensitive << ( max_record_reg_509 );
    sensitive << ( max_record_1_reg_131 );
    sensitive << ( tmp_fu_152_p2 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln87_3_fu_381_p1 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( max_record_0_reg_108 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln80_fu_328_p2 );

    SC_METHOD(thread_p_shl3_cast_fu_280_p3);
    sensitive << ( trunc_ln87_fu_276_p1 );

    SC_METHOD(thread_p_shl4_cast_fu_346_p3);
    sensitive << ( trunc_ln83_fu_342_p1 );

    SC_METHOD(thread_p_shl5_cast_fu_358_p3);
    sensitive << ( trunc_ln83_1_fu_354_p1 );

    SC_METHOD(thread_sext_ln83_1_fu_333_p1);
    sensitive << ( x_0_reg_121 );

    SC_METHOD(thread_sext_ln83_fu_203_p1);
    sensitive << ( sub_ln83_fu_197_p2 );

    SC_METHOD(thread_sext_ln87_1_fu_272_p1);
    sensitive << ( add_ln87_fu_267_p2 );

    SC_METHOD(thread_sext_ln87_fu_225_p1);
    sensitive << ( sub_ln87_fu_219_p2 );

    SC_METHOD(thread_sub_ln83_1_fu_366_p2);
    sensitive << ( p_shl4_cast_fu_346_p3 );
    sensitive << ( p_shl5_cast_fu_358_p3 );

    SC_METHOD(thread_sub_ln83_fu_197_p2);
    sensitive << ( zext_ln83_1_fu_181_p1 );
    sensitive << ( zext_ln83_2_fu_193_p1 );

    SC_METHOD(thread_sub_ln87_1_fu_288_p2);
    sensitive << ( p_shl3_cast_fu_280_p3 );
    sensitive << ( sext_ln87_1_fu_272_p1 );

    SC_METHOD(thread_sub_ln87_fu_219_p2);
    sensitive << ( zext_ln87_fu_215_p1 );
    sensitive << ( zext_ln83_fu_169_p1 );

    SC_METHOD(thread_tmp_1_fu_185_p3);
    sensitive << ( m_0_reg_74 );

    SC_METHOD(thread_tmp_2_fu_207_p3);
    sensitive << ( m_0_reg_74 );

    SC_METHOD(thread_tmp_s_fu_173_p3);
    sensitive << ( m_0_reg_74 );

    SC_METHOD(thread_trunc_ln83_1_fu_354_p1);
    sensitive << ( add_ln83_fu_337_p2 );

    SC_METHOD(thread_trunc_ln83_2_fu_391_p1);
    sensitive << ( y_0_reg_143 );

    SC_METHOD(thread_trunc_ln83_fu_342_p1);
    sensitive << ( add_ln83_fu_337_p2 );

    SC_METHOD(thread_trunc_ln87_fu_276_p1);
    sensitive << ( add_ln87_fu_267_p2 );

    SC_METHOD(thread_x_1_fu_411_p2);
    sensitive << ( x_0_reg_121 );

    SC_METHOD(thread_x_fu_241_p3);
    sensitive << ( i_0_reg_85 );

    SC_METHOD(thread_y_1_fu_405_p2);
    sensitive << ( y_0_reg_143 );

    SC_METHOD(thread_y_fu_306_p3);
    sensitive << ( j_0_reg_96 );

    SC_METHOD(thread_zext_ln80_1_fu_259_p1);
    sensitive << ( add_ln80_fu_253_p2 );

    SC_METHOD(thread_zext_ln80_fu_249_p1);
    sensitive << ( x_fu_241_p3 );

    SC_METHOD(thread_zext_ln81_1_fu_324_p1);
    sensitive << ( add_ln81_fu_318_p2 );

    SC_METHOD(thread_zext_ln81_fu_314_p1);
    sensitive << ( y_fu_306_p3 );

    SC_METHOD(thread_zext_ln83_1_fu_181_p1);
    sensitive << ( tmp_s_fu_173_p3 );

    SC_METHOD(thread_zext_ln83_2_fu_193_p1);
    sensitive << ( tmp_1_fu_185_p3 );

    SC_METHOD(thread_zext_ln83_3_fu_400_p1);
    sensitive << ( add_ln83_1_fu_395_p2 );

    SC_METHOD(thread_zext_ln83_fu_169_p1);
    sensitive << ( m_0_reg_74 );

    SC_METHOD(thread_zext_ln87_1_fu_263_p1);
    sensitive << ( i_0_reg_85 );

    SC_METHOD(thread_zext_ln87_2_fu_372_p1);
    sensitive << ( j_0_reg_96 );

    SC_METHOD(thread_zext_ln87_3_fu_381_p1);
    sensitive << ( add_ln87_1_fu_376_p2 );

    SC_METHOD(thread_zext_ln87_fu_215_p1);
    sensitive << ( tmp_2_fu_207_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln73_fu_157_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln75_fu_229_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln77_fu_294_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln80_fu_328_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln81_fu_386_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "max_pool_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r_address0, "(port)in_r_address0");
    sc_trace(mVcdFile, in_r_ce0, "(port)in_r_ce0");
    sc_trace(mVcdFile, in_r_q0, "(port)in_r_q0");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, m_fu_163_p2, "m_fu_163_p2");
    sc_trace(mVcdFile, m_reg_427, "m_reg_427");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sext_ln83_fu_203_p1, "sext_ln83_fu_203_p1");
    sc_trace(mVcdFile, sext_ln83_reg_432, "sext_ln83_reg_432");
    sc_trace(mVcdFile, icmp_ln73_fu_157_p2, "icmp_ln73_fu_157_p2");
    sc_trace(mVcdFile, sext_ln87_fu_225_p1, "sext_ln87_fu_225_p1");
    sc_trace(mVcdFile, sext_ln87_reg_437, "sext_ln87_reg_437");
    sc_trace(mVcdFile, i_fu_235_p2, "i_fu_235_p2");
    sc_trace(mVcdFile, i_reg_445, "i_reg_445");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln80_fu_249_p1, "zext_ln80_fu_249_p1");
    sc_trace(mVcdFile, zext_ln80_reg_450, "zext_ln80_reg_450");
    sc_trace(mVcdFile, icmp_ln75_fu_229_p2, "icmp_ln75_fu_229_p2");
    sc_trace(mVcdFile, zext_ln80_1_fu_259_p1, "zext_ln80_1_fu_259_p1");
    sc_trace(mVcdFile, zext_ln80_1_reg_455, "zext_ln80_1_reg_455");
    sc_trace(mVcdFile, sub_ln87_1_fu_288_p2, "sub_ln87_1_fu_288_p2");
    sc_trace(mVcdFile, sub_ln87_1_reg_460, "sub_ln87_1_reg_460");
    sc_trace(mVcdFile, j_fu_300_p2, "j_fu_300_p2");
    sc_trace(mVcdFile, j_reg_468, "j_reg_468");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln81_fu_314_p1, "zext_ln81_fu_314_p1");
    sc_trace(mVcdFile, zext_ln81_reg_473, "zext_ln81_reg_473");
    sc_trace(mVcdFile, icmp_ln77_fu_294_p2, "icmp_ln77_fu_294_p2");
    sc_trace(mVcdFile, zext_ln81_1_fu_324_p1, "zext_ln81_1_fu_324_p1");
    sc_trace(mVcdFile, zext_ln81_1_reg_478, "zext_ln81_1_reg_478");
    sc_trace(mVcdFile, sub_ln83_1_fu_366_p2, "sub_ln83_1_fu_366_p2");
    sc_trace(mVcdFile, sub_ln83_1_reg_486, "sub_ln83_1_reg_486");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln80_fu_328_p2, "icmp_ln80_fu_328_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln81_fu_386_p2, "icmp_ln81_fu_386_p2");
    sc_trace(mVcdFile, y_1_fu_405_p2, "y_1_fu_405_p2");
    sc_trace(mVcdFile, y_1_reg_499, "y_1_reg_499");
    sc_trace(mVcdFile, x_1_fu_411_p2, "x_1_fu_411_p2");
    sc_trace(mVcdFile, max_record_reg_509, "max_record_reg_509");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, max_record_2_fu_417_p3, "max_record_2_fu_417_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, m_0_reg_74, "m_0_reg_74");
    sc_trace(mVcdFile, i_0_reg_85, "i_0_reg_85");
    sc_trace(mVcdFile, j_0_reg_96, "j_0_reg_96");
    sc_trace(mVcdFile, max_record_0_reg_108, "max_record_0_reg_108");
    sc_trace(mVcdFile, x_0_reg_121, "x_0_reg_121");
    sc_trace(mVcdFile, max_record_1_reg_131, "max_record_1_reg_131");
    sc_trace(mVcdFile, y_0_reg_143, "y_0_reg_143");
    sc_trace(mVcdFile, zext_ln87_3_fu_381_p1, "zext_ln87_3_fu_381_p1");
    sc_trace(mVcdFile, zext_ln83_3_fu_400_p1, "zext_ln83_3_fu_400_p1");
    sc_trace(mVcdFile, tmp_s_fu_173_p3, "tmp_s_fu_173_p3");
    sc_trace(mVcdFile, tmp_1_fu_185_p3, "tmp_1_fu_185_p3");
    sc_trace(mVcdFile, zext_ln83_1_fu_181_p1, "zext_ln83_1_fu_181_p1");
    sc_trace(mVcdFile, zext_ln83_2_fu_193_p1, "zext_ln83_2_fu_193_p1");
    sc_trace(mVcdFile, sub_ln83_fu_197_p2, "sub_ln83_fu_197_p2");
    sc_trace(mVcdFile, tmp_2_fu_207_p3, "tmp_2_fu_207_p3");
    sc_trace(mVcdFile, zext_ln87_fu_215_p1, "zext_ln87_fu_215_p1");
    sc_trace(mVcdFile, zext_ln83_fu_169_p1, "zext_ln83_fu_169_p1");
    sc_trace(mVcdFile, sub_ln87_fu_219_p2, "sub_ln87_fu_219_p2");
    sc_trace(mVcdFile, x_fu_241_p3, "x_fu_241_p3");
    sc_trace(mVcdFile, add_ln80_fu_253_p2, "add_ln80_fu_253_p2");
    sc_trace(mVcdFile, zext_ln87_1_fu_263_p1, "zext_ln87_1_fu_263_p1");
    sc_trace(mVcdFile, add_ln87_fu_267_p2, "add_ln87_fu_267_p2");
    sc_trace(mVcdFile, trunc_ln87_fu_276_p1, "trunc_ln87_fu_276_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_280_p3, "p_shl3_cast_fu_280_p3");
    sc_trace(mVcdFile, sext_ln87_1_fu_272_p1, "sext_ln87_1_fu_272_p1");
    sc_trace(mVcdFile, y_fu_306_p3, "y_fu_306_p3");
    sc_trace(mVcdFile, add_ln81_fu_318_p2, "add_ln81_fu_318_p2");
    sc_trace(mVcdFile, sext_ln83_1_fu_333_p1, "sext_ln83_1_fu_333_p1");
    sc_trace(mVcdFile, add_ln83_fu_337_p2, "add_ln83_fu_337_p2");
    sc_trace(mVcdFile, trunc_ln83_fu_342_p1, "trunc_ln83_fu_342_p1");
    sc_trace(mVcdFile, trunc_ln83_1_fu_354_p1, "trunc_ln83_1_fu_354_p1");
    sc_trace(mVcdFile, p_shl4_cast_fu_346_p3, "p_shl4_cast_fu_346_p3");
    sc_trace(mVcdFile, p_shl5_cast_fu_358_p3, "p_shl5_cast_fu_358_p3");
    sc_trace(mVcdFile, zext_ln87_2_fu_372_p1, "zext_ln87_2_fu_372_p1");
    sc_trace(mVcdFile, add_ln87_1_fu_376_p2, "add_ln87_1_fu_376_p2");
    sc_trace(mVcdFile, trunc_ln83_2_fu_391_p1, "trunc_ln83_2_fu_391_p1");
    sc_trace(mVcdFile, add_ln83_1_fu_395_p2, "add_ln83_1_fu_395_p2");
    sc_trace(mVcdFile, tmp_fu_152_p2, "tmp_fu_152_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

max_pool_1::~max_pool_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete test_hcmp_16ns_16g8j_U31;
}

void max_pool_1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv5_2;
}

void max_pool_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln77_fu_294_p2.read(), ap_const_lv1_1))) {
        i_0_reg_85 = i_reg_445.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln73_fu_157_p2.read(), ap_const_lv1_0))) {
        i_0_reg_85 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln75_fu_229_p2.read()))) {
        j_0_reg_96 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_fu_328_p2.read()))) {
        j_0_reg_96 = j_reg_468.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln75_fu_229_p2.read(), ap_const_lv1_1))) {
        m_0_reg_74 = m_reg_427.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        m_0_reg_74 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln81_fu_386_p2.read()))) {
        max_record_0_reg_108 = max_record_1_reg_131.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln77_fu_294_p2.read()))) {
        max_record_0_reg_108 = ap_const_lv16_FC00;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        max_record_1_reg_131 = max_record_2_fu_417_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(icmp_ln80_fu_328_p2.read(), ap_const_lv1_1))) {
        max_record_1_reg_131 = max_record_0_reg_108.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln81_fu_386_p2.read()))) {
        x_0_reg_121 = x_1_fu_411_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln77_fu_294_p2.read()))) {
        x_0_reg_121 = zext_ln80_reg_450.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        y_0_reg_143 = y_1_reg_499.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(icmp_ln80_fu_328_p2.read(), ap_const_lv1_1))) {
        y_0_reg_143 = zext_ln81_reg_473.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_reg_445 = i_fu_235_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_reg_468 = j_fu_300_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        m_reg_427 = m_fu_163_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        max_record_reg_509 = in_r_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln73_fu_157_p2.read(), ap_const_lv1_0))) {
        sext_ln83_reg_432 = sext_ln83_fu_203_p1.read();
        sext_ln87_reg_437 = sext_ln87_fu_225_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln80_fu_328_p2.read(), ap_const_lv1_1))) {
        sub_ln83_1_reg_486 = sub_ln83_1_fu_366_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln75_fu_229_p2.read()))) {
        sub_ln87_1_reg_460 = sub_ln87_1_fu_288_p2.read();
        zext_ln80_1_reg_455 = zext_ln80_1_fu_259_p1.read();
        zext_ln80_reg_450 = zext_ln80_fu_249_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln81_fu_386_p2.read()))) {
        y_1_reg_499 = y_1_fu_405_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln77_fu_294_p2.read()))) {
        zext_ln81_1_reg_478 = zext_ln81_1_fu_324_p1.read();
        zext_ln81_reg_473 = zext_ln81_fu_314_p1.read();
    }
}

void max_pool_1::thread_add_ln80_fu_253_p2() {
    add_ln80_fu_253_p2 = (!ap_const_lv4_2.is_01() || !x_fu_241_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_2) + sc_biguint<4>(x_fu_241_p3.read()));
}

void max_pool_1::thread_add_ln81_fu_318_p2() {
    add_ln81_fu_318_p2 = (!y_fu_306_p3.read().is_01() || !ap_const_lv4_2.is_01())? sc_lv<4>(): (sc_biguint<4>(y_fu_306_p3.read()) + sc_biguint<4>(ap_const_lv4_2));
}

void max_pool_1::thread_add_ln83_1_fu_395_p2() {
    add_ln83_1_fu_395_p2 = (!sub_ln83_1_reg_486.read().is_01() || !trunc_ln83_2_fu_391_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(sub_ln83_1_reg_486.read()) + sc_biguint<13>(trunc_ln83_2_fu_391_p1.read()));
}

void max_pool_1::thread_add_ln83_fu_337_p2() {
    add_ln83_fu_337_p2 = (!sext_ln83_1_fu_333_p1.read().is_01() || !sext_ln83_reg_432.read().is_01())? sc_lv<33>(): (sc_bigint<33>(sext_ln83_1_fu_333_p1.read()) + sc_bigint<33>(sext_ln83_reg_432.read()));
}

void max_pool_1::thread_add_ln87_1_fu_376_p2() {
    add_ln87_1_fu_376_p2 = (!sub_ln87_1_reg_460.read().is_01() || !zext_ln87_2_fu_372_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(sub_ln87_1_reg_460.read()) + sc_biguint<11>(zext_ln87_2_fu_372_p1.read()));
}

void max_pool_1::thread_add_ln87_fu_267_p2() {
    add_ln87_fu_267_p2 = (!sext_ln87_reg_437.read().is_01() || !zext_ln87_1_fu_263_p1.read().is_01())? sc_lv<10>(): (sc_bigint<10>(sext_ln87_reg_437.read()) + sc_biguint<10>(zext_ln87_1_fu_263_p1.read()));
}

void max_pool_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void max_pool_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void max_pool_1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void max_pool_1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void max_pool_1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void max_pool_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void max_pool_1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void max_pool_1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void max_pool_1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln73_fu_157_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void max_pool_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void max_pool_1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln73_fu_157_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void max_pool_1::thread_i_fu_235_p2() {
    i_fu_235_p2 = (!i_0_reg_85.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_0_reg_85.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void max_pool_1::thread_icmp_ln73_fu_157_p2() {
    icmp_ln73_fu_157_p2 = (!m_0_reg_74.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(m_0_reg_74.read() == ap_const_lv5_10);
}

void max_pool_1::thread_icmp_ln75_fu_229_p2() {
    icmp_ln75_fu_229_p2 = (!i_0_reg_85.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_85.read() == ap_const_lv3_7);
}

void max_pool_1::thread_icmp_ln77_fu_294_p2() {
    icmp_ln77_fu_294_p2 = (!j_0_reg_96.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_96.read() == ap_const_lv3_7);
}

void max_pool_1::thread_icmp_ln80_fu_328_p2() {
    icmp_ln80_fu_328_p2 = (!x_0_reg_121.read().is_01() || !zext_ln80_1_reg_455.read().is_01())? sc_lv<1>(): (sc_bigint<32>(x_0_reg_121.read()) < sc_bigint<32>(zext_ln80_1_reg_455.read()));
}

void max_pool_1::thread_icmp_ln81_fu_386_p2() {
    icmp_ln81_fu_386_p2 = (!y_0_reg_143.read().is_01() || !zext_ln81_1_reg_478.read().is_01())? sc_lv<1>(): (sc_bigint<32>(y_0_reg_143.read()) < sc_bigint<32>(zext_ln81_1_reg_478.read()));
}

void max_pool_1::thread_in_r_address0() {
    in_r_address0 =  (sc_lv<12>) (zext_ln83_3_fu_400_p1.read());
}

void max_pool_1::thread_in_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        in_r_ce0 = ap_const_logic_1;
    } else {
        in_r_ce0 = ap_const_logic_0;
    }
}

void max_pool_1::thread_j_fu_300_p2() {
    j_fu_300_p2 = (!j_0_reg_96.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j_0_reg_96.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void max_pool_1::thread_m_fu_163_p2() {
    m_fu_163_p2 = (!m_0_reg_74.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(m_0_reg_74.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void max_pool_1::thread_max_record_2_fu_417_p3() {
    max_record_2_fu_417_p3 = (!tmp_fu_152_p2.read()[0].is_01())? sc_lv<16>(): ((tmp_fu_152_p2.read()[0].to_bool())? max_record_reg_509.read(): max_record_1_reg_131.read());
}

void max_pool_1::thread_out_r_address0() {
    out_r_address0 =  (sc_lv<10>) (zext_ln87_3_fu_381_p1.read());
}

void max_pool_1::thread_out_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        out_r_ce0 = ap_const_logic_1;
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void max_pool_1::thread_out_r_d0() {
    out_r_d0 = max_record_0_reg_108.read();
}

void max_pool_1::thread_out_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_fu_328_p2.read()))) {
        out_r_we0 = ap_const_logic_1;
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void max_pool_1::thread_p_shl3_cast_fu_280_p3() {
    p_shl3_cast_fu_280_p3 = esl_concat<8,3>(trunc_ln87_fu_276_p1.read(), ap_const_lv3_0);
}

void max_pool_1::thread_p_shl4_cast_fu_346_p3() {
    p_shl4_cast_fu_346_p3 = esl_concat<9,4>(trunc_ln83_fu_342_p1.read(), ap_const_lv4_0);
}

void max_pool_1::thread_p_shl5_cast_fu_358_p3() {
    p_shl5_cast_fu_358_p3 = esl_concat<12,1>(trunc_ln83_1_fu_354_p1.read(), ap_const_lv1_0);
}

void max_pool_1::thread_sext_ln83_1_fu_333_p1() {
    sext_ln83_1_fu_333_p1 = esl_sext<33,32>(x_0_reg_121.read());
}

void max_pool_1::thread_sext_ln83_fu_203_p1() {
    sext_ln83_fu_203_p1 = esl_sext<33,10>(sub_ln83_fu_197_p2.read());
}

void max_pool_1::thread_sext_ln87_1_fu_272_p1() {
    sext_ln87_1_fu_272_p1 = esl_sext<11,10>(add_ln87_fu_267_p2.read());
}

void max_pool_1::thread_sext_ln87_fu_225_p1() {
    sext_ln87_fu_225_p1 = esl_sext<10,9>(sub_ln87_fu_219_p2.read());
}

void max_pool_1::thread_sub_ln83_1_fu_366_p2() {
    sub_ln83_1_fu_366_p2 = (!p_shl4_cast_fu_346_p3.read().is_01() || !p_shl5_cast_fu_358_p3.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl4_cast_fu_346_p3.read()) - sc_biguint<13>(p_shl5_cast_fu_358_p3.read()));
}

void max_pool_1::thread_sub_ln83_fu_197_p2() {
    sub_ln83_fu_197_p2 = (!zext_ln83_1_fu_181_p1.read().is_01() || !zext_ln83_2_fu_193_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln83_1_fu_181_p1.read()) - sc_biguint<10>(zext_ln83_2_fu_193_p1.read()));
}

void max_pool_1::thread_sub_ln87_1_fu_288_p2() {
    sub_ln87_1_fu_288_p2 = (!p_shl3_cast_fu_280_p3.read().is_01() || !sext_ln87_1_fu_272_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl3_cast_fu_280_p3.read()) - sc_bigint<11>(sext_ln87_1_fu_272_p1.read()));
}

void max_pool_1::thread_sub_ln87_fu_219_p2() {
    sub_ln87_fu_219_p2 = (!zext_ln87_fu_215_p1.read().is_01() || !zext_ln83_fu_169_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln87_fu_215_p1.read()) - sc_biguint<9>(zext_ln83_fu_169_p1.read()));
}

void max_pool_1::thread_tmp_1_fu_185_p3() {
    tmp_1_fu_185_p3 = esl_concat<5,1>(m_0_reg_74.read(), ap_const_lv1_0);
}

void max_pool_1::thread_tmp_2_fu_207_p3() {
    tmp_2_fu_207_p3 = esl_concat<5,3>(m_0_reg_74.read(), ap_const_lv3_0);
}

void max_pool_1::thread_tmp_s_fu_173_p3() {
    tmp_s_fu_173_p3 = esl_concat<5,4>(m_0_reg_74.read(), ap_const_lv4_0);
}

void max_pool_1::thread_trunc_ln83_1_fu_354_p1() {
    trunc_ln83_1_fu_354_p1 = add_ln83_fu_337_p2.read().range(12-1, 0);
}

void max_pool_1::thread_trunc_ln83_2_fu_391_p1() {
    trunc_ln83_2_fu_391_p1 = y_0_reg_143.read().range(13-1, 0);
}

void max_pool_1::thread_trunc_ln83_fu_342_p1() {
    trunc_ln83_fu_342_p1 = add_ln83_fu_337_p2.read().range(9-1, 0);
}

void max_pool_1::thread_trunc_ln87_fu_276_p1() {
    trunc_ln87_fu_276_p1 = add_ln87_fu_267_p2.read().range(8-1, 0);
}

void max_pool_1::thread_x_1_fu_411_p2() {
    x_1_fu_411_p2 = (!x_0_reg_121.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(x_0_reg_121.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void max_pool_1::thread_x_fu_241_p3() {
    x_fu_241_p3 = esl_concat<3,1>(i_0_reg_85.read(), ap_const_lv1_0);
}

void max_pool_1::thread_y_1_fu_405_p2() {
    y_1_fu_405_p2 = (!ap_const_lv32_1.is_01() || !y_0_reg_143.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(y_0_reg_143.read()));
}

void max_pool_1::thread_y_fu_306_p3() {
    y_fu_306_p3 = esl_concat<3,1>(j_0_reg_96.read(), ap_const_lv1_0);
}

void max_pool_1::thread_zext_ln80_1_fu_259_p1() {
    zext_ln80_1_fu_259_p1 = esl_zext<32,4>(add_ln80_fu_253_p2.read());
}

void max_pool_1::thread_zext_ln80_fu_249_p1() {
    zext_ln80_fu_249_p1 = esl_zext<32,4>(x_fu_241_p3.read());
}

void max_pool_1::thread_zext_ln81_1_fu_324_p1() {
    zext_ln81_1_fu_324_p1 = esl_zext<32,4>(add_ln81_fu_318_p2.read());
}

void max_pool_1::thread_zext_ln81_fu_314_p1() {
    zext_ln81_fu_314_p1 = esl_zext<32,4>(y_fu_306_p3.read());
}

void max_pool_1::thread_zext_ln83_1_fu_181_p1() {
    zext_ln83_1_fu_181_p1 = esl_zext<10,9>(tmp_s_fu_173_p3.read());
}

void max_pool_1::thread_zext_ln83_2_fu_193_p1() {
    zext_ln83_2_fu_193_p1 = esl_zext<10,6>(tmp_1_fu_185_p3.read());
}

void max_pool_1::thread_zext_ln83_3_fu_400_p1() {
    zext_ln83_3_fu_400_p1 = esl_zext<64,13>(add_ln83_1_fu_395_p2.read());
}

void max_pool_1::thread_zext_ln83_fu_169_p1() {
    zext_ln83_fu_169_p1 = esl_zext<9,5>(m_0_reg_74.read());
}

void max_pool_1::thread_zext_ln87_1_fu_263_p1() {
    zext_ln87_1_fu_263_p1 = esl_zext<10,3>(i_0_reg_85.read());
}

void max_pool_1::thread_zext_ln87_2_fu_372_p1() {
    zext_ln87_2_fu_372_p1 = esl_zext<11,3>(j_0_reg_96.read());
}

void max_pool_1::thread_zext_ln87_3_fu_381_p1() {
    zext_ln87_3_fu_381_p1 = esl_zext<64,11>(add_ln87_1_fu_376_p2.read());
}

void max_pool_1::thread_zext_ln87_fu_215_p1() {
    zext_ln87_fu_215_p1 = esl_zext<9,8>(tmp_2_fu_207_p3.read());
}

void max_pool_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln73_fu_157_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln75_fu_229_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln77_fu_294_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln80_fu_328_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln81_fu_386_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

