// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pad_3_34_0_8.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pad_3_34_0_8::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pad_3_34_0_8::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> pad_3_34_0_8::ap_ST_fsm_state1 = "1";
const sc_lv<5> pad_3_34_0_8::ap_ST_fsm_state2 = "10";
const sc_lv<5> pad_3_34_0_8::ap_ST_fsm_state3 = "100";
const sc_lv<5> pad_3_34_0_8::ap_ST_fsm_state4 = "1000";
const sc_lv<5> pad_3_34_0_8::ap_ST_fsm_state5 = "10000";
const sc_lv<32> pad_3_34_0_8::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pad_3_34_0_8::ap_const_lv32_1 = "1";
const sc_lv<1> pad_3_34_0_8::ap_const_lv1_0 = "0";
const sc_lv<32> pad_3_34_0_8::ap_const_lv32_2 = "10";
const sc_lv<32> pad_3_34_0_8::ap_const_lv32_3 = "11";
const sc_lv<2> pad_3_34_0_8::ap_const_lv2_0 = "00";
const sc_lv<1> pad_3_34_0_8::ap_const_lv1_1 = "1";
const sc_lv<6> pad_3_34_0_8::ap_const_lv6_0 = "000000";
const sc_lv<32> pad_3_34_0_8::ap_const_lv32_4 = "100";
const sc_lv<2> pad_3_34_0_8::ap_const_lv2_3 = "11";
const sc_lv<2> pad_3_34_0_8::ap_const_lv2_1 = "1";
const sc_lv<5> pad_3_34_0_8::ap_const_lv5_0 = "00000";
const sc_lv<6> pad_3_34_0_8::ap_const_lv6_22 = "100010";
const sc_lv<6> pad_3_34_0_8::ap_const_lv6_1 = "1";
const bool pad_3_34_0_8::ap_const_boolean_1 = true;

pad_3_34_0_8::pad_3_34_0_8(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln19_2_fu_154_p2);
    sensitive << ( add_ln19_reg_219 );
    sensitive << ( zext_ln19_4_fu_150_p1 );

    SC_METHOD(thread_add_ln19_3_fu_179_p2);
    sensitive << ( p_shl2_cast_fu_159_p3 );
    sensitive << ( zext_ln19_5_fu_175_p1 );

    SC_METHOD(thread_add_ln19_4_fu_201_p2);
    sensitive << ( add_ln19_3_reg_232 );
    sensitive << ( zext_ln19_6_fu_197_p1 );

    SC_METHOD(thread_add_ln19_fu_132_p2);
    sensitive << ( zext_ln19_3_fu_128_p1 );
    sensitive << ( zext_ln19_fu_116_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln11_fu_96_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln11_fu_96_p2 );

    SC_METHOD(thread_i_fu_102_p2);
    sensitive << ( i_0_reg_63 );

    SC_METHOD(thread_icmp_ln11_fu_96_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_63 );

    SC_METHOD(thread_icmp_ln13_fu_138_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_0_reg_74 );

    SC_METHOD(thread_icmp_ln15_fu_185_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( k_0_reg_85 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln19_7_fu_206_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_j_fu_144_p2);
    sensitive << ( j_0_reg_74 );

    SC_METHOD(thread_k_fu_191_p2);
    sensitive << ( k_0_reg_85 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( zext_ln19_7_reg_245 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( input_r_q0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_p_shl2_cast_fu_159_p3);
    sensitive << ( add_ln19_2_fu_154_p2 );

    SC_METHOD(thread_tmp_5_fu_167_p3);
    sensitive << ( add_ln19_2_fu_154_p2 );

    SC_METHOD(thread_tmp_fu_108_p3);
    sensitive << ( i_0_reg_63 );

    SC_METHOD(thread_tmp_s_fu_120_p3);
    sensitive << ( i_0_reg_63 );

    SC_METHOD(thread_zext_ln19_3_fu_128_p1);
    sensitive << ( tmp_s_fu_120_p3 );

    SC_METHOD(thread_zext_ln19_4_fu_150_p1);
    sensitive << ( j_0_reg_74 );

    SC_METHOD(thread_zext_ln19_5_fu_175_p1);
    sensitive << ( tmp_5_fu_167_p3 );

    SC_METHOD(thread_zext_ln19_6_fu_197_p1);
    sensitive << ( k_0_reg_85 );

    SC_METHOD(thread_zext_ln19_7_fu_206_p1);
    sensitive << ( add_ln19_4_fu_201_p2 );

    SC_METHOD(thread_zext_ln19_fu_116_p1);
    sensitive << ( tmp_fu_108_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln11_fu_96_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln13_fu_138_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln15_fu_185_p2 );

    ap_CS_fsm = "00001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pad_3_34_0_8_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_102_p2, "i_fu_102_p2");
    sc_trace(mVcdFile, i_reg_214, "i_reg_214");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln19_fu_132_p2, "add_ln19_fu_132_p2");
    sc_trace(mVcdFile, add_ln19_reg_219, "add_ln19_reg_219");
    sc_trace(mVcdFile, icmp_ln11_fu_96_p2, "icmp_ln11_fu_96_p2");
    sc_trace(mVcdFile, j_fu_144_p2, "j_fu_144_p2");
    sc_trace(mVcdFile, j_reg_227, "j_reg_227");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, add_ln19_3_fu_179_p2, "add_ln19_3_fu_179_p2");
    sc_trace(mVcdFile, add_ln19_3_reg_232, "add_ln19_3_reg_232");
    sc_trace(mVcdFile, icmp_ln13_fu_138_p2, "icmp_ln13_fu_138_p2");
    sc_trace(mVcdFile, k_fu_191_p2, "k_fu_191_p2");
    sc_trace(mVcdFile, k_reg_240, "k_reg_240");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln19_7_fu_206_p1, "zext_ln19_7_fu_206_p1");
    sc_trace(mVcdFile, zext_ln19_7_reg_245, "zext_ln19_7_reg_245");
    sc_trace(mVcdFile, icmp_ln15_fu_185_p2, "icmp_ln15_fu_185_p2");
    sc_trace(mVcdFile, i_0_reg_63, "i_0_reg_63");
    sc_trace(mVcdFile, j_0_reg_74, "j_0_reg_74");
    sc_trace(mVcdFile, k_0_reg_85, "k_0_reg_85");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_fu_108_p3, "tmp_fu_108_p3");
    sc_trace(mVcdFile, tmp_s_fu_120_p3, "tmp_s_fu_120_p3");
    sc_trace(mVcdFile, zext_ln19_3_fu_128_p1, "zext_ln19_3_fu_128_p1");
    sc_trace(mVcdFile, zext_ln19_fu_116_p1, "zext_ln19_fu_116_p1");
    sc_trace(mVcdFile, zext_ln19_4_fu_150_p1, "zext_ln19_4_fu_150_p1");
    sc_trace(mVcdFile, add_ln19_2_fu_154_p2, "add_ln19_2_fu_154_p2");
    sc_trace(mVcdFile, tmp_5_fu_167_p3, "tmp_5_fu_167_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_159_p3, "p_shl2_cast_fu_159_p3");
    sc_trace(mVcdFile, zext_ln19_5_fu_175_p1, "zext_ln19_5_fu_175_p1");
    sc_trace(mVcdFile, zext_ln19_6_fu_197_p1, "zext_ln19_6_fu_197_p1");
    sc_trace(mVcdFile, add_ln19_4_fu_201_p2, "add_ln19_4_fu_201_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

pad_3_34_0_8::~pad_3_34_0_8() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void pad_3_34_0_8::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln13_fu_138_p2.read(), ap_const_lv1_1))) {
        i_0_reg_63 = i_reg_214.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_63 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln15_fu_185_p2.read(), ap_const_lv1_1))) {
        j_0_reg_74 = j_reg_227.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln11_fu_96_p2.read(), ap_const_lv1_0))) {
        j_0_reg_74 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln13_fu_138_p2.read()))) {
        k_0_reg_85 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        k_0_reg_85 = k_reg_240.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln13_fu_138_p2.read()))) {
        add_ln19_3_reg_232 = add_ln19_3_fu_179_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln11_fu_96_p2.read(), ap_const_lv1_0))) {
        add_ln19_reg_219 = add_ln19_fu_132_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_214 = i_fu_102_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_reg_227 = j_fu_144_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        k_reg_240 = k_fu_191_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln15_fu_185_p2.read()))) {
        zext_ln19_7_reg_245 = zext_ln19_7_fu_206_p1.read();
    }
}

void pad_3_34_0_8::thread_add_ln19_2_fu_154_p2() {
    add_ln19_2_fu_154_p2 = (!zext_ln19_4_fu_150_p1.read().is_01() || !add_ln19_reg_219.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln19_4_fu_150_p1.read()) + sc_biguint<8>(add_ln19_reg_219.read()));
}

void pad_3_34_0_8::thread_add_ln19_3_fu_179_p2() {
    add_ln19_3_fu_179_p2 = (!p_shl2_cast_fu_159_p3.read().is_01() || !zext_ln19_5_fu_175_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl2_cast_fu_159_p3.read()) + sc_biguint<13>(zext_ln19_5_fu_175_p1.read()));
}

void pad_3_34_0_8::thread_add_ln19_4_fu_201_p2() {
    add_ln19_4_fu_201_p2 = (!add_ln19_3_reg_232.read().is_01() || !zext_ln19_6_fu_197_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(add_ln19_3_reg_232.read()) + sc_biguint<13>(zext_ln19_6_fu_197_p1.read()));
}

void pad_3_34_0_8::thread_add_ln19_fu_132_p2() {
    add_ln19_fu_132_p2 = (!zext_ln19_3_fu_128_p1.read().is_01() || !zext_ln19_fu_116_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln19_3_fu_128_p1.read()) + sc_biguint<8>(zext_ln19_fu_116_p1.read()));
}

void pad_3_34_0_8::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pad_3_34_0_8::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pad_3_34_0_8::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void pad_3_34_0_8::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void pad_3_34_0_8::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void pad_3_34_0_8::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln11_fu_96_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void pad_3_34_0_8::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pad_3_34_0_8::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln11_fu_96_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void pad_3_34_0_8::thread_i_fu_102_p2() {
    i_fu_102_p2 = (!i_0_reg_63.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_0_reg_63.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void pad_3_34_0_8::thread_icmp_ln11_fu_96_p2() {
    icmp_ln11_fu_96_p2 = (!i_0_reg_63.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_63.read() == ap_const_lv2_3);
}

void pad_3_34_0_8::thread_icmp_ln13_fu_138_p2() {
    icmp_ln13_fu_138_p2 = (!j_0_reg_74.read().is_01() || !ap_const_lv6_22.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_74.read() == ap_const_lv6_22);
}

void pad_3_34_0_8::thread_icmp_ln15_fu_185_p2() {
    icmp_ln15_fu_185_p2 = (!k_0_reg_85.read().is_01() || !ap_const_lv6_22.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_85.read() == ap_const_lv6_22);
}

void pad_3_34_0_8::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<12>) (zext_ln19_7_fu_206_p1.read());
}

void pad_3_34_0_8::thread_input_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void pad_3_34_0_8::thread_j_fu_144_p2() {
    j_fu_144_p2 = (!j_0_reg_74.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(j_0_reg_74.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void pad_3_34_0_8::thread_k_fu_191_p2() {
    k_fu_191_p2 = (!k_0_reg_85.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(k_0_reg_85.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void pad_3_34_0_8::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<12>) (zext_ln19_7_reg_245.read());
}

void pad_3_34_0_8::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void pad_3_34_0_8::thread_output_r_d0() {
    output_r_d0 = input_r_q0.read();
}

void pad_3_34_0_8::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void pad_3_34_0_8::thread_p_shl2_cast_fu_159_p3() {
    p_shl2_cast_fu_159_p3 = esl_concat<8,5>(add_ln19_2_fu_154_p2.read(), ap_const_lv5_0);
}

void pad_3_34_0_8::thread_tmp_5_fu_167_p3() {
    tmp_5_fu_167_p3 = esl_concat<8,1>(add_ln19_2_fu_154_p2.read(), ap_const_lv1_0);
}

void pad_3_34_0_8::thread_tmp_fu_108_p3() {
    tmp_fu_108_p3 = esl_concat<2,5>(i_0_reg_63.read(), ap_const_lv5_0);
}

void pad_3_34_0_8::thread_tmp_s_fu_120_p3() {
    tmp_s_fu_120_p3 = esl_concat<2,1>(i_0_reg_63.read(), ap_const_lv1_0);
}

void pad_3_34_0_8::thread_zext_ln19_3_fu_128_p1() {
    zext_ln19_3_fu_128_p1 = esl_zext<8,3>(tmp_s_fu_120_p3.read());
}

void pad_3_34_0_8::thread_zext_ln19_4_fu_150_p1() {
    zext_ln19_4_fu_150_p1 = esl_zext<8,6>(j_0_reg_74.read());
}

void pad_3_34_0_8::thread_zext_ln19_5_fu_175_p1() {
    zext_ln19_5_fu_175_p1 = esl_zext<13,9>(tmp_5_fu_167_p3.read());
}

void pad_3_34_0_8::thread_zext_ln19_6_fu_197_p1() {
    zext_ln19_6_fu_197_p1 = esl_zext<13,6>(k_0_reg_85.read());
}

void pad_3_34_0_8::thread_zext_ln19_7_fu_206_p1() {
    zext_ln19_7_fu_206_p1 = esl_zext<64,13>(add_ln19_4_fu_201_p2.read());
}

void pad_3_34_0_8::thread_zext_ln19_fu_116_p1() {
    zext_ln19_fu_116_p1 = esl_zext<8,7>(tmp_fu_108_p3.read());
}

void pad_3_34_0_8::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln11_fu_96_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln13_fu_138_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln15_fu_185_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm = "XXXXX";
            break;
    }
}

}

