// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "relu_8_49_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic relu_8_49_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic relu_8_49_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> relu_8_49_s::ap_ST_fsm_state1 = "1";
const sc_lv<7> relu_8_49_s::ap_ST_fsm_state2 = "10";
const sc_lv<7> relu_8_49_s::ap_ST_fsm_state3 = "100";
const sc_lv<7> relu_8_49_s::ap_ST_fsm_state4 = "1000";
const sc_lv<7> relu_8_49_s::ap_ST_fsm_state5 = "10000";
const sc_lv<7> relu_8_49_s::ap_ST_fsm_state6 = "100000";
const sc_lv<7> relu_8_49_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> relu_8_49_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> relu_8_49_s::ap_const_lv32_1 = "1";
const sc_lv<32> relu_8_49_s::ap_const_lv32_2 = "10";
const sc_lv<1> relu_8_49_s::ap_const_lv1_0 = "0";
const sc_lv<32> relu_8_49_s::ap_const_lv32_3 = "11";
const sc_lv<32> relu_8_49_s::ap_const_lv32_4 = "100";
const sc_lv<32> relu_8_49_s::ap_const_lv32_5 = "101";
const sc_lv<4> relu_8_49_s::ap_const_lv4_0 = "0000";
const sc_lv<1> relu_8_49_s::ap_const_lv1_1 = "1";
const sc_lv<9> relu_8_49_s::ap_const_lv9_0 = "000000000";
const sc_lv<6> relu_8_49_s::ap_const_lv6_0 = "000000";
const sc_lv<32> relu_8_49_s::ap_const_lv32_6 = "110";
const sc_lv<16> relu_8_49_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<9> relu_8_49_s::ap_const_lv9_31 = "110001";
const sc_lv<4> relu_8_49_s::ap_const_lv4_8 = "1000";
const sc_lv<4> relu_8_49_s::ap_const_lv4_1 = "1";
const sc_lv<6> relu_8_49_s::ap_const_lv6_31 = "110001";
const sc_lv<6> relu_8_49_s::ap_const_lv6_1 = "1";
const sc_lv<15> relu_8_49_s::ap_const_lv15_31 = "110001";
const sc_lv<5> relu_8_49_s::ap_const_lv5_2 = "10";
const bool relu_8_49_s::ap_const_boolean_1 = true;

relu_8_49_s::relu_8_49_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    test_hcmp_16ns_16g8j_U12 = new test_hcmp_16ns_16g8j<1,1,16,16,1>("test_hcmp_16ns_16g8j_U12");
    test_hcmp_16ns_16g8j_U12->din0(in_load_reg_235);
    test_hcmp_16ns_16g8j_U12->din1(ap_var_for_const0);
    test_hcmp_16ns_16g8j_U12->opcode(ap_var_for_const1);
    test_hcmp_16ns_16g8j_U12->dout(tmp_fu_103_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln96_fu_108_p2);
    sensitive << ( phi_mul_reg_69 );

    SC_METHOD(thread_add_ln99_1_fu_174_p2);
    sensitive << ( mul_ln99_reg_212 );
    sensitive << ( zext_ln99_2_fu_170_p1 );

    SC_METHOD(thread_add_ln99_fu_142_p2);
    sensitive << ( phi_mul_reg_69 );
    sensitive << ( zext_ln99_fu_138_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln96_fu_114_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln96_fu_114_p2 );

    SC_METHOD(thread_c_fu_164_p2);
    sensitive << ( c_0_reg_92 );

    SC_METHOD(thread_icmp_ln96_fu_114_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( m_0_reg_58 );

    SC_METHOD(thread_icmp_ln97_fu_126_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( r_0_reg_81 );

    SC_METHOD(thread_icmp_ln98_fu_158_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( c_0_reg_92 );

    SC_METHOD(thread_in_r_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln99_3_fu_179_p1 );

    SC_METHOD(thread_in_r_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_m_fu_120_p2);
    sensitive << ( m_0_reg_58 );

    SC_METHOD(thread_mul_ln99_fu_152_p0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( mul_ln99_fu_152_p00 );

    SC_METHOD(thread_mul_ln99_fu_152_p00);
    sensitive << ( add_ln99_fu_142_p2 );

    SC_METHOD(thread_mul_ln99_fu_152_p2);
    sensitive << ( mul_ln99_fu_152_p0 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( zext_ln99_3_reg_225 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( select_ln99_reg_241 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_r_fu_132_p2);
    sensitive << ( r_0_reg_81 );

    SC_METHOD(thread_select_ln99_fu_184_p3);
    sensitive << ( in_load_reg_235 );
    sensitive << ( tmp_fu_103_p2 );

    SC_METHOD(thread_zext_ln99_2_fu_170_p1);
    sensitive << ( c_0_reg_92 );

    SC_METHOD(thread_zext_ln99_3_fu_179_p1);
    sensitive << ( add_ln99_1_fu_174_p2 );

    SC_METHOD(thread_zext_ln99_fu_138_p1);
    sensitive << ( r_0_reg_81 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln97_fu_126_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln98_fu_158_p2 );
    sensitive << ( icmp_ln96_fu_114_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "relu_8_49_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r_address0, "(port)in_r_address0");
    sc_trace(mVcdFile, in_r_ce0, "(port)in_r_ce0");
    sc_trace(mVcdFile, in_r_q0, "(port)in_r_q0");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, add_ln96_fu_108_p2, "add_ln96_fu_108_p2");
    sc_trace(mVcdFile, add_ln96_reg_191, "add_ln96_reg_191");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, m_fu_120_p2, "m_fu_120_p2");
    sc_trace(mVcdFile, m_reg_199, "m_reg_199");
    sc_trace(mVcdFile, r_fu_132_p2, "r_fu_132_p2");
    sc_trace(mVcdFile, r_reg_207, "r_reg_207");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, mul_ln99_fu_152_p2, "mul_ln99_fu_152_p2");
    sc_trace(mVcdFile, mul_ln99_reg_212, "mul_ln99_reg_212");
    sc_trace(mVcdFile, icmp_ln97_fu_126_p2, "icmp_ln97_fu_126_p2");
    sc_trace(mVcdFile, c_fu_164_p2, "c_fu_164_p2");
    sc_trace(mVcdFile, c_reg_220, "c_reg_220");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln99_3_fu_179_p1, "zext_ln99_3_fu_179_p1");
    sc_trace(mVcdFile, zext_ln99_3_reg_225, "zext_ln99_3_reg_225");
    sc_trace(mVcdFile, icmp_ln98_fu_158_p2, "icmp_ln98_fu_158_p2");
    sc_trace(mVcdFile, in_load_reg_235, "in_load_reg_235");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, select_ln99_fu_184_p3, "select_ln99_fu_184_p3");
    sc_trace(mVcdFile, select_ln99_reg_241, "select_ln99_reg_241");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, m_0_reg_58, "m_0_reg_58");
    sc_trace(mVcdFile, phi_mul_reg_69, "phi_mul_reg_69");
    sc_trace(mVcdFile, r_0_reg_81, "r_0_reg_81");
    sc_trace(mVcdFile, icmp_ln96_fu_114_p2, "icmp_ln96_fu_114_p2");
    sc_trace(mVcdFile, c_0_reg_92, "c_0_reg_92");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, zext_ln99_fu_138_p1, "zext_ln99_fu_138_p1");
    sc_trace(mVcdFile, add_ln99_fu_142_p2, "add_ln99_fu_142_p2");
    sc_trace(mVcdFile, mul_ln99_fu_152_p0, "mul_ln99_fu_152_p0");
    sc_trace(mVcdFile, zext_ln99_2_fu_170_p1, "zext_ln99_2_fu_170_p1");
    sc_trace(mVcdFile, add_ln99_1_fu_174_p2, "add_ln99_1_fu_174_p2");
    sc_trace(mVcdFile, tmp_fu_103_p2, "tmp_fu_103_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul_ln99_fu_152_p00, "mul_ln99_fu_152_p00");
#endif

    }
}

relu_8_49_s::~relu_8_49_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete test_hcmp_16ns_16g8j_U12;
}

void relu_8_49_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv16_0;
}

void relu_8_49_s::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv5_2;
}

void relu_8_49_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_fu_126_p2.read(), ap_const_lv1_0))) {
        c_0_reg_92 = ap_const_lv6_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        c_0_reg_92 = c_reg_220.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_fu_126_p2.read(), ap_const_lv1_1))) {
        m_0_reg_58 = m_reg_199.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        m_0_reg_58 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_fu_126_p2.read(), ap_const_lv1_1))) {
        phi_mul_reg_69 = add_ln96_reg_191.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        phi_mul_reg_69 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_114_p2.read()))) {
        r_0_reg_81 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln98_fu_158_p2.read(), ap_const_lv1_1))) {
        r_0_reg_81 = r_reg_207.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln96_reg_191 = add_ln96_fu_108_p2.read();
        m_reg_199 = m_fu_120_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        c_reg_220 = c_fu_164_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        in_load_reg_235 = in_r_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln97_fu_126_p2.read(), ap_const_lv1_0))) {
        mul_ln99_reg_212 = mul_ln99_fu_152_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        r_reg_207 = r_fu_132_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        select_ln99_reg_241 = select_ln99_fu_184_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_158_p2.read()))) {
        zext_ln99_3_reg_225 = zext_ln99_3_fu_179_p1.read();
    }
}

void relu_8_49_s::thread_add_ln96_fu_108_p2() {
    add_ln96_fu_108_p2 = (!phi_mul_reg_69.read().is_01() || !ap_const_lv9_31.is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul_reg_69.read()) + sc_biguint<9>(ap_const_lv9_31));
}

void relu_8_49_s::thread_add_ln99_1_fu_174_p2() {
    add_ln99_1_fu_174_p2 = (!mul_ln99_reg_212.read().is_01() || !zext_ln99_2_fu_170_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(mul_ln99_reg_212.read()) + sc_biguint<15>(zext_ln99_2_fu_170_p1.read()));
}

void relu_8_49_s::thread_add_ln99_fu_142_p2() {
    add_ln99_fu_142_p2 = (!phi_mul_reg_69.read().is_01() || !zext_ln99_fu_138_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul_reg_69.read()) + sc_biguint<9>(zext_ln99_fu_138_p1.read()));
}

void relu_8_49_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void relu_8_49_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void relu_8_49_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void relu_8_49_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void relu_8_49_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void relu_8_49_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void relu_8_49_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void relu_8_49_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_fu_114_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void relu_8_49_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void relu_8_49_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_fu_114_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void relu_8_49_s::thread_c_fu_164_p2() {
    c_fu_164_p2 = (!c_0_reg_92.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(c_0_reg_92.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void relu_8_49_s::thread_icmp_ln96_fu_114_p2() {
    icmp_ln96_fu_114_p2 = (!m_0_reg_58.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(m_0_reg_58.read() == ap_const_lv4_8);
}

void relu_8_49_s::thread_icmp_ln97_fu_126_p2() {
    icmp_ln97_fu_126_p2 = (!r_0_reg_81.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(r_0_reg_81.read() == ap_const_lv6_31);
}

void relu_8_49_s::thread_icmp_ln98_fu_158_p2() {
    icmp_ln98_fu_158_p2 = (!c_0_reg_92.read().is_01() || !ap_const_lv6_31.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_92.read() == ap_const_lv6_31);
}

void relu_8_49_s::thread_in_r_address0() {
    in_r_address0 =  (sc_lv<15>) (zext_ln99_3_fu_179_p1.read());
}

void relu_8_49_s::thread_in_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        in_r_ce0 = ap_const_logic_1;
    } else {
        in_r_ce0 = ap_const_logic_0;
    }
}

void relu_8_49_s::thread_m_fu_120_p2() {
    m_fu_120_p2 = (!m_0_reg_58.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(m_0_reg_58.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void relu_8_49_s::thread_mul_ln99_fu_152_p0() {
    mul_ln99_fu_152_p0 =  (sc_lv<9>) (mul_ln99_fu_152_p00.read());
}

void relu_8_49_s::thread_mul_ln99_fu_152_p00() {
    mul_ln99_fu_152_p00 = esl_zext<15,9>(add_ln99_fu_142_p2.read());
}

void relu_8_49_s::thread_mul_ln99_fu_152_p2() {
    mul_ln99_fu_152_p2 = (!mul_ln99_fu_152_p0.read().is_01() || !ap_const_lv15_31.is_01())? sc_lv<15>(): sc_biguint<9>(mul_ln99_fu_152_p0.read()) * sc_biguint<15>(ap_const_lv15_31);
}

void relu_8_49_s::thread_out_r_address0() {
    out_r_address0 =  (sc_lv<15>) (zext_ln99_3_reg_225.read());
}

void relu_8_49_s::thread_out_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        out_r_ce0 = ap_const_logic_1;
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void relu_8_49_s::thread_out_r_d0() {
    out_r_d0 = select_ln99_reg_241.read();
}

void relu_8_49_s::thread_out_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        out_r_we0 = ap_const_logic_1;
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void relu_8_49_s::thread_r_fu_132_p2() {
    r_fu_132_p2 = (!r_0_reg_81.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(r_0_reg_81.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void relu_8_49_s::thread_select_ln99_fu_184_p3() {
    select_ln99_fu_184_p3 = (!tmp_fu_103_p2.read()[0].is_01())? sc_lv<16>(): ((tmp_fu_103_p2.read()[0].to_bool())? in_load_reg_235.read(): ap_const_lv16_0);
}

void relu_8_49_s::thread_zext_ln99_2_fu_170_p1() {
    zext_ln99_2_fu_170_p1 = esl_zext<15,6>(c_0_reg_92.read());
}

void relu_8_49_s::thread_zext_ln99_3_fu_179_p1() {
    zext_ln99_3_fu_179_p1 = esl_zext<64,15>(add_ln99_1_fu_174_p2.read());
}

void relu_8_49_s::thread_zext_ln99_fu_138_p1() {
    zext_ln99_fu_138_p1 = esl_zext<9,6>(r_0_reg_81.read());
}

void relu_8_49_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_fu_114_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln97_fu_126_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln98_fu_158_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

}

